// Decompiled by Opus. Names are provisional.
// Builds a "CalcedExplosion": a header followed by one entry per frame, each
// frame generated by 0x420d20 (an "ExplosionFrame" of the given size), with
// sizes stepping evenly from `from` towards `to`.

void* __cdecl FUN_004d83b0(char* name, unsigned int size);
void* __stdcall FUN_00420d20(int size);

struct ExplosionEntry {
    void* frame;                       // +0x0
    short kind;                        // +0x4
    short pad;
};

struct CalcedExplosion {
    short count;                       // +0x0
    char flag;                         // +0x2
    char unknown_3[0x25];
    ExplosionEntry entries[1];         // +0x28
};

// FUNCTION: 0x420cb0
CalcedExplosion* __stdcall FUN_00420cb0(int n, int from, int to)
{
    CalcedExplosion* e = (CalcedExplosion*)FUN_004d83b0("CalcedExplosion", n * 8 + 0x28);
    int step = (to - from) / n;
    e->count = n;
    e->flag = 0;
    for (int i = 0; i < n; i++) {
        e->entries[i].frame = FUN_00420d20(from);
        e->entries[i].kind = 2;
        from += step;
    }
    return e;
}
