// Generated by tools/globals.py from data/globals.csv: do not edit.
//
// Definitions of the most-referenced globals in link/globals.h, with the
// initial values the original exe holds. Pointers to strings become string
// literals and pointers to other globals in this file become their address;
// any other pointer is marked TODO. Not part of any build yet; see
// docs/linking.md.

#include "globals.h"

// 0x4fc490 .rdata (holds 17 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_004fc490[576] = {
    -80, 18, 80, 0, 32, 28, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    19, 0, 0, 0, 0, -88, 18, 80, 0, -100, 18, 80, 0, 96, 33, 64,
    0, 64, -105, 67, 0, 8, 0, 0, 0, 1, -128, 2, 0, 0, -116, 18,
    80, 0, -128, 18, 80, 0, 16, 48, 64, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 19, 96, 0, 1, 0, -128, 18, 80, 0, 116, 18, 80, 0, 64,
    48, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 96, 0, 1, 0,
    116, 18, 80, 0, 104, 18, 80, 0, 112, 48, 64, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 19, 96, 0, 1, 0, 92, 18, 80, 0, 80, 18, 80,
    0, -96, 48, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 96, 0,
    1, 0, 68, 18, 80, 0, 52, 18, 80, 0, -48, 48, 64, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 19, 96, 0, 1, 0, 32, 18, 80, 0, 52,
    18, 80, 0, 0, 49, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19,
    96, 0, 1, 0, 12, 18, 80, 0, 0, 18, 80, 0, 64, 38, 64, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 19, 12, 1, 16, 0, -16, 17, 80,
    0, 0, 18, 80, 0, 112, 43, 64, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 19, 64, 1, 12, 0, -28, 17, 80, 0, -52, 17, 80, 0, 16, 32,
    64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 64, 0, 4, 0, -68,
    17, 80, 0, -52, 17, 80, 0, 16, 32, 64, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 19, 0, 0, 0, 0, -84, 17, 80, 0, -96, 17, 80, 0,
    16, 45, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 36, 0, 0,
    0, -108, 17, 80, 0, -128, 17, 80, 0, -96, 45, 64, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 19, 36, 2, 0, 0, 116, 17, 80, 0, 96, 17,
    80, 0, -64, 47, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 36,
    0, 0, 0, 84, 17, 80, 0, 64, 17, 80, 0, -64, 28, 64, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 19, 4, 0, 0, 0, 48, 17, 80, 0,
    40, 17, 80, 0, -32, 28, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    19, 4, 0, 0, 0, 32, 17, 80, 0, 12, 17, 80, 0, -48, 31, 64,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 4, 2, 0, 0, -4, 16,
    80, 0, -100, 18, 80, 0, 0, 30, 64, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 19, 4, 0, 0, 0, -16, 16, 80, 0, -24, 16, 80, 0, -16,
    33, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 32, 0, 0, 0,
    -40, 16, 80, 0, -52, 16, 80, 0, 48, 36, 64, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 19, 4, 2, 0, 1, -64, 16, 80, 0, -84, 16, 80,
    0, 96, 49, 64, 0, -32, -108, 67, 0, 2, 0, 0, 0, 14, 0, 4,
    0, 0, -92, 16, 80, 0, -84, 16, 80, 0, 96, 49, 64, 0, -32, -108,
    67, 0, 2, 0, 0, 0, 7, 0, 4, 0, 0, -100, 16, 80
};
// 0x4fc6e8 .rdata (holds 21 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_004fc6e8[552] = {
    24, 21, 80, 0, -32, 95, 64, 0, 0, 0, 0, 0, 16, 0, 0, 0,
    15, 0, 0, 2, 0, 24, 21, 80, 0, 24, 21, 80, 0, -112, 96, 64,
    0, 0, 0, 0, 0, 16, 0, 0, 0, 15, 0, 0, 2, 1, 8, 21,
    80, 0, 0, 21, 80, 0, -48, 49, 64, 0, -32, -108, 67, 0, 18, 0,
    0, 0, 14, 2, 4, 0, 0, -12, 20, 80, 0, -24, 20, 80, 0, 0,
    99, 64, 0, -32, -108, 67, 0, 18, 0, 0, 0, 5, 0, 2, 0, 0,
    -40, 20, 80, 0, -60, 20, 80, 0, -96, 56, 64, 0, 64, -105, 67, 0,
    8, 0, 0, 0, 1, 16, 4, 0, 0, -72, 20, 80, 0, -100, 18, 80,
    0, -96, 52, 64, 0, 64, -105, 67, 0, 8, 0, 0, 0, 1, -128, 2,
    0, 0, -88, 20, 80, 0, -100, 18, 80, 0, 96, 50, 64, 0, 64, -105,
    67, 0, 8, 0, 0, 0, 1, 0, 6, 0, 0, -104, 20, 80, 0, -120,
    20, 80, 0, -112, 49, 64, 0, 64, -105, 67, 0, 8, 0, 0, 0, 1,
    -128, 6, 0, 0, 120, 20, 80, 0, 112, 20, 80, 0, -96, 97, 64, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 104, 20, 80,
    0, 92, 20, 80, 0, -96, 51, 64, 0, -32, -108, 67, 0, 18, 0, 0,
    0, 7, 18, 4, 0, 0, 84, 20, 80, 0, 76, 20, 80, 0, -128, 103,
    64, 0, 64, -105, 67, 0, 8, 0, 0, 0, 12, 0, 2, 0, 0, 60,
    20, 80, 0, 48, 20, 80, 0, 0, 105, 64, 0, 64, -105, 67, 0, 8,
    0, 0, 0, 13, 0, 4, 0, 0, 32, 20, 80, 0, 20, 20, 80, 0,
    -96, 106, 64, 0, 64, -105, 67, 0, 8, 0, 0, 0, 9, 0, 6, 0,
    0, 8, 20, 80, 0, 0, 18, 80, 0, 32, 58, 64, 0, 0, -116, 67,
    0, 19, 0, 0, 0, 0, 8, 5, 16, 0, -4, 19, 80, 0, 0, 18,
    80, 0, 112, 63, 64, 0, 64, -105, 67, 0, 24, 0, 0, 0, 6, 8,
    2, 16, 0, -16, 19, 80, 0, -32, 19, 80, 0, -128, 89, 64, 0, -32,
    -108, 67, 0, 18, 0, 0, 0, 7, 18, 4, 0, 0, -48, 19, 80, 0,
    -52, 16, 80, 0, 0, 83, 64, 0, -32, -108, 67, 0, 18, 0, 0, 0,
    6, 0, 2, 16, 0, -60, 19, 80, 0, -72, 19, 80, 0, 112, 66, 64,
    0, 64, -105, 67, 0, 8, 0, 0, 0, 4, 0, 2, 0, 0, -80, 19,
    80, 0, -96, 19, 80, 0, -80, 77, 64, 0, -32, -108, 67, 0, 18, 0,
    0, 0, 11, 0, 2, 0, 0, -108, 19, 80, 0, -120, 19, 80, 0, -48,
    74, 64, 0, -32, -108, 67, 0, 18, 0, 0, 0, 11, 0, 8, 16, 0,
    -128, 19, 80, 0, -120, 19, 80, 0, 48, 71, 64, 0, -32, -108, 67, 0,
    18, 0, 0, 0, 11, 0, 2, 16, 0, 116, 19, 80, 0, -52, 16, 80,
    0, 64, 87, 64, 0, 64, -105, 67, 0, 24, 0, 0, 0, 6, 0, 2,
    0, 0, 96, 19, 80
};
unsigned char DAT_004fca10[8] = {0, 40, 60, 80, 100, 80, 60, 40};  // 0x4fca10 .rdata
// 0x4fca18 .rdata (holds 21 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_004fca18[552] = {
    24, 21, 80, 0, -48, -9, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    15, 0, 0, 2, 0, -4, 26, 80, 0, 0, 21, 80, 0, 32, -6, 64,
    0, -32, -108, 67, 0, 2, 0, 0, 0, 14, 2, 4, 0, 0, -16, 26,
    80, 0, -24, 26, 80, 0, -32, 24, 65, 0, 64, -105, 67, 0, 8, 0,
    0, 0, 14, 0, 6, 0, 0, -40, 26, 80, 0, 76, 20, 80, 0, -80,
    17, 65, 0, 64, -105, 67, 0, 8, 0, 0, 0, 8, 0, 2, 0, 0,
    -52, 26, 80, 0, 48, 20, 80, 0, 96, 21, 65, 0, 64, -105, 67, 0,
    8, 0, 0, 0, 9, 0, 4, 0, 0, -64, 26, 80, 0, -24, 20, 80,
    0, -32, -5, 64, 0, -32, -108, 67, 0, 2, 0, 0, 0, 5, 0, 2,
    0, 0, -76, 26, 80, 0, 92, 20, 80, 0, 112, 14, 65, 0, -32, -108,
    67, 0, 2, 0, 0, 0, 7, 18, 4, 0, 0, -88, 26, 80, 0, -100,
    26, 80, 0, 80, 31, 65, 0, 64, -105, 67, 0, 8, 0, 0, 0, 2,
    0, 6, 0, 0, -112, 26, 80, 0, -128, 26, 80, 0, 64, 45, 65, 0,
    64, -105, 67, 0, 8, 0, 0, 0, 1, 0, 2, 0, 0, 116, 26, 80,
    0, -128, 26, 80, 0, 16, 39, 65, 0, 64, -105, 67, 0, 8, 0, 0,
    0, 1, 0, 2, 0, 0, 104, 26, 80, 0, -128, 26, 80, 0, 112, 52,
    65, 0, 64, -105, 67, 0, 8, 0, 0, 0, 1, 0, 2, 0, 0, 84,
    26, 80, 0, 0, 18, 80, 0, -128, 61, 65, 0, 0, -116, 67, 0, 3,
    0, 0, 0, 0, 8, 5, 16, 0, 64, 26, 80, 0, 0, 18, 80, 0,
    -128, 67, 65, 0, 64, -105, 67, 0, 8, 0, 0, 0, 6, 8, 2, 16,
    0, 48, 26, 80, 0, -32, 19, 80, 0, -16, 82, 65, 0, -32, -108, 67,
    0, 2, 0, 0, 0, 7, 18, 4, 0, 0, 28, 26, 80, 0, -52, 16,
    80, 0, 112, 78, 65, 0, -32, -108, 67, 0, 2, 0, 0, 0, 6, 0,
    2, 16, 0, 12, 26, 80, 0, -120, 19, 80, 0, 112, 71, 65, 0, -32,
    -108, 67, 0, 2, 0, 0, 0, 11, 0, 8, 16, 0, -4, 25, 80, 0,
    -120, 19, 80, 0, -128, 74, 65, 0, -32, -108, 67, 0, 2, 0, 0, 0,
    11, 0, 2, 16, 0, -24, 25, 80, 0, -32, 25, 80, 0, -64, 59, 65,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0, 0, 0, 0, -44, 25,
    80, 0, -64, 25, 80, 0, -32, 3, 65, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 19, 0, 6, 0, 0, -80, 25, 80, 0, -100, 25, 80, 0, 80,
    8, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0, 6, 0, 0,
    -116, 25, 80, 0, 124, 25, 80, 0, 80, 82, 65, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 19, 0, 2, 0, 0, 104, 25, 80, 0, 88, 25, 80,
    0, -96, -14, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0, 4,
    0, 0, 72, 25, 80
};
unsigned char DAT_004fcc68[8] = {4, 14, 10};  // 0x4fcc68 .rdata
unsigned char IID_IDirectDraw2[16] = {224, 243, 166, 179, 67, 43, 207, 17, 162, 222, 0, 170, 0, 185, 51, 86};  // 0x4fccd8 .rdata
// 0x4fcd78 .rdata
unsigned char DAT_004fcd78[32] = {
    65, 254, 62, 19, 220, 50, 208, 17, 156, 251, 0, 160, 201, 10, 67, 203,
    32, 109, 235, 209, 35, 137, 208, 17, 157, 151, 0, 160, 201, 10, 67, 203
};
unsigned char DAT_004fcd98[16] = {0, 196, 91, 104, 44, 157, 207, 17, 169, 205, 0, 170, 0, 104, 134, 227};  // 0x4fcd98 .rdata
// 0x4fce18 .rdata
unsigned char DAT_004fce18[112] = {
    128, 175, 180, 27, 3, 163, 208, 17, 156, 79, 0, 160, 201, 5, 66, 94,
    16, 248, 232, 47, 165, 178, 208, 17, 167, 135, 0, 0, 248, 3, 171, 252,
    161, 205, 44, 118, 22, 217, 208, 17, 186, 57, 0, 192, 79, 215, 237, 103,
    160, 32, 105, 245, 24, 210, 208, 17, 186, 57, 0, 192, 79, 215, 237, 103,
    34, 147, 49, 180, 13, 210, 208, 17, 186, 57, 0, 192, 79, 215, 237, 103,
    0, 64, 120, 72, 25, 210, 208, 17, 186, 57, 0, 192, 79, 215, 237, 103,
    96, 245, 24, 19, 44, 145, 208, 17, 157, 170, 0, 160, 201, 10, 67, 203
};
// 0x4fce88 .rdata
unsigned char DAT_004fce88[32] = {
    192, 22, 217, 7, 175, 224, 207, 17, 156, 78, 0, 160, 201, 5, 66, 94,
    64, 86, 185, 89, 103, 150, 208, 17, 167, 125, 0, 0, 248, 3, 171, 252
};
// 0x4fcea8 .rdata
unsigned char DAT_004fcea8[32] = {
    160, 137, 236, 120, 175, 224, 207, 17, 156, 78, 0, 160, 201, 5, 66, 94,
    112, 122, 90, 186, 191, 157, 208, 17, 156, 193, 0, 160, 201, 5, 66, 94
};
// 0x4fcee8 .rdata
unsigned char DAT_004fcee8[32] = {
    160, 77, 165, 196, 175, 224, 207, 17, 156, 78, 0, 160, 201, 5, 66, 94,
    160, 50, 50, 230, 191, 157, 208, 17, 156, 193, 0, 160, 201, 5, 66, 94
};
// 0x4fcf08 .rdata
unsigned char DAT_004fcf08[96] = {
    0, 206, 240, 242, 175, 224, 207, 17, 156, 78, 0, 160, 201, 5, 66, 94,
    70, 217, 212, 71, 232, 98, 207, 17, 147, 188, 68, 69, 83, 84, 0, 0,
    128, 7, 33, 176, 205, 137, 208, 17, 175, 8, 0, 160, 201, 37, 205, 22,
    131, 250, 154, 39, 129, 73, 206, 17, 165, 33, 0, 32, 175, 11, 229, 96,
    133, 250, 154, 39, 129, 73, 206, 17, 165, 33, 0, 32, 175, 11, 229, 96,
    132, 250, 154, 39, 129, 73, 206, 17, 165, 33, 0, 32, 175, 11, 229, 96
};
// 0x4fcf68 .rdata
unsigned char DAT_004fcf68[80] = {
    134, 250, 154, 39, 129, 73, 206, 17, 165, 33, 0, 32, 175, 11, 229, 96,
    129, 7, 33, 176, 205, 137, 208, 17, 175, 8, 0, 160, 201, 37, 205, 22,
    130, 7, 33, 176, 205, 137, 208, 17, 175, 8, 0, 160, 201, 37, 205, 22,
    131, 7, 33, 176, 205, 137, 208, 17, 175, 8, 0, 160, 201, 37, 205, 22,
    48, 172, 239, 49, 92, 81, 208, 17, 169, 170, 0, 170, 0, 97, 190, 147
};
char DAT_004fd050[200] = "Warning! The currently installed version of Microsoft%sDirectX may not function properly with Total Annihilation.%sPlease install the version of DirectX included on the%sTotal Annihilation setup CD.";  // 0x4fd050 .rdata
// 0x4fd288 .rdata (holds 2 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
unsigned char DAT_004fd288[25] = {
    232, 16, 80, 0, 160, 158, 67, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    15, 0, 0, 0, 0, 184, 25, 81
};
unsigned char DAT_004fd2a1[3] = {0};  // 0x4fd2a1 .rdata
double DAT_004fd2b0 = 6.28318530717958;  // 0x4fd2b0 .rdata
double DAT_004fd2b8 = 0.125;  // 0x4fd2b8 .rdata
const float DAT_004fd4c0 = 0.0f;  // 0x4fd4c0 .rdata
const float DAT_004fd4cc = 5.0f;  // 0x4fd4cc .rdata
float DAT_004fd750 = 0.003921568859368563f;  // 0x4fd750 .rdata
int DAT_004fdaf4 = 0;  // 0x4fdaf4 .rdata
int DAT_004fdaf8 = 0;  // 0x4fdaf8 .rdata
int DAT_004fdafc = 0;  // 0x4fdafc .rdata
double DAT_004fdbe8 = -0.06875;  // 0x4fdbe8 .rdata
char DAT_004fdbf0[40] = "Copyright 0000 Cavedog Entertainment";  // 0x4fdbf0 .rdata
int DAT_00501774 = 1;  // 0x501774 .data
// 0x501d18 .data
unsigned char DAT_00501d18[32] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 111, 110, 109, 108, 107, 106,
    88, 87, 86, 85, 84, 83, 82, 81, 80, 255, 255, 255, 255, 255, 255, 255
};
// 0x501d38 .data (holds 86 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
unsigned char DAT_00501d38[528] = {
    68, 36, 80, 0, 96, 110, 65, 0, 1, 0, 0, 0, 60, 36, 80, 0,
    176, 109, 65, 0, 1, 0, 0, 0, 48, 36, 80, 0, 240, 108, 65, 0,
    1, 0, 0, 0, 40, 36, 80, 0, 32, 109, 65, 0, 1, 0, 0, 0,
    32, 36, 80, 0, 208, 107, 65, 0, 1, 0, 0, 0, 24, 36, 80, 0,
    240, 103, 65, 0, 1, 0, 0, 0, 16, 36, 80, 0, 16, 104, 65, 0,
    1, 0, 0, 0, 8, 36, 80, 0, 32, 104, 65, 0, 1, 0, 0, 0,
    0, 36, 80, 0, 32, 100, 65, 0, 1, 0, 0, 0, 244, 35, 80, 0,
    16, 101, 65, 0, 1, 0, 0, 0, 236, 35, 80, 0, 80, 101, 65, 0,
    1, 0, 0, 0, 228, 35, 80, 0, 144, 101, 65, 0, 1, 0, 0, 0,
    216, 35, 80, 0, 192, 101, 65, 0, 1, 0, 0, 0, 208, 35, 80, 0,
    48, 102, 65, 0, 1, 0, 0, 0, 200, 35, 80, 0, 96, 102, 65, 0,
    1, 0, 0, 0, 192, 35, 80, 0, 144, 102, 65, 0, 1, 0, 0, 0,
    184, 35, 80, 0, 192, 102, 65, 0, 1, 0, 0, 0, 176, 35, 80, 0,
    16, 103, 65, 0, 1, 0, 0, 0, 164, 35, 80, 0, 96, 100, 65, 0,
    1, 0, 0, 0, 152, 35, 80, 0, 224, 117, 65, 0, 1, 0, 0, 0,
    144, 35, 80, 0, 208, 104, 65, 0, 1, 0, 0, 0, 132, 35, 80, 0,
    48, 113, 65, 0, 1, 0, 0, 0, 124, 35, 80, 0, 144, 114, 65, 0,
    1, 0, 0, 0, 116, 35, 80, 0, 0, 115, 65, 0, 1, 0, 0, 0,
    104, 35, 80, 0, 112, 117, 65, 0, 1, 0, 0, 0, 96, 35, 80, 0,
    224, 114, 65, 0, 1, 0, 0, 0, 88, 35, 80, 0, 80, 113, 65, 0,
    1, 0, 0, 0, 76, 35, 80, 0, 240, 113, 65, 0, 1, 0, 0, 0,
    64, 35, 80, 0, 224, 116, 65, 0, 1, 0, 0, 0, 60, 35, 80, 0,
    144, 110, 65, 0, 1, 0, 0, 0, 52, 35, 80, 0, 160, 119, 65, 0,
    1, 0, 0, 0, 40, 35, 80, 0, 160, 140, 65, 0, 1, 0, 0, 0,
    28, 35, 80, 0, 208, 140, 65, 0, 1, 0, 0, 0, 16, 35, 80, 0,
    144, 141, 65, 0, 1, 0, 0, 0, 0, 35, 80, 0, 80, 142, 65, 0,
    1, 0, 0, 0, 244, 34, 80, 0, 208, 143, 65, 0, 1, 0, 0, 0,
    232, 34, 80, 0, 144, 144, 65, 0, 1, 0, 0, 0, 220, 34, 80, 0,
    192, 148, 65, 0, 1, 0, 0, 0, 204, 34, 80, 0, 64, 147, 65, 0,
    1, 0, 0, 0, 188, 34, 80, 0, 0, 148, 65, 0, 1, 0, 0, 0,
    176, 34, 80, 0, 208, 148, 65, 0, 1, 0, 0, 0, 172, 34, 80, 0,
    64, 149, 65, 0, 1, 0, 0, 0, 168, 34, 80, 0, 80, 149, 65, 0,
    1
};
// 0x501f48 .data (holds 20 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
unsigned char DAT_00501f48[136] = {
    160, 34, 80, 0, 144, 112, 65, 0, 2, 0, 0, 0, 156, 34, 80, 0,
    192, 112, 65, 0, 2, 0, 0, 0, 148, 34, 80, 0, 80, 107, 65, 0,
    2, 0, 0, 0, 144, 34, 80, 0, 80, 109, 65, 0, 2, 0, 0, 0,
    136, 34, 80, 0, 128, 109, 65, 0, 2, 0, 0, 0, 124, 34, 80, 0,
    48, 112, 65, 0, 2, 0, 0, 0, 112, 34, 80, 0, 96, 112, 65, 0,
    2, 0, 0, 0, 104, 34, 80, 0, 64, 117, 65, 0, 2, 0, 0, 0,
    96, 34, 80, 0, 96, 119, 65, 0, 2, 0, 0, 0, 84, 34, 80, 0,
    0, 118, 65, 0, 2
};
// 0x501fd0 .data (holds 60 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
unsigned char DAT_00501fd0[372] = {
    224, 24, 80, 0, 128, 98, 65, 0, 4, 0, 0, 0, 76, 34, 80, 0,
    176, 106, 65, 0, 4, 0, 0, 0, 68, 34, 80, 0, 176, 100, 65, 0,
    4, 0, 0, 0, 60, 34, 80, 0, 208, 105, 65, 0, 4, 0, 0, 0,
    52, 34, 80, 0, 48, 106, 65, 0, 4, 0, 0, 0, 44, 34, 80, 0,
    48, 115, 65, 0, 4, 0, 0, 0, 32, 34, 80, 0, 224, 115, 65, 0,
    4, 0, 0, 0, 24, 34, 80, 0, 112, 99, 65, 0, 4, 0, 0, 0,
    16, 34, 80, 0, 16, 99, 65, 0, 4, 0, 0, 0, 8, 34, 80, 0,
    144, 99, 65, 0, 4, 0, 0, 0, 0, 34, 80, 0, 160, 99, 65, 0,
    4, 0, 0, 0, 244, 33, 80, 0, 96, 122, 65, 0, 4, 0, 0, 0,
    236, 33, 80, 0, 128, 99, 65, 0, 4, 0, 0, 0, 228, 33, 80, 0,
    48, 103, 65, 0, 4, 0, 0, 0, 220, 33, 80, 0, 224, 119, 65, 0,
    4, 0, 0, 0, 216, 33, 80, 0, 112, 98, 65, 0, 4, 0, 0, 0,
    208, 33, 80, 0, 64, 98, 65, 0, 4, 0, 0, 0, 200, 33, 80, 0,
    96, 104, 65, 0, 4, 0, 0, 0, 184, 33, 80, 0, 176, 139, 65, 0,
    4, 0, 0, 0, 176, 33, 80, 0, 32, 117, 65, 0, 4, 0, 0, 0,
    168, 33, 80, 0, 144, 116, 65, 0, 4, 0, 0, 0, 148, 33, 80, 0,
    208, 116, 65, 0, 4, 0, 0, 0, 140, 33, 80, 0, 48, 116, 65, 0,
    4, 0, 0, 0, 128, 33, 80, 0, 144, 106, 65, 0, 4, 0, 0, 0,
    120, 33, 80, 0, 128, 103, 65, 0, 4, 0, 0, 0, 108, 33, 80, 0,
    0, 110, 65, 0, 4, 0, 0, 0, 96, 33, 80, 0, 112, 140, 65, 0,
    4, 0, 0, 0, 84, 33, 80, 0, 48, 110, 65, 0, 4, 0, 0, 0,
    76, 33, 80, 0, 208, 99, 65, 0, 4, 0, 0, 0, 68, 33, 80, 0,
    0, 101, 65, 0, 4
};
char DAT_00502288[8] = "Mapping";  // 0x502288 .data
char DAT_005024fc[16] = "%s\\screenshots";  // 0x5024fc .data
const char DAT_00502820[8] = "guis";  // 0x502820 .data
char DAT_00502878[12] = "X Position";  // 0x502878 .data
char DAT_00502884[12] = "Z Position";  // 0x502884 .data
char DAT_00502890[8] = "Camera";  // 0x502890 .data
int DAT_00502898 = 1;  // 0x502898 .data
int DAT_0050289c = 1;  // 0x50289c .data
char DAT_005028f8[12] = "Campaign";  // 0x5028f8 .data
char DAT_00502910[4] = ".";  // 0x502910 .data
char DAT_00502a20[4] = "&G";  // 0x502a20 .data
char DAT_00502a78[12] = "Difficulty";  // 0x502a78 .data
char DAT_00502b38[8] = "Options";  // 0x502b38 .data
// 0x502bf8 .data
unsigned char DAT_00502bf8[64] = {
    0, 0, 1, 0, 2, 0, 3, 0, 2, 0, 1, 0, 6, 0, 5, 0,
    0, 0, 3, 0, 4, 0, 7, 0, 1, 0, 0, 0, 7, 0, 6, 0,
    3, 0, 2, 0, 5, 0, 4, 0, 4, 0, 5, 0, 6, 0, 7, 0,
    101, 120, 112, 108, 111, 100, 101, 112, 105, 101, 99, 101
};
const char DAT_00502e30[8] = "anims";  // 0x502e30 .data
char DAT_00502e78[12] = "Description";  // 0x502e78 .data
char DAT_00502f9c[104] = "Code segment checksum error found when switching FE states.\nState change called from [line %d, file %s]";  // 0x502f9c .data
char DAT_00503004[32] = "c:\\cavedog\\wargame\\frontend.cpp";  // 0x503004 .data
char DAT_0050310c[4] = "tdf";  // 0x50310c .data
char DAT_00503120[8] = "CHOICE2";  // 0x503120 .data
char DAT_00503128[8] = "CHOICE1";  // 0x503128 .data
char DAT_00503130[12] = "SmallButton";  // 0x503130 .data
char DAT_0050313c[8] = "TITLE";  // 0x50313c .data
char DAT_00503160[4] = "No";  // 0x503160 .data
char DAT_00503164[4] = "Yes";  // 0x503164 .data
char DAT_00503168[12] = "YESORNO.GUI";  // 0x503168 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_005031d4[4] = "BGM";  // 0x5031d4 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_0050324c[48] = "An error occurred trying to use this service";  // 0x50324c .data
char DAT_0050327c[8] = "4.zrb";  // 0x50327c .data
char DAT_00503284[8] = "3.zrb";  // 0x503284 .data
char DAT_0050328c[8] = "5.zrb";  // 0x50328c .data
char DAT_00503294[8] = "2.zrb";  // 0x503294 .data
char DAT_0050329c[8] = "1.zrb";  // 0x50329c .data
char* DAT_0050331c = (char*)"Total Annihilation 3.0";  // 0x50331c .data
char* DAT_00503320 = (char*)"Summary";  // 0x503320 .data
char DAT_00503374[4] = "\\";  // 0x503374 .data
const char DAT_0050338c[8] = "fonts";  // 0x50338c .data
char DAT_0050341c[4] = "TDF";  // 0x50341c .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_0050372c[4] = "*";  // 0x50372c .data
char DAT_00503ea0[8] = "none";  // 0x503ea0 .data
char DAT_00504314[20] = "Say Choice Array";  // 0x504314 .data
char DAT_005048f8[12] = "maxunits";  // 0x5048f8 .data
char DAT_00504904[12] = "Radar Image";  // 0x504904 .data
char DAT_00504910[12] = "Game Time";  // 0x504910 .data
char DAT_0050491c[8] = "Game ID";  // 0x50491c .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_00504924[16] = "BetweenMissions";  // 0x504924 .data
char DAT_00504934[16] = "LineOfSightType";  // 0x504934 .data
char DAT_00504944[12] = "LineOfSight";  // 0x504944 .data
char DAT_00504950[12] = "Location";  // 0x504950 .data
char DAT_0050495c[16] = "CommanderDeath";  // 0x50495c .data
char DAT_0050496c[8] = "Thumbs";  // 0x50496c .data
char DAT_00504974[12] = "Gametype";  // 0x504974 .data
char DAT_00504980[8] = "Players";  // 0x504980 .data
char DAT_00504988[8] = "Side";  // 0x504988 .data
char DAT_00504990[4] = "Map";  // 0x504990 .data
char DAT_00504994[8] = "Mission";  // 0x504994 .data
char DAT_0050499c[16] = "BUILD TIME: %s";  // 0x50499c .data
char DAT_005049ac[16] = "BUILD DATE: %s";  // 0x5049ac .data
char DAT_00504a64[8] = "camps";  // 0x504a64 .data
const char DAT_00504ab8[8] = "english";  // 0x504ab8 .data
char DAT_00504e98[8] = "Hard";  // 0x504e98 .data
char DAT_00504ea0[8] = "Medium";  // 0x504ea0 .data
char DAT_00504ea8[8] = "Easy";  // 0x504ea8 .data
signed char DAT_00505205[7] = {100, 75, 50, 25, 20, 15};  // 0x505205 .data
int DAT_00505490[6] = {115200, 57600, 38400, 19200, 14400, 9600};  // 0x505490 .data
unsigned int DAT_005054a8 = 16;  // 0x5054a8 .data
// 0x5054b0 .data
const char* DAT_005054b0[23] = {
    (const char*)"PLAYERx", (const char*)"READYx", (const char*)"LOGOx", (const char*)"SIDEx", (const char*)"PINGx", (const char*)"MEMx", (const char*)"RESx", (const char*)"ALLYx",
    (const char*)"CDx", (const char*)"TEAMICONSx", 0, 0, (const char*)"COMMNDER", (const char*)"WATCHING", (const char*)"FIXEDLOC", (const char*)"MAPPING",
    (const char*)"TECHLEVL", (const char*)"SHARING", (const char*)"CHEATING", (const char*)"UNITS", (const char*)"METAL", (const char*)"ENERGY"
};
unsigned int DAT_0050550c = 4294967295u;  // 0x50550c .data
const char* DAT_00505518[8] = {(const char*)"COMMANDER", (const char*)"MAPPING", (const char*)"LOSTYPE", (const char*)"WATCHING", (const char*)"CHEATING", (const char*)"FIXEDLOC", (const char*)"GAMEOPEN"};  // 0x505518 .data
char DAT_00505974[8] = "Multi";  // 0x505974 .data
char DAT_00505dc4[8] = "Ally";  // 0x505dc4 .data
char DAT_00505f18[8] = "GAMES";  // 0x505f18 .data
char DAT_00505f20[16] = "SAVEGAME DESCS";  // 0x505f20 .data
char DAT_00505f30[16] = "SAVEGAME NAMES";  // 0x505f30 .data
char DAT_00505f40[4] = "LST";  // 0x505f40 .data
char* DAT_005061b8[8] = {(char*)"has left the scene", (char*)"has been shown the door", (char*)"has gone to a better place", (char*)"has bowed out", (char*)"has terminated", (char*)"has been eradicated", (char*)"has been liquidated", (char*)"has been obliterated"};  // 0x5061b8 .data
int DAT_005061d8 = -1;  // 0x5061d8 .data
char s_PACKET_DATA_00506524[12] = "PACKET DATA";  // 0x506524 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_00506578[8] = "TALK";  // 0x506578 .data
float DAT_005065f8 = -0.800000011920929f;  // 0x5065f8 .data
float DAT_005065fc = 1.0f;  // 0x5065fc .data
float DAT_00506600 = 0.25f;  // 0x506600 .data
int DAT_00506788 = 1;  // 0x506788 .data
char DAT_005067bc[8] = "NOTRAK";  // 0x5067bc .data
char DAT_00506884[8] = "FXVOL";  // 0x506884 .data
char DAT_0050692c[12] = "TRACKTYPE";  // 0x50692c .data
char DAT_00506964[8] = "CDNEXT";  // 0x506964 .data
char DAT_0050696c[8] = "CDPLAY";  // 0x50696c .data
char DAT_00506974[8] = "CDSTOP";  // 0x506974 .data
char DAT_0050697c[8] = "CDPREV";  // 0x50697c .data
char DAT_00506984[12] = "TRACKMODE";  // 0x506984 .data
char DAT_00506990[8] = "RESTORE";  // 0x506990 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_00506998[8] = "UNDO";  // 0x506998 .data
char DAT_005069b8[8] = "SPEECH";  // 0x5069b8 .data
char DAT_005069c0[8] = "TEST";  // 0x5069c0 .data
char DAT_005069c8[8] = "VOLTEXT";  // 0x5069c8 .data
char DAT_005069d0[8] = "MODE";  // 0x5069d0 .data
char DAT_005069d8[20] = "sounds\\explode.wav";  // 0x5069d8 .data
int DAT_00506dbc = 1;  // 0x506dbc .data
char DAT_00507318[32] = "You're out!  Continue Watching?";  // 0x507318 .data
char DAT_005074e8[16] = "RADARPIC TEMP";  // 0x5074e8 .data
char DAT_005074f8[16] = "RADAR PICTURE";  // 0x5074f8 .data
char DAT_00507508[16] = "RADAR MAPPED";  // 0x507508 .data
char DAT_00507518[12] = "RADAR FINAL";  // 0x507518 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
int DAT_00507b6c = 1;  // 0x507b6c .data
char* DAT_00507b88[3] = {(char*)"forces have been obliterated", (char*)"vermin have been exterminated", (char*)"forces have gone to a better place"};  // 0x507b88 .data
char DAT_00508384[8] = "Allies";  // 0x508384 .data
const char DAT_00508460[16] = "SkirmishCheat";  // 0x508460 .data
const char DAT_00508470[4] = "*X";  // 0x508470 .data
const char DAT_00508474[4] = "*IX";  // 0x508474 .data
const char DAT_00508478[8] = "*III";  // 0x508478 .data
const char DAT_00508480[8] = "*VIII";  // 0x508480 .data
const char DAT_00508488[8] = "*VII";  // 0x508488 .data
const char DAT_00508490[4] = "*VI";  // 0x508490 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
const char DAT_00508494[4] = "*V";  // 0x508494 .data
const char DAT_00508498[4] = "*IV";  // 0x508498 .data
char DAT_0050849c[16] = "Skirmsetup4x";  // 0x50849c .data
char DAT_005084ac[16] = "SKIRMISH.GUI";  // 0x5084ac .data
// 0x5086dc .data
unsigned char DAT_005086dc[32] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 0, 0, 10
};
// 0x5086e0 .data (holds 36 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
unsigned char DAT_005086e0[596] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 112, 138, 80, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 9, 0, 0, 0,
    20, 0, 0, 0, 100, 138, 80, 0, 84, 138, 80, 0, 0, 0, 0, 0,
    3, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 72, 138, 80, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0,
    2, 0, 0, 0, 60, 138, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    5, 0, 0, 0, 5, 0, 0, 0, 1, 0, 0, 0, 56, 138, 80, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 3, 0, 0, 0,
    4, 0, 0, 0, 48, 138, 80, 0, 40, 138, 80, 0, 0, 0, 0, 0,
    7, 0, 0, 0, 8, 0, 0, 0, 1, 0, 0, 0, 32, 138, 80, 0,
    16, 138, 80, 0, 0, 0, 0, 0, 8, 0, 0, 0, 3, 0, 0, 0,
    3, 0, 0, 0, 0, 138, 80, 0, 236, 137, 80, 0, 0, 0, 0, 0,
    9, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 228, 137, 80, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 3, 0, 0, 0,
    1, 0, 0, 0, 220, 137, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    11, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 212, 137, 80, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 7, 0, 0, 0,
    1, 0, 0, 0, 204, 137, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    13, 0, 0, 0, 7, 0, 0, 0, 1, 0, 0, 0, 196, 137, 80, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 7, 0, 0, 0,
    1, 0, 0, 0, 188, 137, 80, 0, 180, 137, 80, 0, 0, 0, 0, 0,
    15, 0, 0, 0, 7, 0, 0, 0, 1, 0, 0, 0, 172, 137, 80, 0,
    164, 137, 80, 0, 0, 0, 0, 0, 16, 0, 0, 0, 4, 0, 0, 0,
    1, 0, 0, 0, 156, 137, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    17, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 148, 137, 80, 0,
    140, 137, 80, 0, 0, 0, 0, 0, 18, 0, 0, 0, 10, 0, 0, 0,
    0, 0, 0, 0, 132, 137, 80, 0, 124, 137, 80, 0, 0, 0, 0, 0,
    19, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 116, 137, 80, 0,
    108, 137, 80, 0, 0, 0, 0, 0, 20, 0, 0, 0, 10, 0, 0, 0,
    0, 0, 0, 0, 100, 137, 80, 0, 96, 137, 80, 0, 0, 0, 0, 0,
    21, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 88, 137, 80, 0,
    84, 137, 80, 0, 0, 0, 0, 0, 22, 0, 0, 0, 10, 0, 0, 0,
    0, 0, 0, 0, 76, 137, 80, 0, 68, 137, 80, 0, 0, 0, 0, 0,
    23, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 52, 137, 80, 0,
    24, 137, 80, 0, 0, 0, 0, 0, 83, 101, 108, 102, 32, 100, 101, 115,
    116, 114, 117, 99, 116, 32, 116, 101, 114, 109, 105, 110, 97, 116, 101, 100
};
unsigned char DAT_005086e8[4] = {0};  // 0x5086e8 .data
// 0x5086fc .data (holds 36 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
unsigned char DAT_005086fc[560] = {
    112, 138, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
    9, 0, 0, 0, 20, 0, 0, 0, 100, 138, 80, 0, 84, 138, 80, 0,
    0, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0,
    72, 138, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0,
    4, 0, 0, 0, 2, 0, 0, 0, 60, 138, 80, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 5, 0, 0, 0, 5, 0, 0, 0, 1, 0, 0, 0,
    56, 138, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0,
    3, 0, 0, 0, 4, 0, 0, 0, 48, 138, 80, 0, 40, 138, 80, 0,
    0, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0, 1, 0, 0, 0,
    32, 138, 80, 0, 16, 138, 80, 0, 0, 0, 0, 0, 8, 0, 0, 0,
    3, 0, 0, 0, 3, 0, 0, 0, 0, 138, 80, 0, 236, 137, 80, 0,
    0, 0, 0, 0, 9, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0,
    228, 137, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0,
    3, 0, 0, 0, 1, 0, 0, 0, 220, 137, 80, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 11, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    212, 137, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0,
    7, 0, 0, 0, 1, 0, 0, 0, 204, 137, 80, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 13, 0, 0, 0, 7, 0, 0, 0, 1, 0, 0, 0,
    196, 137, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0,
    7, 0, 0, 0, 1, 0, 0, 0, 188, 137, 80, 0, 180, 137, 80, 0,
    0, 0, 0, 0, 15, 0, 0, 0, 7, 0, 0, 0, 1, 0, 0, 0,
    172, 137, 80, 0, 164, 137, 80, 0, 0, 0, 0, 0, 16, 0, 0, 0,
    4, 0, 0, 0, 1, 0, 0, 0, 156, 137, 80, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 17, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0,
    148, 137, 80, 0, 140, 137, 80, 0, 0, 0, 0, 0, 18, 0, 0, 0,
    10, 0, 0, 0, 0, 0, 0, 0, 132, 137, 80, 0, 124, 137, 80, 0,
    0, 0, 0, 0, 19, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0,
    116, 137, 80, 0, 108, 137, 80, 0, 0, 0, 0, 0, 20, 0, 0, 0,
    10, 0, 0, 0, 0, 0, 0, 0, 100, 137, 80, 0, 96, 137, 80, 0,
    0, 0, 0, 0, 21, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0,
    88, 137, 80, 0, 84, 137, 80, 0, 0, 0, 0, 0, 22, 0, 0, 0,
    10, 0, 0, 0, 0, 0, 0, 0, 76, 137, 80, 0, 68, 137, 80, 0,
    0, 0, 0, 0, 23, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0,
    52, 137, 80, 0, 24, 137, 80, 0, 0, 0, 0, 0, 83, 101, 108, 102,
    32, 100, 101, 115, 116, 114, 117, 99, 116, 32, 116, 101, 114, 109, 105, 110
};
char DAT_00508a78[44] = "Error:  Sound system initialization failed.";  // 0x508a78 .data
char DAT_00508aa4[16] = "UseWindowsSound";  // 0x508aa4 .data
char DAT_00508ab4[16] = "NoDirectSound";  // 0x508ab4 .data
char DAT_00508be8[8] = "Killed";  // 0x508be8 .data
char DAT_00508bf0[36] = "%s has taken the lead with %d kills";  // 0x508bf0 .data
char s_TakeDamage_00508d68[12] = "TakeDamage";  // 0x508d68 .data
char s_HitByWeapon_00508d74[12] = "HitByWeapon";  // 0x508d74 .data
char s_paralyze_00508d80[12] = "paralyze";  // 0x508d80 .data
char s_SelectMultipleUnits_00508d8c[20] = "SelectMultipleUnits";  // 0x508d8c .data
char DAT_00508f24[12] = "Celebrated";  // 0x508f24 .data
char DAT_00508f30[12] = "Satisfied";  // 0x508f30 .data
char DAT_00508f3c[36] = "VictoryCondition_KillEnemyCommander";  // 0x508f3c .data
char DAT_00508f60[36] = "VictoryCondition_DestroyAllUnits";  // 0x508f60 .data
char DAT_00508f84[12] = "NumUnits";  // 0x508f84 .data
char DAT_00508f90[36] = "VictoryCondition_KillAllMobileUnits";  // 0x508f90 .data
char DAT_00508fb4[32] = "VictoryCondition_BuildUnitType";  // 0x508fb4 .data
char DAT_00509018[16] = "NumLeftToKill";  // 0x509018 .data
char DAT_00509028[32] = "VictoryCondition_KillUnitType";  // 0x509028 .data
char DAT_005090fc[32] = "DefeatCondition_AllUnitsKilled";  // 0x5090fc .data
char* DAT_005091c8 = (char*)"SAVEGAME";  // 0x5091c8 .data
int DAT_005091cc = 1;  // 0x5091cc .data
int DAT_005091d0 = -1;  // 0x5091d0 .data
const char DAT_005091d4[12] = "OFFSCREEN";  // 0x5091d4 .data
const char DAT_00509200[8] = "CDLISTS";  // 0x509200 .data
const char DAT_00509238[12] = "UnitLimit";  // 0x509238 .data
const char DAT_00509244[12] = "hattfont11";  // 0x509244 .data
const char DAT_00509250[12] = "hattfont12";  // 0x509250 .data
const char DAT_0050925c[12] = "commongui";  // 0x50925c .data
const char DAT_00509268[16] = "SkirmishInfo";  // 0x509268 .data
const char DAT_00509310[24] = "Invalid savegame file";  // 0x509310 .data
char DAT_005093ec[8] = "Enemies";  // 0x5093ec .data
char DAT_005093f4[4] = ",:;";  // 0x5093f4 .data
char DAT_005093f8[8] = "SENDTO";  // 0x5093f8 .data
char DAT_00509400[12] = "SENDTYPE";  // 0x509400 .data
char DAT_0050940c[12] = "LIVEPLYR";  // 0x50940c .data
char DAT_0050966c[12] = "SHOT";  // 0x50966c .data
char* DAT_00509678[4] = {(char*)"FirePrimary", (char*)"FireSecondary", (char*)"FireTertiary"};  // 0x509678 .data
char* DAT_00509688[4] = {(char*)"AimPrimary", (char*)"AimSecondary", (char*)"AimTertiary", 0 /* TODO: 0x546d6941 */};  // 0x509688 .data (the type runs past the next known address, 0x509688+0xc)
char* DAT_00509718 = (char*)"Total Annihilation Class";  // 0x509718 .data
char* DAT_0050971c = (char*)"Total Annihilation";  // 0x50971c .data
int DAT_00509720 = 1;  // 0x509720 .data
const char DAT_005097a8[8] = "cdshell";  // 0x5097a8 .data
const char DAT_005097b0[32] = "SOFTWARE\\Classes\\AudioCD\\shell";  // 0x5097b0 .data
const char DAT_005097d0[24] = "gamedata\\translate.tdf";  // 0x5097d0 .data
const char DAT_005097e8[12] = "language";  // 0x5097e8 .data
const char DAT_005097f4[8] = "Wargame";  // 0x5097f4 .data
char DAT_005098c4[12] = "HELPTEXT";  // 0x5098c4 .data
const char DAT_00509edc[20] = "Error";  // 0x509edc .data
char DAT_0050a430[12] = "ALPHA TABLE";  // 0x50a430 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
const char DAT_0050a43c[12] = "SHADE TABLE";  // 0x50a43c .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_0050a548[4] = "..";  // 0x50a548 .data
char DAT_0050a56c[16] = "Package Data";  // 0x50a56c .data
char DAT_0050a57c[4] = "\\*";  // 0x50a57c .data
char DAT_0050a5c0[16] = "HAPIFILE array";  // 0x50a5c0 .data
int DAT_0050a778 = 1;  // 0x50a778 .data
void* DAT_0050a77c = 0;  // 0x50a77c .data
int DAT_0050a780 = 1;  // 0x50a780 .data
Guid_4ca100* DAT_0050a788[4] = {0 /* TODO: 0x4fcfc8 */, 0 /* TODO: 0x4fcfd8 */, 0 /* TODO: 0x4fcfe8 */, 0 /* TODO: 0x4fcff8 */};  // 0x50a788 .data
int DAT_0050b540 = -1;  // 0x50b540 .data
int DAT_0050b544 = -1;  // 0x50b544 .data
void* DAT_0050b9e0[7] = {(void*)"SQUASHERR_OK", (void*)"SQUASHERR_BADHEADER", (void*)"SQUASHERR_BADCHECKSUM", (void*)"SQUASHERR_BADUNPACKSIZE", (void*)"SQUASHERR_BADUNPACKTYPE", (void*)"SQUASHERR_BADPACKTYPESQUASHERR_BADPARAMS"};  // 0x50b9e0 .data
char DAT_0050c8ac[8] = "Cavedog";  // 0x50c8ac .data
// 0x50c908 .data
char* DAT_0050c908[19] = {
    (char*)"-memfussy", (char*)"-memnofussy", (char*)"-memfrontalign", (char*)"-gonzo", (char*)"-memset", (char*)"-memnoset", (char*)"-fpufussy", (char*)"-fpunofussy",
    (char*)"-dprinton", (char*)"-dprintoff", (char*)"-dprintfile", (char*)DAT_0050d220, (char*)"-performancestatus", (char*)"-disableimagehlp", (char*)"-enableimagehlp", (char*)"-disableimagehlplines",
    (char*)"-enableimagehlplines", (char*)"-debughelper", (char*)"-saveresources"
};
char DAT_0050c958 = -64;  // 0x50c958 .data
char DAT_0050cd38 = -64;  // 0x50cd38 .data
char DAT_0050ced8 = -64;  // 0x50ced8 .data
char DAT_0050d220[16] = "-memorystatus";  // 0x50d220 .data
const char DAT_0050d2d0[28] = "Global Exception Handler";  // 0x50d2d0 .data
char* DAT_0050d4d0 = (char*)"Library date stamp: Jun 30 1998 16:08:53";  // 0x50d4d0 .data
char* DAT_0050d660 = (char*)"Performance status";  // 0x50d660 .data
char DAT_0050d6b4[36] = "Performance dialog failed to open";  // 0x50d6b4 .data
char* DAT_0050d72c = (char*)"Memory Status";  // 0x50d72c .data
// 0x50d980 .data (holds 8 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
unsigned char DAT_0050d980[128] = {
    0, 3, 0, 80, 12, 221, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 1, 80, 248, 220, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 11, 80, 212, 220, 80, 0, 3, 0, 0, 0, 0, 3, 40, 80,
    0, 3, 34, 80, 184, 220, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 40, 80, 160, 220, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 55, 80, 128, 220, 80, 0, 3, 0, 0, 0, 0, 2, 55, 80,
    0, 2, 55, 80, 108, 220, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 63, 80, 96, 220, 80, 0, 3
};
// 0x50da00 .data (holds 17 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
unsigned char DAT_0050da00[272] = {
    0, 3, 5, 96, 212, 220, 80, 0, 3, 0, 0, 0, 0, 3, 67, 96,
    0, 1, 16, 96, 72, 220, 80, 0, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 2, 17, 96, 48, 220, 80, 0, 2, 0, 0, 0, 0, 0, 0, 0,
    0, 2, 18, 96, 36, 220, 80, 0, 2, 0, 0, 0, 0, 0, 0, 0,
    0, 2, 19, 96, 28, 220, 80, 0, 2, 0, 0, 0, 0, 0, 0, 0,
    0, 2, 20, 96, 8, 220, 80, 0, 2, 0, 0, 0, 0, 0, 0, 0,
    1, 3, 41, 96, 240, 219, 80, 0, 3, 0, 0, 0, 15, 3, 41, 96,
    15, 3, 41, 96, 224, 219, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    1, 3, 42, 96, 200, 219, 80, 0, 3, 0, 0, 0, 15, 3, 42, 96,
    15, 3, 42, 96, 184, 219, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 67, 96, 160, 219, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 121, 96, 96, 220, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 128, 96, 132, 219, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 129, 96, 100, 219, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 193, 96, 76, 219, 80, 0, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 196, 96, 48, 219, 80, 0, 3, 0, 0, 0, 0, 0, 0, 0,
    0, 3, 197, 96, 16, 219, 80, 0, 3, 0, 0, 0, 0, 3, 196, 96
};
char DAT_005119b8[8];  // 0x5119b8 .bss
int DAT_005119e8[10];  // 0x5119e8 .bss
int DAT_00511a10[10];  // 0x511a10 .bss
int DAT_00511a38;  // 0x511a38 .bss
int DAT_00511a40;  // 0x511a40 .bss
int DAT_00511a44;  // 0x511a44 .bss
unsigned int DAT_00511a48;  // 0x511a48 .bss
int DAT_00511a4c;  // 0x511a4c .bss
unsigned int DAT_00511a50;  // 0x511a50 .bss
int DAT_00511a58[45][2];  // 0x511a58 .bss (the type runs past the next known address, 0x511a58+0x4)
unsigned char DAT_00511a60[352];  // 0x511a60 .bss
int DAT_00511bc0;  // 0x511bc0 .bss
int DAT_00511bc4;  // 0x511bc4 .bss
int DAT_00511bc8;  // 0x511bc8 .bss
int DAT_00511bcc;  // 0x511bcc .bss
char DAT_00511bd0[80];  // 0x511bd0 .bss
int DAT_00511c20;  // 0x511c20 .bss
int DAT_00511c24;  // 0x511c24 .bss
int DAT_00511c28;  // 0x511c28 .bss
int DAT_00511c2c;  // 0x511c2c .bss
unsigned int DAT_00511c30;  // 0x511c30 .bss
int DAT_00511c34;  // 0x511c34 .bss
unsigned int DAT_00511c38;  // 0x511c38 .bss
unsigned int DAT_00511c3c;  // 0x511c3c .bss
int DAT_00511c40;  // 0x511c40 .bss
int DAT_00511c44;  // 0x511c44 .bss
int DAT_00511c48;  // 0x511c48 .bss
unsigned int DAT_00511c4c;  // 0x511c4c .bss
int DAT_00511c50;  // 0x511c50 .bss
int DAT_00511c58[45][2];  // 0x511c58 .bss (the type runs past the next known address, 0x511c58+0x8)
unsigned char DAT_00511c60[352];  // 0x511c60 .bss
unsigned int DAT_00511dc0;  // 0x511dc0 .bss
unsigned int DAT_00511dc4;  // 0x511dc4 .bss
int DAT_00511dc8;  // 0x511dc8 .bss
int DAT_00511dcc;  // 0x511dcc .bss
int DAT_00511dd0;  // 0x511dd0 .bss
int DAT_00511dd4;  // 0x511dd4 .bss
unsigned int DAT_00511dd8;  // 0x511dd8 .bss
unsigned int DAT_00511ddc;  // 0x511ddc .bss
int DAT_00511de0;  // 0x511de0 .bss
int DAT_00511de4;  // 0x511de4 .bss
Game* g_game;  // 0x511de8 .bss
int DAT_00511dec;  // 0x511dec .bss
unsigned char DAT_00511f80[16];  // 0x511f80 .bss
int DAT_00511f90;  // 0x511f90 .bss
int DAT_00511f94;  // 0x511f94 .bss
int DAT_00511f98;  // 0x511f98 .bss
int DAT_00511f9c;  // 0x511f9c .bss
int DAT_00511fa0;  // 0x511fa0 .bss
int DAT_00511fa4;  // 0x511fa4 .bss
int DAT_00511fa8;  // 0x511fa8 .bss
int DAT_00511fac;  // 0x511fac .bss
int DAT_00511fb0;  // 0x511fb0 .bss
unsigned char DAT_00511fb4[4];  // 0x511fb4 .bss
char DAT_00511fb8[256];  // 0x511fb8 .bss
unsigned char DAT_005120bc[460];  // 0x5120bc .bss
int DAT_00512288;  // 0x512288 .bss
int DAT_0051228c;  // 0x51228c .bss
int DAT_00512290;  // 0x512290 .bss
int DAT_00512294;  // 0x512294 .bss
int DAT_0051229c;  // 0x51229c .bss
unsigned char DAT_005122c0[4];  // 0x5122c0 .bss
Class_00437820* DAT_005122c4;  // 0x5122c4 .bss
Class_00437820* DAT_005122c8;  // 0x5122c8 .bss
int DAT_005122d8;  // 0x5122d8 .bss
int DAT_005122dc;  // 0x5122dc .bss
int DAT_005122e0;  // 0x5122e0 .bss
int DAT_005122e8;  // 0x5122e8 .bss
char DAT_005122f0[32];  // 0x5122f0 .bss
int DAT_00512310;  // 0x512310 .bss
int DAT_00512314;  // 0x512314 .bss
int DAT_00512318;  // 0x512318 .bss
int DAT_0051231c;  // 0x51231c .bss
short DAT_00512322;  // 0x512322 .bss
int DAT_00512324;  // 0x512324 .bss
int DAT_0051232c;  // 0x51232c .bss
int DAT_00512330;  // 0x512330 .bss
short DAT_00512336;  // 0x512336 .bss
int DAT_00512338;  // 0x512338 .bss
unsigned char DAT_00512340[24];  // 0x512340 .bss
unsigned char DAT_00512358[1032];  // 0x512358 .bss
char DAT_00512370[1000];  // 0x512370 .bss
int DAT_00512760;  // 0x512760 .bss
int DAT_00512768;  // 0x512768 .bss
int DAT_0051276c;  // 0x51276c .bss
int DAT_00512774;  // 0x512774 .bss
unsigned int DAT_00512788;  // 0x512788 .bss
int DAT_00512978;  // 0x512978 .bss
int DAT_0051297c;  // 0x51297c .bss
char* DAT_00512980;  // 0x512980 .bss
int DAT_00512984;  // 0x512984 .bss
Entry_00443100* DAT_00512988;  // 0x512988 .bss
char* DAT_0051298c;  // 0x51298c .bss
char* DAT_00512990;  // 0x512990 .bss
int DAT_00512994;  // 0x512994 .bss
int DAT_005129a4;  // 0x5129a4 .bss
unsigned int DAT_005129a8;  // 0x5129a8 .bss
char* DAT_005129b0;  // 0x5129b0 .bss
Record_005129b4* DAT_005129b4;  // 0x5129b4 .bss
int DAT_005129c0;  // 0x5129c0 .bss
int* DAT_005129c4;  // 0x5129c4 .bss
int DAT_005129c8;  // 0x5129c8 .bss
unsigned char DAT_005129d0[40];  // 0x5129d0 .bss
int DAT_005129f1;  // 0x5129f1 .bss
unsigned char DAT_005129f8[40];  // 0x5129f8 .bss
void (__stdcall* DAT_00512a20[2])(void*);  // 0x512a20 .bss
int (__stdcall* DAT_00512a28)(int);  // 0x512a28 .bss
int (__stdcall* DAT_00512a2c)(int);  // 0x512a2c .bss
int (__stdcall* DAT_00512a34)(int);  // 0x512a34 .bss
int (__stdcall* DAT_00512a38)(int);  // 0x512a38 .bss
int (__stdcall* DAT_00512a3c)(int);  // 0x512a3c .bss
int (__stdcall* DAT_00512a40)(int);  // 0x512a40 .bss
int (__stdcall* DAT_00512a44)(int);  // 0x512a44 .bss
int (__stdcall* DAT_00512a48)(int);  // 0x512a48 .bss
int (__stdcall* DAT_00512a4c)(int);  // 0x512a4c .bss
int (__stdcall* DAT_00512a50)(int);  // 0x512a50 .bss
int (__stdcall* DAT_00512a54)(int);  // 0x512a54 .bss
int (__stdcall* DAT_00512a58)(int);  // 0x512a58 .bss
int (__stdcall* DAT_00512a5c)(int);  // 0x512a5c .bss
int (__stdcall* DAT_00512a60)(int);  // 0x512a60 .bss
int (__stdcall* DAT_00512a64)(int);  // 0x512a64 .bss
int (__stdcall* DAT_00512a68)(int);  // 0x512a68 .bss
int (__stdcall* DAT_00512a6c)(int);  // 0x512a6c .bss
int (__stdcall* DAT_00512a70)(int);  // 0x512a70 .bss
int (__stdcall* DAT_00512a74)(int);  // 0x512a74 .bss
int (__stdcall* DAT_00512a78)(int);  // 0x512a78 .bss
int (__stdcall* DAT_00512a7c)(int);  // 0x512a7c .bss
int (__stdcall* DAT_00512a80)(int);  // 0x512a80 .bss
int (__stdcall* DAT_00512a84)(int);  // 0x512a84 .bss
int (__stdcall* DAT_00512a88)(int);  // 0x512a88 .bss
int (__stdcall* DAT_00512a8c)(int);  // 0x512a8c .bss
int (__stdcall* DAT_00512a90)(int);  // 0x512a90 .bss
int (__stdcall* DAT_00512a94)(int);  // 0x512a94 .bss
int (__stdcall* DAT_00512a98)(int);  // 0x512a98 .bss
int (__stdcall* DAT_00512a9c)(int);  // 0x512a9c .bss
int (__stdcall* DAT_00512aa0)(int);  // 0x512aa0 .bss
int (__stdcall* DAT_00512aa4)(int);  // 0x512aa4 .bss
int (__stdcall* DAT_00512aa8)(int);  // 0x512aa8 .bss
int (__stdcall* DAT_00512aac)(int);  // 0x512aac .bss
int (__stdcall* DAT_00512ab0)(int);  // 0x512ab0 .bss
int (__stdcall* DAT_00512ab4)(int);  // 0x512ab4 .bss
int (__stdcall* DAT_00512ab8)(int);  // 0x512ab8 .bss
int (__stdcall* DAT_00512abc)(int);  // 0x512abc .bss
int (__stdcall* DAT_00512ac0)(int);  // 0x512ac0 .bss
int (__stdcall* DAT_00512ac4)(int);  // 0x512ac4 .bss
int (__stdcall* DAT_00512ac8)(int);  // 0x512ac8 .bss
int (__stdcall* DAT_00512ad0)(int);  // 0x512ad0 .bss
unsigned short DAT_00512ad8[2][2];  // 0x512ad8 .bss
int DAT_00512adc;  // 0x512adc .bss
int DAT_00512ae0;  // 0x512ae0 .bss
int DAT_00512ae4;  // 0x512ae4 .bss
int DAT_00512aec;  // 0x512aec .bss
int DAT_00512af0;  // 0x512af0 .bss
int DAT_00512af4;  // 0x512af4 .bss
int DAT_00512af8;  // 0x512af8 .bss
int DAT_00512afc;  // 0x512afc .bss
int DAT_00512b00;  // 0x512b00 .bss
int DAT_00512b04;  // 0x512b04 .bss
int DAT_00512b08;  // 0x512b08 .bss
int DAT_00512b0c;  // 0x512b0c .bss
int DAT_00512b10;  // 0x512b10 .bss
int DAT_00512b14;  // 0x512b14 .bss
int DAT_00512b18;  // 0x512b18 .bss
int DAT_00512b1c;  // 0x512b1c .bss
int DAT_00512b20;  // 0x512b20 .bss
int DAT_00512b24;  // 0x512b24 .bss
int DAT_00512b28;  // 0x512b28 .bss
int DAT_00512b2c;  // 0x512b2c .bss
int DAT_00512b30;  // 0x512b30 .bss
int DAT_00512b34;  // 0x512b34 .bss
int DAT_00512b38;  // 0x512b38 .bss
int DAT_00512b3c;  // 0x512b3c .bss
int DAT_00512b40;  // 0x512b40 .bss
int DAT_00512b44;  // 0x512b44 .bss
int DAT_00512b48;  // 0x512b48 .bss
int DAT_00512b4c;  // 0x512b4c .bss
int DAT_00512b50;  // 0x512b50 .bss
int DAT_00512b54;  // 0x512b54 .bss
int DAT_00512b58;  // 0x512b58 .bss
int DAT_00512b5c;  // 0x512b5c .bss
int DAT_00512b60;  // 0x512b60 .bss
int DAT_00512b64;  // 0x512b64 .bss
int DAT_00512b68;  // 0x512b68 .bss
int DAT_00512b6c;  // 0x512b6c .bss
int DAT_00512b70;  // 0x512b70 .bss
int DAT_00512b74;  // 0x512b74 .bss
int DAT_00512b78;  // 0x512b78 .bss
int DAT_00512b7c;  // 0x512b7c .bss
int DAT_00512b80;  // 0x512b80 .bss
int DAT_00512b88;  // 0x512b88 .bss
int DAT_00512b90[11];  // 0x512b90 .bss
unsigned char DAT_00512bc0[8];  // 0x512bc0 .bss
int DAT_00512bc8;  // 0x512bc8 .bss
int DAT_00512bcc;  // 0x512bcc .bss
int DAT_00512bd4;  // 0x512bd4 .bss
int DAT_00512bd8;  // 0x512bd8 .bss
int DAT_00512bdc;  // 0x512bdc .bss
int DAT_00512be0;  // 0x512be0 .bss
int DAT_00512be4;  // 0x512be4 .bss
int DAT_00512be8;  // 0x512be8 .bss
int DAT_00512bec;  // 0x512bec .bss
int DAT_00512bf0;  // 0x512bf0 .bss
int DAT_00512bf4;  // 0x512bf4 .bss
int DAT_00512bf8;  // 0x512bf8 .bss
int DAT_00512bfc;  // 0x512bfc .bss
int DAT_00512c00;  // 0x512c00 .bss
int DAT_00512c04;  // 0x512c04 .bss
int DAT_00512c08;  // 0x512c08 .bss
int DAT_00512c0c;  // 0x512c0c .bss
int DAT_00512c10;  // 0x512c10 .bss
int DAT_00512c14;  // 0x512c14 .bss
int DAT_00512c18;  // 0x512c18 .bss
int DAT_00512c1c;  // 0x512c1c .bss
int DAT_00512c20;  // 0x512c20 .bss
int DAT_00512c24;  // 0x512c24 .bss
int DAT_00512c28;  // 0x512c28 .bss
int DAT_00512c2c;  // 0x512c2c .bss
int DAT_00512c30;  // 0x512c30 .bss
int DAT_00512c38;  // 0x512c38 .bss
int DAT_00512c3c;  // 0x512c3c .bss
int DAT_00512c40;  // 0x512c40 .bss
int DAT_00512c44;  // 0x512c44 .bss
int DAT_00512c48;  // 0x512c48 .bss
int DAT_00512c4c;  // 0x512c4c .bss
int DAT_00512c50;  // 0x512c50 .bss
int DAT_00512c54;  // 0x512c54 .bss
int DAT_00512c58;  // 0x512c58 .bss
int DAT_00512c5c;  // 0x512c5c .bss
int DAT_00512c60;  // 0x512c60 .bss
int DAT_00512c64;  // 0x512c64 .bss
int DAT_00512c68;  // 0x512c68 .bss
int DAT_00512c70;  // 0x512c70 .bss
int DAT_00512c78;  // 0x512c78 .bss
unsigned int DAT_00512c7c;  // 0x512c7c .bss
int DAT_00512c80;  // 0x512c80 .bss
int DAT_00512c84;  // 0x512c84 .bss
int DAT_00512c8c;  // 0x512c8c .bss
int DAT_00512c94;  // 0x512c94 .bss
char DAT_00512c98[16];  // 0x512c98 .bss
char DAT_00512ca8[64];  // 0x512ca8 .bss
char DAT_00512ce8;  // 0x512ce8 .bss
char DAT_00512d28;  // 0x512d28 .bss
int DAT_00512d68;  // 0x512d68 .bss
int DAT_00512d6c;  // 0x512d6c .bss
int DAT_00512d70;  // 0x512d70 .bss
int DAT_00512d74;  // 0x512d74 .bss
int DAT_00512d78;  // 0x512d78 .bss
int DAT_00512d7c;  // 0x512d7c .bss
int DAT_00512d80;  // 0x512d80 .bss
int DAT_00512d84;  // 0x512d84 .bss
int DAT_00512d88;  // 0x512d88 .bss
int DAT_00512d8c;  // 0x512d8c .bss
int DAT_00512ee8;  // 0x512ee8 .bss
void* DAT_00512eec;  // 0x512eec .bss
int DAT_00512ef0;  // 0x512ef0 .bss
unsigned char DAT_00512ef8[24];  // 0x512ef8 .bss
int DAT_00512f10;  // 0x512f10 .bss
int DAT_00512f14;  // 0x512f14 .bss
unsigned char DAT_00512f18[85];  // 0x512f18 .bss
int DAT_00512f2c;  // 0x512f2c .bss
int DAT_00512f38;  // 0x512f38 .bss (the type runs past the next known address, 0x512f38+0x2)
int DAT_00512f3a;  // 0x512f3a .bss
int DAT_00512f3e;  // 0x512f3e .bss
int DAT_00512f42;  // 0x512f42 .bss
char DAT_00512f48;  // 0x512f48 .bss
char DAT_00512f49;  // 0x512f49 .bss
char DAT_00512f4a;  // 0x512f4a .bss
unsigned int DAT_00512f4b;  // 0x512f4b .bss (the type runs past the next known address, 0x512f4b+0x2)
int DAT_00512f4d;  // 0x512f4d .bss
int DAT_00512f51;  // 0x512f51 .bss
int DAT_00512f55;  // 0x512f55 .bss
int DAT_00512f59;  // 0x512f59 .bss
int DAT_00512f6d;  // 0x512f6d .bss
int DAT_00512fd9;  // 0x512fd9 .bss
int DAT_00512fe0;  // 0x512fe0 .bss
int DAT_00512fe4;  // 0x512fe4 .bss
int DAT_00512fec;  // 0x512fec .bss
int DAT_00512ff0;  // 0x512ff0 .bss
int DAT_00512ff8;  // 0x512ff8 .bss
unsigned char DAT_00513000[46416];  // 0x513000 .bss
unsigned char DAT_00513008[4];  // 0x513008 .bss
int* DAT_0051e2f4;  // 0x51e2f4 .bss
int DAT_0051e2f8;  // 0x51e2f8 .bss
unsigned char DAT_0051e300[4];  // 0x51e300 .bss
Buffer_461020* DAT_0051e314;  // 0x51e314 .bss
void* DAT_0051e318;  // 0x51e318 .bss
void* DAT_0051e31c;  // 0x51e31c .bss
int DAT_0051e528;  // 0x51e528 .bss
int DAT_0051e52c;  // 0x51e52c .bss
int DAT_0051e53c;  // 0x51e53c .bss
int DAT_0051e540;  // 0x51e540 .bss
int DAT_0051e544;  // 0x51e544 .bss
int (__stdcall* DAT_0051e54c)(int*, int);  // 0x51e54c .bss
int (__stdcall* DAT_0051e554)(char*);  // 0x51e554 .bss
void (__cdecl* DAT_0051e558)(void);  // 0x51e558 .bss
unsigned char DAT_0051e560[20];  // 0x51e560 .bss
void (__stdcall* DAT_0051e578)(void (__stdcall*)(int), int (__stdcall*)(char*, int));  // 0x51e578 .bss
int (__stdcall* DAT_0051e588)(int);  // 0x51e588 .bss
int DAT_0051e590;  // 0x51e590 .bss
int DAT_0051e594;  // 0x51e594 .bss
char DAT_0051e5a0[104];  // 0x51e5a0 .bss
char DAT_0051e608;  // 0x51e608 .bss
unsigned char DAT_0051e610[36];  // 0x51e610 .bss
unsigned char DAT_0051e634;  // 0x51e634 .bss
char* DAT_0051e63c;  // 0x51e63c .bss
int DAT_0051e64c;  // 0x51e64c .bss
int DAT_0051e650;  // 0x51e650 .bss
int DAT_0051e654;  // 0x51e654 .bss
int* DAT_0051e65c;  // 0x51e65c .bss
int DAT_0051e668;  // 0x51e668 .bss
int DAT_0051e66c;  // 0x51e66c .bss
int DAT_0051e670;  // 0x51e670 .bss
short DAT_0051e674;  // 0x51e674 .bss
int DAT_0051e678;  // 0x51e678 .bss
unsigned int DAT_0051e67c;  // 0x51e67c .bss
unsigned int DAT_0051e680;  // 0x51e680 .bss
int DAT_0051e684;  // 0x51e684 .bss
int DAT_0051e688;  // 0x51e688 .bss
List_0047f8c0* DAT_0051e68c;  // 0x51e68c .bss
int DAT_0051e690;  // 0x51e690 .bss
int DAT_0051e694;  // 0x51e694 .bss
int DAT_0051e698;  // 0x51e698 .bss
int DAT_0051e69c;  // 0x51e69c .bss
unsigned char DAT_0051e6b0[12];  // 0x51e6b0 .bss
int DAT_0051e6c0;  // 0x51e6c0 .bss
unsigned int DAT_0051e6c4;  // 0x51e6c4 .bss
int DAT_0051e6c8;  // 0x51e6c8 .bss
int DAT_0051e6cc;  // 0x51e6cc .bss
int DAT_0051e6d0[10];  // 0x51e6d0 .bss
char DAT_0051e6f8[24];  // 0x51e6f8 .bss
int DAT_0051e710[30];  // 0x51e710 .bss
char DAT_0051e788[136];  // 0x51e788 .bss
unsigned char DAT_0051e810[10];  // 0x51e810 .bss (the type runs past the next known address, 0x51e810+0x4)
int DAT_0051e814;  // 0x51e814 .bss
short DAT_0051e818;  // 0x51e818 .bss
unsigned char DAT_0051e820;  // 0x51e820 .bss
unsigned char DAT_0051e821;  // 0x51e821 .bss
unsigned char DAT_0051e822;  // 0x51e822 .bss
unsigned char DAT_0051e823;  // 0x51e823 .bss
unsigned char DAT_0051e824;  // 0x51e824 .bss
unsigned char DAT_0051e825;  // 0x51e825 .bss
int DAT_0051e848;  // 0x51e848 .bss
int DAT_0051e84c;  // 0x51e84c .bss
int DAT_0051e850;  // 0x51e850 .bss
int DAT_0051e854;  // 0x51e854 .bss
int DAT_0051e858;  // 0x51e858 .bss
unsigned char DAT_0051f2c8[10];  // 0x51f2c8 .bss (the type runs past the next known address, 0x51f2c8+0x4)
int DAT_0051f2cc;  // 0x51f2cc .bss
short DAT_0051f2d0;  // 0x51f2d0 .bss
unsigned int DAT_0051f2d8;  // 0x51f2d8 .bss
int DAT_0051f2dc;  // 0x51f2dc .bss
char* DAT_0051f2e0;  // 0x51f2e0 .bss
char* DAT_0051f2ec;  // 0x51f2ec .bss
int DAT_0051f2f0;  // 0x51f2f0 .bss
int DAT_0051f2f4;  // 0x51f2f4 .bss
unsigned int DAT_0051f2f8;  // 0x51f2f8 .bss
int DAT_0051f2fc;  // 0x51f2fc .bss
int DAT_0051f300;  // 0x51f300 .bss
int DAT_0051f304;  // 0x51f304 .bss
int DAT_0051f308;  // 0x51f308 .bss
unsigned char DAT_0051f310[12];  // 0x51f310 .bss
unsigned char DAT_0051f31c;  // 0x51f31c .bss
unsigned char DAT_0051f320[2088];  // 0x51f320 .bss
int DAT_0051fb48;  // 0x51fb48 .bss
int DAT_0051fb90;  // 0x51fb90 .bss
unsigned long DAT_0051fb94;  // 0x51fb94 .bss
int* DAT_0051fba0;  // 0x51fba0 .bss
Class_0051fba4* DAT_0051fba4;  // 0x51fba4 .bss
int DAT_0051fba8;  // 0x51fba8 .bss
int DAT_0051fbac;  // 0x51fbac .bss
int DAT_0051fbb0;  // 0x51fbb0 .bss
int DAT_0051fbb4;  // 0x51fbb4 .bss
int DAT_0051fbb8;  // 0x51fbb8 .bss
unsigned char DAT_0051fbc0[16];  // 0x51fbc0 .bss
unsigned char DAT_0051fbd8[160];  // 0x51fbd8 .bss
void (__cdecl* DAT_0051fc78)(int);  // 0x51fc78 .bss
int DAT_0051fc7c;  // 0x51fc7c .bss
int DAT_0051fc80;  // 0x51fc80 .bss
unsigned int DAT_0051fc84;  // 0x51fc84 .bss
unsigned int DAT_0051fc88;  // 0x51fc88 .bss
int DAT_0051fc90;  // 0x51fc90 .bss
int DAT_0051fc94;  // 0x51fc94 .bss
unsigned char DAT_0051fcaf[1];  // 0x51fcaf .bss
unsigned char DAT_0051fcb0[256];  // 0x51fcb0 .bss
int DAT_0051fdb0;  // 0x51fdb0 .bss
Class_004c5840* DAT_0051fdb8;  // 0x51fdb8 .bss
char DAT_0051fdc0[256];  // 0x51fdc0 .bss (the type runs past the next known address, 0x51fdc0+0x40)
int DAT_0051fe00;  // 0x51fe00 .bss (the type runs past the next known address, 0x51fe00+0x3)
unsigned char DAT_0051fe08[56];  // 0x51fe08 .bss
int DAT_0051fe40;  // 0x51fe40 .bss
int DAT_0051fe48[20];  // 0x51fe48 .bss
int DAT_0051fe98;  // 0x51fe98 .bss
int DAT_0051fea0[20];  // 0x51fea0 .bss
int DAT_0051fef0;  // 0x51fef0 .bss
int DAT_0051fef4;  // 0x51fef4 .bss
Chunk* DAT_0051fef8;  // 0x51fef8 .bss
int DAT_0051fefc;  // 0x51fefc .bss
int DAT_0051ff00;  // 0x51ff00 .bss
int DAT_0051ff04;  // 0x51ff04 .bss
int DAT_0051ff08;  // 0x51ff08 .bss
int DAT_0051ff0c;  // 0x51ff0c .bss
int DAT_0051ff10;  // 0x51ff10 .bss
void* DAT_0051ff18;  // 0x51ff18 .bss
int DAT_0051ff20[10];  // 0x51ff20 .bss
int DAT_0051ff48;  // 0x51ff48 .bss
int DAT_0051ff58;  // 0x51ff58 .bss
char DAT_0051ff60[112];  // 0x51ff60 .bss
char DAT_0051ffd0[176];  // 0x51ffd0 .bss
char DAT_00520fe8[12634];  // 0x520fe8 .bss
Struct_00526ff0* DAT_00526ff0;  // 0x526ff0 .bss
int DAT_00526ff8;  // 0x526ff8 .bss
int DAT_00526ffc;  // 0x526ffc .bss (the type runs past the next known address, 0x526ffc+0x3)
char DAT_005289b4;  // 0x5289b4 .bss
char DAT_005289b8;  // 0x5289b8 .bss
void (__stdcall* DAT_005289bc)(void);  // 0x5289bc .bss
int DAT_005289c0;  // 0x5289c0 .bss
int DAT_005289c4;  // 0x5289c4 .bss
unsigned int DAT_005289d0;  // 0x5289d0 .bss
unsigned int DAT_005289d4;  // 0x5289d4 .bss
unsigned int DAT_005289d8;  // 0x5289d8 .bss
unsigned int DAT_005289dc;  // 0x5289dc .bss
void* DAT_005289e0;  // 0x5289e0 .bss
unsigned int DAT_005289f0;  // 0x5289f0 .bss
unsigned int DAT_005289f8;  // 0x5289f8 .bss
unsigned int DAT_005289fc;  // 0x5289fc .bss
unsigned int DAT_00528a00;  // 0x528a00 .bss
unsigned int DAT_00528a04;  // 0x528a04 .bss
unsigned int DAT_00528a08;  // 0x528a08 .bss
unsigned int DAT_00528a1c;  // 0x528a1c .bss
Class_004db000* DAT_00528a40;  // 0x528a40 .bss
void* DAT_00528a44;  // 0x528a44 .bss
unsigned char DAT_00528a48[4];  // 0x528a48 .bss
int DAT_00528a4c;  // 0x528a4c .bss
Node_004dde70* DAT_00528a50;  // 0x528a50 .bss
unsigned char DAT_00528a78[44];  // 0x528a78 .bss
void* DAT_00528aa4;  // 0x528aa4 .bss
char DAT_00528aa8;  // 0x528aa8 .bss
char DAT_00528aac;  // 0x528aac .bss
void* DAT_00528ab0;  // 0x528ab0 .bss
char DAT_00528ad8;  // 0x528ad8 .bss
char DAT_00528adc;  // 0x528adc .bss
void* DAT_00528ae0;  // 0x528ae0 .bss
char DAT_00528ae4;  // 0x528ae4 .bss
char DAT_00528ae8[488];  // 0x528ae8 .bss
char DAT_00528ed0[488];  // 0x528ed0 .bss
int DAT_00529508;  // 0x529508 .bss
int DAT_00529528;  // 0x529528 .bss
void* DAT_00529530;  // 0x529530 .bss
int DAT_005295b8;  // 0x5295b8 .bss
void* DAT_005295bc;  // 0x5295bc .bss
int DAT_005295c0;  // 0x5295c0 .bss
int DAT_005295c8;  // 0x5295c8 .bss
char DAT_005295cc;  // 0x5295cc .bss
int DAT_005295d0;  // 0x5295d0 .bss
int DAT_005295d4;  // 0x5295d4 .bss
char DAT_005295d8[2000];  // 0x5295d8 .bss
unsigned char DAT_00529dc8;  // 0x529dc8 .bss
int DAT_00529dcc;  // 0x529dcc .bss
int DAT_00529dd0;  // 0x529dd0 .bss
unsigned char DAT_00529dd4;  // 0x529dd4 .bss
unsigned char DAT_00529dd8;  // 0x529dd8 .bss
unsigned char DAT_00529ddc;  // 0x529ddc .bss
char DAT_00529e20[56];  // 0x529e20 .bss
void* DAT_00529e58;  // 0x529e58 .bss
unsigned char DAT_00529e64;  // 0x529e64 .bss
unsigned char DAT_00529e6c;  // 0x529e6c .bss
unsigned char DAT_00529e70;  // 0x529e70 .bss
Class_004e17c0* DAT_00529e7c;  // 0x529e7c .bss
char* DAT_00529e80;  // 0x529e80 .bss
void* DAT_00529e98;  // 0x529e98 .bss
int DAT_00529ea0;  // 0x529ea0 .bss
char DAT_0052a4e4;  // 0x52a4e4 .bss
long DAT_0052a4e8;  // 0x52a4e8 .bss
long DAT_0052a4ec;  // 0x52a4ec .bss
void* DAT_0052a4f0;  // 0x52a4f0 .bss
int DAT_0052a4f4;  // 0x52a4f4 .bss
void* DAT_0052a4f8;  // 0x52a4f8 .bss
long DAT_0052a4fc;  // 0x52a4fc .bss
