// Generated by tools/globals.py from data/globals.csv: do not edit.
//
// Definitions of the most-referenced globals in link/globals.h, with the
// initial values the original exe holds. Pointers to strings become string
// literals, pointers to other globals in this file become their address,
// and pointers to data no row names (DAT_0050a788's GUIDs) point at a byte
// array of that data defined here; any other pointer is marked TODO. Not
// part of any build yet; see docs/linking.md.

#include "globals.h"

unsigned char DAT_004fca10[8] = {0, 40, 60, 80, 100, 80, 60, 40};  // 0x4fca10 .rdata
unsigned char DAT_004fcc68[8] = {4, 14, 10};  // 0x4fcc68 .rdata
char DAT_004fd050[200] = "Warning! The currently installed version of Microsoft%sDirectX may not function properly with Total Annihilation.%sPlease install the version of DirectX included on the%sTotal Annihilation setup CD.";  // 0x4fd050 .rdata
double DAT_004fd2b0 = 6.28318530717958;  // 0x4fd2b0 .rdata
double DAT_004fd2b8 = 0.125;  // 0x4fd2b8 .rdata
const float DAT_004fd4c0 = 0.0f;  // 0x4fd4c0 .rdata
const float DAT_004fd4cc = 5.0f;  // 0x4fd4cc .rdata
signed char DAT_004fd670[8] = {0, -1, -1, -1, 0, 1, 1, 1};  // 0x4fd670 .rdata
signed char DAT_004fd678[8] = {-1, -1, 0, 1, 1, 1, 0, -1};  // 0x4fd678 .rdata
float DAT_004fd750 = 0.003921568859368563f;  // 0x4fd750 .rdata
unsigned char DAT_004fdaf0[16] = {0};  // 0x4fdaf0 .rdata
double DAT_004fdbe8 = -0.06875;  // 0x4fdbe8 .rdata
char g_hapiCopyright[40] = "Copyright 0000 Cavedog Entertainment";  // 0x4fdbf0 .rdata
int g_aiCommandsEnabled = 1;  // 0x501774 .data
// 0x501d18 .data
unsigned char DAT_00501d18[32] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 111, 110, 109, 108, 107, 106,
    88, 87, 86, 85, 84, 83, 82, 81, 80, 255, 255, 255, 255, 255, 255, 255
};
char DAT_00502288[8] = "Mapping";  // 0x502288 .data
char DAT_005024fc[16] = "%s\\screenshots";  // 0x5024fc .data
const char DAT_00502820[8] = "guis";  // 0x502820 .data
char g_cameraXPosition[12] = "X Position";  // 0x502878 .data
char g_cameraZPosition[12] = "Z Position";  // 0x502884 .data
char g_cameraAccount[8] = "Camera";  // 0x502890 .data
int g_commandLineUnusedFlagL = 1;  // 0x502898 .data
int DAT_0050289c = 1;  // 0x50289c .data
char DAT_005028f8[12] = "Campaign";  // 0x5028f8 .data
char DAT_00502910[4] = ".";  // 0x502910 .data
char DAT_00502a20[4] = "&G";  // 0x502a20 .data
char DAT_00502a78[12] = "Difficulty";  // 0x502a78 .data
char DAT_00502b38[8] = "Options";  // 0x502b38 .data
// 0x502bf8 .data
unsigned char DAT_00502bf8[64] = {
    0, 0, 1, 0, 2, 0, 3, 0, 2, 0, 1, 0, 6, 0, 5, 0,
    0, 0, 3, 0, 4, 0, 7, 0, 1, 0, 0, 0, 7, 0, 6, 0,
    3, 0, 2, 0, 5, 0, 4, 0, 4, 0, 5, 0, 6, 0, 7, 0,
    101, 120, 112, 108, 111, 100, 101, 112, 105, 101, 99, 101
};
const char DAT_00502e30[8] = "anims";  // 0x502e30 .data
char DAT_00502e78[12] = "Description";  // 0x502e78 .data
char DAT_00502f9c[104] = "Code segment checksum error found when switching FE states.\nState change called from [line %d, file %s]";  // 0x502f9c .data
char DAT_00503004[32] = "c:\\cavedog\\wargame\\frontend.cpp";  // 0x503004 .data
char DAT_0050310c[4] = "tdf";  // 0x50310c .data
char DAT_00503120[8] = "CHOICE2";  // 0x503120 .data
char DAT_00503128[8] = "CHOICE1";  // 0x503128 .data
char DAT_00503130[12] = "SmallButton";  // 0x503130 .data
char DAT_0050313c[8] = "TITLE";  // 0x50313c .data
char DAT_00503160[4] = "No";  // 0x503160 .data
char DAT_00503164[4] = "Yes";  // 0x503164 .data
char DAT_00503168[12] = "YESORNO.GUI";  // 0x503168 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_005031d4[4] = "BGM";  // 0x5031d4 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_0050324c[48] = "An error occurred trying to use this service";  // 0x50324c .data
char DAT_0050327c[8] = "4.zrb";  // 0x50327c .data
char DAT_00503284[8] = "3.zrb";  // 0x503284 .data
char DAT_0050328c[8] = "5.zrb";  // 0x50328c .data
char DAT_00503294[8] = "2.zrb";  // 0x503294 .data
char DAT_0050329c[8] = "1.zrb";  // 0x50329c .data
char* DAT_0050331c = (char*)"Total Annihilation 3.0";  // 0x50331c .data
char* DAT_00503320 = (char*)"Summary";  // 0x503320 .data
char DAT_00503374[4] = "\\";  // 0x503374 .data
const char DAT_0050338c[8] = "fonts";  // 0x50338c .data
char DAT_0050341c[4] = "TDF";  // 0x50341c .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_0050372c[4] = "*";  // 0x50372c .data
char DAT_00503ea0[8] = "none";  // 0x503ea0 .data
char DAT_00504314[20] = "Say Choice Array";  // 0x504314 .data
char DAT_005048f8[12] = "maxunits";  // 0x5048f8 .data
char DAT_00504904[12] = "Radar Image";  // 0x504904 .data
char DAT_00504910[12] = "Game Time";  // 0x504910 .data
char DAT_0050491c[8] = "Game ID";  // 0x50491c .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_00504924[16] = "BetweenMissions";  // 0x504924 .data
char DAT_00504934[16] = "LineOfSightType";  // 0x504934 .data
char DAT_00504944[12] = "LineOfSight";  // 0x504944 .data
char DAT_00504950[12] = "Location";  // 0x504950 .data
char DAT_0050495c[16] = "CommanderDeath";  // 0x50495c .data
char DAT_0050496c[8] = "Thumbs";  // 0x50496c .data
char DAT_00504974[12] = "Gametype";  // 0x504974 .data
char DAT_00504980[8] = "Players";  // 0x504980 .data
char DAT_00504988[8] = "Side";  // 0x504988 .data
char DAT_00504990[4] = "Map";  // 0x504990 .data
char DAT_00504994[8] = "Mission";  // 0x504994 .data
char DAT_0050499c[16] = "BUILD TIME: %s";  // 0x50499c .data
char DAT_005049ac[16] = "BUILD DATE: %s";  // 0x5049ac .data
char DAT_00504a64[8] = "camps";  // 0x504a64 .data
const char DAT_00504ab8[8] = "english";  // 0x504ab8 .data
char DAT_00504e98[8] = "Hard";  // 0x504e98 .data
char DAT_00504ea0[8] = "Medium";  // 0x504ea0 .data
char DAT_00504ea8[8] = "Easy";  // 0x504ea8 .data
int DAT_00505490[6] = {115200, 57600, 38400, 19200, 14400, 9600};  // 0x505490 .data
unsigned int DAT_005054a8 = 16;  // 0x5054a8 .data
// 0x5054b0 .data
char* DAT_005054b0[23] = {
    (char*)"PLAYERx", (char*)"READYx", (char*)"LOGOx", (char*)"SIDEx", (char*)"PINGx", (char*)"MEMx", (char*)"RESx", (char*)"ALLYx",
    (char*)"CDx", (char*)"TEAMICONSx", 0, 0, (char*)"COMMNDER", (char*)"WATCHING", (char*)"FIXEDLOC", (char*)"MAPPING",
    (char*)"TECHLEVL", (char*)"SHARING", (char*)"CHEATING", (char*)"UNITS", (char*)"METAL", (char*)"ENERGY"
};
unsigned int DAT_0050550c = 4294967295u;  // 0x50550c .data
char* DAT_00505518[8] = {(char*)"COMMANDER", (char*)"MAPPING", (char*)"LOSTYPE", (char*)"WATCHING", (char*)"CHEATING", (char*)"FIXEDLOC", (char*)"GAMEOPEN"};  // 0x505518 .data
char DAT_00505974[8] = "Multi";  // 0x505974 .data
char DAT_00505dc4[8] = "Ally";  // 0x505dc4 .data
char DAT_00505f18[8] = "GAMES";  // 0x505f18 .data
char DAT_00505f20[16] = "SAVEGAME DESCS";  // 0x505f20 .data
char DAT_00505f30[16] = "SAVEGAME NAMES";  // 0x505f30 .data
char DAT_00505f40[4] = "LST";  // 0x505f40 .data
char* g_leftGameTexts[8] = {(char*)"has left the scene", (char*)"has been shown the door", (char*)"has gone to a better place", (char*)"has bowed out", (char*)"has terminated", (char*)"has been eradicated", (char*)"has been liquidated", (char*)"has been obliterated"};  // 0x5061b8 .data
int g_timeoutPlayerDpid = -1;  // 0x5061d8 .data
char DAT_00506290[8] = "%s %s";  // 0x506290 .data
char s_PACKET_DATA_00506524[12] = "PACKET DATA";  // 0x506524 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_00506578[8] = "TALK";  // 0x506578 .data
char DAT_0050658c[56] = "has modified his executable.  Game integrity breached.";  // 0x50658c .data
char DAT_005065c4[28] = "Player %s has disconnected";  // 0x5065c4 .data
float g_lightX = -0.800000011920929f;  // 0x5065f8 .data
float g_lightY = 1.0f;  // 0x5065fc .data
float g_lightZ = 0.25f;  // 0x506600 .data
int DAT_00506788 = 1;  // 0x506788 .data
char DAT_005067bc[8] = "NOTRAK";  // 0x5067bc .data
char DAT_00506884[8] = "FXVOL";  // 0x506884 .data
char DAT_0050692c[12] = "TRACKTYPE";  // 0x50692c .data
char DAT_00506964[8] = "CDNEXT";  // 0x506964 .data
char DAT_0050696c[8] = "CDPLAY";  // 0x50696c .data
char DAT_00506974[8] = "CDSTOP";  // 0x506974 .data
char DAT_0050697c[8] = "CDPREV";  // 0x50697c .data
char DAT_00506984[12] = "TRACKMODE";  // 0x506984 .data
char DAT_00506990[8] = "RESTORE";  // 0x506990 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_00506998[8] = "UNDO";  // 0x506998 .data
char DAT_005069b8[8] = "SPEECH";  // 0x5069b8 .data
char DAT_005069c0[8] = "TEST";  // 0x5069c0 .data
char DAT_005069c8[8] = "VOLTEXT";  // 0x5069c8 .data
char DAT_005069d0[8] = "MODE";  // 0x5069d0 .data
char DAT_005069d8[20] = "sounds\\explode.wav";  // 0x5069d8 .data
int g_usePacketManager = 1;  // 0x506dbc .data
char DAT_00507318[32] = "You're out!  Continue Watching?";  // 0x507318 .data
char DAT_005074e8[16] = "RADARPIC TEMP";  // 0x5074e8 .data
char DAT_005074f8[16] = "RADAR PICTURE";  // 0x5074f8 .data
char DAT_00507508[16] = "RADAR MAPPED";  // 0x507508 .data
char DAT_00507518[12] = "RADAR FINAL";  // 0x507518 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char* DAT_00507948[2] = {(char*)"Arm", (char*)"Core"};  // 0x507948 .data
// 0x507950 .data (the type runs past the next known address, 0x507950+0x20)
char* DAT_00507950[9] = {
    (char*)"Kills", (char*)"Losses", (char*)"Energy Produced", (char*)"Metal Produced", (char*)"Excess Energy", (char*)"Excess Metal", (char*)"Commanders Killed", (char*)"Commanders Lost",
    (char*)"I am Winner"
};
int DAT_00507b6c = 1;  // 0x507b6c .data
char* DAT_00507b88[3] = {(char*)"forces have been obliterated", (char*)"vermin have been exterminated", (char*)"forces have gone to a better place"};  // 0x507b88 .data
char DAT_00508384[8] = "Allies";  // 0x508384 .data
const char DAT_00508460[16] = "SkirmishCheat";  // 0x508460 .data
const char DAT_00508470[4] = "*X";  // 0x508470 .data
const char DAT_00508474[4] = "*IX";  // 0x508474 .data
const char DAT_00508478[8] = "*III";  // 0x508478 .data
const char DAT_00508480[8] = "*VIII";  // 0x508480 .data
const char DAT_00508488[8] = "*VII";  // 0x508488 .data
const char DAT_00508490[4] = "*VI";  // 0x508490 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
const char DAT_00508494[4] = "*V";  // 0x508494 .data
const char DAT_00508498[4] = "*IV";  // 0x508498 .data
char DAT_0050849c[16] = "Skirmsetup4x";  // 0x50849c .data
char DAT_005084ac[16] = "SKIRMISH.GUI";  // 0x5084ac .data
char DAT_00508a78[44] = "Error:  Sound system initialization failed.";  // 0x508a78 .data
char DAT_00508aa4[16] = "UseWindowsSound";  // 0x508aa4 .data
char DAT_00508ab4[16] = "NoDirectSound";  // 0x508ab4 .data
char DAT_00508be8[8] = "Killed";  // 0x508be8 .data
char DAT_00508bf0[36] = "%s has taken the lead with %d kills";  // 0x508bf0 .data
char s_TakeDamage_00508d68[12] = "TakeDamage";  // 0x508d68 .data
char s_HitByWeapon_00508d74[12] = "HitByWeapon";  // 0x508d74 .data
char s_paralyze_00508d80[12] = "paralyze";  // 0x508d80 .data
char s_SelectMultipleUnits_00508d8c[20] = "SelectMultipleUnits";  // 0x508d8c .data
char DAT_00508f24[12] = "Celebrated";  // 0x508f24 .data
char DAT_00508f30[12] = "Satisfied";  // 0x508f30 .data
char DAT_00508f3c[36] = "VictoryCondition_KillEnemyCommander";  // 0x508f3c .data
char DAT_00508f60[36] = "VictoryCondition_DestroyAllUnits";  // 0x508f60 .data
char DAT_00508f84[12] = "NumUnits";  // 0x508f84 .data
char DAT_00508f90[36] = "VictoryCondition_KillAllMobileUnits";  // 0x508f90 .data
char DAT_00508fb4[32] = "VictoryCondition_BuildUnitType";  // 0x508fb4 .data
char DAT_00509018[16] = "NumLeftToKill";  // 0x509018 .data
char DAT_00509028[32] = "VictoryCondition_KillUnitType";  // 0x509028 .data
char DAT_005090fc[32] = "DefeatCondition_AllUnitsKilled";  // 0x5090fc .data
char* DAT_005091c8 = (char*)"SAVEGAME";  // 0x5091c8 .data
int DAT_005091cc = 1;  // 0x5091cc .data
int DAT_005091d0 = -1;  // 0x5091d0 .data
const char DAT_005091d4[12] = "OFFSCREEN";  // 0x5091d4 .data
const char DAT_00509200[8] = "CDLISTS";  // 0x509200 .data
const char DAT_00509238[12] = "UnitLimit";  // 0x509238 .data
const char DAT_00509244[12] = "hattfont11";  // 0x509244 .data
const char DAT_00509250[12] = "hattfont12";  // 0x509250 .data
const char DAT_0050925c[12] = "commongui";  // 0x50925c .data
const char DAT_00509268[16] = "SkirmishInfo";  // 0x509268 .data
const char DAT_00509310[24] = "Invalid savegame file";  // 0x509310 .data
char DAT_005093ec[8] = "Enemies";  // 0x5093ec .data
char DAT_005093f4[4] = ",:;";  // 0x5093f4 .data
char DAT_005093f8[8] = "SENDTO";  // 0x5093f8 .data
char DAT_00509400[12] = "SENDTYPE";  // 0x509400 .data
char DAT_0050940c[12] = "LIVEPLYR";  // 0x50940c .data
char DAT_0050966c[12] = "SHOT";  // 0x50966c .data
char* DAT_00509678[4] = {(char*)"FirePrimary", (char*)"FireSecondary", (char*)"FireTertiary"};  // 0x509678 .data
char* DAT_00509688[3] = {(char*)"AimPrimary", (char*)"AimSecondary", (char*)"AimTertiary"};  // 0x509688 .data
char* DAT_00509718 = (char*)"Total Annihilation Class";  // 0x509718 .data
char* DAT_0050971c = (char*)"Total Annihilation";  // 0x50971c .data
int DAT_00509720 = 1;  // 0x509720 .data
const char DAT_005097a8[8] = "cdshell";  // 0x5097a8 .data
const char DAT_005097b0[32] = "SOFTWARE\\Classes\\AudioCD\\shell";  // 0x5097b0 .data
const char DAT_005097d0[24] = "gamedata\\translate.tdf";  // 0x5097d0 .data
const char DAT_005097e8[12] = "language";  // 0x5097e8 .data
const char DAT_005097f4[8] = "Wargame";  // 0x5097f4 .data
const char g_errorCaption[20] = "Error";  // 0x509edc .data
double DAT_00509ef0 = 10430.37835047;  // 0x509ef0 .data
double DAT_00509ef8 = 9.587379924285e-05;  // 0x509ef8 .data
// 0x509f00 .data
short DAT_00509f00[128] = {
    0, 101, 201, 302, 402, 502, 603, 703,
    803, 903, 1003, 1102, 1202, 1301, 1401, 1499,
    1598, 1697, 1795, 1893, 1990, 2088, 2185, 2282,
    2378, 2474, 2570, 2665, 2760, 2854, 2948, 3042,
    3135, 3228, 3320, 3411, 3503, 3593, 3683, 3773,
    3862, 3950, 4038, 4125, 4212, 4297, 4383, 4467,
    4551, 4634, 4717, 4799, 4880, 4960, 5040, 5119,
    5197, 5274, 5351, 5427, 5501, 5575, 5649, 5721,
    5793, 5863, 5933, 6002, 6070, 6137, 6203, 6268,
    6333, 6396, 6458, 6519, 6580, 6639, 6698, 6755,
    6811, 6867, 6921, 6974, 7027, 7078, 7128, 7177,
    7225, 7272, 7317, 7362, 7405, 7448, 7489, 7529,
    7568, 7606, 7643, 7679, 7713, 7746, 7779, 7809,
    7839, 7868, 7895, 7921, 7946, 7970, 7993, 8014,
    8035, 8054, 8071, 8088, 8103, 8117, 8130, 8142,
    8153, 8162, 8170, 8177, 8182, 8186, 8190, 8191
};
// 0x50a000 .data
short DAT_0050a000[512] = {
    8192, 8191, 8190, 8186, 8182, 8177, 8170, 8162,
    8153, 8142, 8130, 8117, 8103, 8088, 8071, 8054,
    8035, 8014, 7993, 7970, 7946, 7921, 7895, 7868,
    7839, 7809, 7779, 7746, 7713, 7679, 7643, 7606,
    7568, 7529, 7489, 7448, 7405, 7362, 7317, 7272,
    7225, 7177, 7128, 7078, 7027, 6974, 6921, 6867,
    6811, 6755, 6698, 6639, 6580, 6519, 6458, 6396,
    6333, 6268, 6203, 6137, 6070, 6002, 5933, 5863,
    5793, 5721, 5649, 5575, 5501, 5427, 5351, 5274,
    5197, 5119, 5040, 4960, 4880, 4799, 4717, 4634,
    4551, 4467, 4383, 4297, 4212, 4125, 4038, 3950,
    3862, 3773, 3683, 3593, 3503, 3411, 3320, 3228,
    3135, 3042, 2948, 2854, 2760, 2665, 2570, 2474,
    2378, 2282, 2185, 2088, 1990, 1893, 1795, 1697,
    1598, 1499, 1401, 1301, 1202, 1102, 1003, 903,
    803, 703, 603, 502, 402, 302, 201, 101,
    0, -101, -201, -302, -402, -502, -603, -703,
    -803, -903, -1003, -1102, -1202, -1301, -1401, -1499,
    -1598, -1697, -1795, -1893, -1990, -2088, -2185, -2282,
    -2378, -2474, -2570, -2665, -2760, -2854, -2948, -3042,
    -3135, -3228, -3320, -3411, -3503, -3593, -3683, -3773,
    -3862, -3950, -4038, -4125, -4212, -4297, -4383, -4467,
    -4551, -4634, -4717, -4799, -4880, -4960, -5040, -5119,
    -5197, -5274, -5351, -5427, -5501, -5575, -5649, -5721,
    -5793, -5863, -5933, -6002, -6070, -6137, -6203, -6268,
    -6333, -6396, -6458, -6519, -6580, -6639, -6698, -6755,
    -6811, -6867, -6921, -6974, -7027, -7078, -7128, -7177,
    -7225, -7272, -7317, -7362, -7405, -7448, -7489, -7529,
    -7568, -7606, -7643, -7679, -7713, -7746, -7779, -7809,
    -7839, -7868, -7895, -7921, -7946, -7970, -7993, -8014,
    -8035, -8054, -8071, -8088, -8103, -8117, -8130, -8142,
    -8153, -8162, -8170, -8177, -8182, -8186, -8190, -8191,
    -8192, -8191, -8190, -8186, -8182, -8177, -8170, -8162,
    -8153, -8142, -8130, -8117, -8103, -8088, -8071, -8054,
    -8035, -8014, -7993, -7970, -7946, -7921, -7895, -7868,
    -7839, -7809, -7779, -7746, -7713, -7679, -7643, -7606,
    -7568, -7529, -7489, -7448, -7405, -7362, -7317, -7272,
    -7225, -7177, -7128, -7078, -7027, -6974, -6921, -6867,
    -6811, -6755, -6698, -6639, -6580, -6519, -6458, -6396,
    -6333, -6268, -6203, -6137, -6070, -6002, -5933, -5863,
    -5793, -5721, -5649, -5575, -5501, -5427, -5351, -5274,
    -5197, -5119, -5040, -4960, -4880, -4799, -4717, -4634,
    -4551, -4467, -4383, -4297, -4212, -4125, -4038, -3950,
    -3862, -3773, -3683, -3593, -3503, -3411, -3320, -3228,
    -3135, -3042, -2948, -2854, -2760, -2665, -2570, -2474,
    -2378, -2282, -2185, -2088, -1990, -1893, -1795, -1697,
    -1598, -1499, -1401, -1301, -1202, -1102, -1003, -903,
    -803, -703, -603, -502, -402, -302, -201, -101,
    0, 101, 201, 302, 402, 502, 603, 703,
    803, 903, 1003, 1102, 1202, 1301, 1401, 1499,
    1598, 1697, 1795, 1893, 1990, 2088, 2185, 2282,
    2378, 2474, 2570, 2665, 2760, 2854, 2948, 3042,
    3135, 3228, 3320, 3411, 3503, 3593, 3683, 3773,
    3862, 3950, 4038, 4125, 4212, 4297, 4383, 4467,
    4551, 4634, 4717, 4799, 4880, 4960, 5040, 5119,
    5197, 5274, 5351, 5427, 5501, 5575, 5649, 5721,
    5793, 5863, 5933, 6002, 6070, 6137, 6203, 6268,
    6333, 6396, 6458, 6519, 6580, 6639, 6698, 6755,
    6811, 6867, 6921, 6974, 7027, 7078, 7128, 7177,
    7225, 7272, 7317, 7362, 7405, 7448, 7489, 7529,
    7568, 7606, 7643, 7679, 7713, 7746, 7779, 7809,
    7839, 7868, 7895, 7921, 7946, 7970, 7993, 8014,
    8035, 8054, 8071, 8088, 8103, 8117, 8130, 8142,
    8153, 8162, 8170, 8177, 8182, 8186, 8190, 8191
};
int DAT_0050a400[9] = {0};  // 0x50a400 .data
char DAT_0050a430[12] = "ALPHA TABLE";  // 0x50a430 .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
const char DAT_0050a43c[12] = "SHADE TABLE";  // 0x50a43c .data (holds 1 value(s) that look like addresses in the exe: they need symbols before this can be relinked)
char DAT_0050a548[4] = "..";  // 0x50a548 .data
char DAT_0050a56c[16] = "Package Data";  // 0x50a56c .data
char DAT_0050a57c[4] = "\\*";  // 0x50a57c .data
char DAT_0050a5c0[16] = "HAPIFILE array";  // 0x50a5c0 .data
int g_emptyStringRefs = 1;  // 0x50a778 .data
void* g_emptyString = 0;  // 0x50a77c .data
int g_guaranteePackets = 1;  // 0x50a780 .data
int g_cdNextTrackTimer = -1;  // 0x50b540 .data
int g_cdFadeTimer = -1;  // 0x50b544 .data
void* g_squashErrorNames[7] = {(void*)"SQUASHERR_OK", (void*)"SQUASHERR_BADHEADER", (void*)"SQUASHERR_BADCHECKSUM", (void*)"SQUASHERR_BADUNPACKSIZE", (void*)"SQUASHERR_BADUNPACKTYPE", (void*)"SQUASHERR_BADPACKTYPESQUASHERR_BADPARAMS"};  // 0x50b9e0 .data
char DAT_0050c8ac[8] = "Cavedog";  // 0x50c8ac .data
// 0x50c908 .data
char* DAT_0050c908[19] = {
    (char*)"-memfussy", (char*)"-memnofussy", (char*)"-memfrontalign", (char*)"-gonzo", (char*)"-memset", (char*)"-memnoset", (char*)"-fpufussy", (char*)"-fpunofussy",
    (char*)"-dprinton", (char*)"-dprintoff", (char*)"-dprintfile", (char*)DAT_0050d220, (char*)"-performancestatus", (char*)"-disableimagehlp", (char*)"-enableimagehlp", (char*)"-disableimagehlplines",
    (char*)"-enableimagehlplines", (char*)"-debughelper", (char*)"-saveresources"
};
char DAT_0050d220[16] = "-memorystatus";  // 0x50d220 .data
const char DAT_0050d2d0[28] = "Global Exception Handler";  // 0x50d2d0 .data
char* DAT_0050d4d0 = (char*)"Library date stamp: Jun 30 1998 16:08:53";  // 0x50d4d0 .data
char* DAT_0050d660 = (char*)"Performance status";  // 0x50d660 .data
char DAT_0050d6b4[36] = "Performance dialog failed to open";  // 0x50d6b4 .data
char* DAT_0050d72c = (char*)"Memory Status";  // 0x50d72c .data
char DAT_005119b8[8];  // 0x5119b8 .bss
int DAT_005119e8[10];  // 0x5119e8 .bss
int DAT_00511a10[10];  // 0x511a10 .bss
int DAT_00511a38;  // 0x511a38 .bss
unsigned char DAT_00511a3c[4];  // 0x511a3c .bss
int g_byteRatesLastReceived;  // 0x511a40 .bss
int g_compressionPercent;  // 0x511a44 .bss
unsigned int g_bytesSentPerSecond;  // 0x511a48 .bss
int g_lastPacketBytesSent;  // 0x511a4c .bss
unsigned int g_bytesReceivedPerSecond;  // 0x511a50 .bss
unsigned char DAT_00511a54[4];  // 0x511a54 .bss
int g_messageCountByType[45][2];  // 0x511a58 .bss (the type runs past the next known address, 0x511a58+0x4)
int DAT_00511bc0;  // 0x511bc0 .bss
int DAT_00511bc4;  // 0x511bc4 .bss
int DAT_00511bc8;  // 0x511bc8 .bss
int g_lastPacketBytesReceived;  // 0x511bcc .bss
char DAT_00511bd0[80];  // 0x511bd0 .bss
int DAT_00511c20;  // 0x511c20 .bss
int g_lastPacketsSent;  // 0x511c24 .bss
int g_lastPacketsReceived;  // 0x511c28 .bss
int g_byteRatesLastSent;  // 0x511c2c .bss
unsigned int g_packetBytesReceivedRate;  // 0x511c30 .bss
int DAT_00511c34;  // 0x511c34 .bss
unsigned int g_messageBytesReceivedRate;  // 0x511c38 .bss
unsigned int g_messageBytesSentRate;  // 0x511c3c .bss
int g_lastMessageBytesReceived;  // 0x511c40 .bss
int g_lastMessageBytesSent;  // 0x511c44 .bss
int DAT_00511c48;  // 0x511c48 .bss
unsigned int g_packetBytesSentRate;  // 0x511c4c .bss
int DAT_00511c50;  // 0x511c50 .bss
unsigned char DAT_00511c54[4];  // 0x511c54 .bss
int g_messageBytesByType[45][2];  // 0x511c58 .bss (the type runs past the next known address, 0x511c58+0x8)
unsigned int g_packetsReceivedRate;  // 0x511dc0 .bss
unsigned int g_packetsSentRate;  // 0x511dc4 .bss
int g_compressedBytesSent;  // 0x511dc8 .bss
int g_lastCompressedBytesSent;  // 0x511dcc .bss
int DAT_00511dd0;  // 0x511dd0 .bss
int DAT_00511dd4;  // 0x511dd4 .bss
unsigned int g_netStatsTick;  // 0x511dd8 .bss
unsigned int g_byteRatesTick;  // 0x511ddc .bss
int DAT_00511de0;  // 0x511de0 .bss
int g_cdPathMismatch;  // 0x511de4 .bss
Game* g_game;  // 0x511de8 .bss
int DAT_00511dec;  // 0x511dec .bss
unsigned char DAT_00511f80[16];  // 0x511f80 .bss
int DAT_00511f90;  // 0x511f90 .bss
int DAT_00511f94;  // 0x511f94 .bss
int DAT_00511f98;  // 0x511f98 .bss
int DAT_00511f9c;  // 0x511f9c .bss
int DAT_00511fa0;  // 0x511fa0 .bss
int DAT_00511fa4;  // 0x511fa4 .bss
int DAT_00511fa8;  // 0x511fa8 .bss
int DAT_00511fac;  // 0x511fac .bss
int DAT_00511fb0;  // 0x511fb0 .bss
unsigned char DAT_00511fb4[4];  // 0x511fb4 .bss
char DAT_00511fb8[256];  // 0x511fb8 .bss
int DAT_00512288;  // 0x512288 .bss
int DAT_0051228c;  // 0x51228c .bss
int DAT_00512290;  // 0x512290 .bss
int DAT_00512294;  // 0x512294 .bss
int DAT_0051229c;  // 0x51229c .bss
unsigned char DAT_005122a0[4];  // 0x5122a0 .bss
MapCacheEntry* DAT_005122c4;  // 0x5122c4 .bss
MapCacheEntry* DAT_005122c8;  // 0x5122c8 .bss
unsigned char DAT_005122cc[4];  // 0x5122cc .bss
char* DAT_005122d4;  // 0x5122d4 .bss
int DAT_005122d8;  // 0x5122d8 .bss
int DAT_005122dc;  // 0x5122dc .bss
int DAT_005122e0;  // 0x5122e0 .bss
unsigned char DAT_005122e4[4];  // 0x5122e4 .bss
int g_meteorNextStrikeTime;  // 0x5122e8 .bss
unsigned char DAT_005122ec[4];  // 0x5122ec .bss
char DAT_005122f0[32];  // 0x5122f0 .bss
int DAT_00512310;  // 0x512310 .bss
int DAT_00512314;  // 0x512314 .bss
int g_meteorActive;  // 0x512318 .bss
int g_meteorStrikeEndTime;  // 0x51231c .bss
unsigned char g_meteorOrigin[4];  // 0x512320 .bss
int DAT_00512324;  // 0x512324 .bss
Player_00437cd0* DAT_00512328;  // 0x512328 .bss
int g_meteorsEnabled;  // 0x51232c .bss
int g_meteorNextHitTime;  // 0x512330 .bss
unsigned char g_meteorTarget[4];  // 0x512334 .bss
int DAT_00512338;  // 0x512338 .bss
unsigned char DAT_0051233c[4];  // 0x51233c .bss
unsigned char DAT_00512350[8];  // 0x512350 .bss
unsigned char DAT_00512758[8];  // 0x512758 .bss
int DAT_00512760;  // 0x512760 .bss
int DAT_00512768;  // 0x512768 .bss
int DAT_0051276c;  // 0x51276c .bss
unsigned char DAT_00512780[8];  // 0x512780 .bss
unsigned int DAT_00512788;  // 0x512788 .bss
unsigned char DAT_0051278c[60];  // 0x51278c .bss
unsigned char DAT_005127c8[432];  // 0x5127c8 .bss
int DAT_00512978;  // 0x512978 .bss
int DAT_0051297c;  // 0x51297c .bss
char* DAT_00512980;  // 0x512980 .bss
int DAT_00512984;  // 0x512984 .bss
Entry_00443100* DAT_00512988;  // 0x512988 .bss
char* DAT_0051298c;  // 0x51298c .bss
char* DAT_00512990;  // 0x512990 .bss
int DAT_00512994;  // 0x512994 .bss
unsigned char DAT_00512998[12];  // 0x512998 .bss
int DAT_005129a4;  // 0x5129a4 .bss
unsigned int DAT_005129a8;  // 0x5129a8 .bss
char* DAT_005129b0;  // 0x5129b0 .bss
Record_005129b4* DAT_005129b4;  // 0x5129b4 .bss
unsigned char DAT_005129bc[4];  // 0x5129bc .bss
int DAT_005129c0;  // 0x5129c0 .bss
int* DAT_005129c4;  // 0x5129c4 .bss
int DAT_005129c8;  // 0x5129c8 .bss
unsigned char DAT_005129cc[4];  // 0x5129cc .bss
void (__stdcall* g_packetHandlers[2])(void*);  // 0x512a20 .bss
int (__stdcall* DAT_00512a28)(int);  // 0x512a28 .bss
int (__stdcall* DAT_00512a2c)(int);  // 0x512a2c .bss
unsigned char DAT_00512a30[4];  // 0x512a30 .bss
int (__stdcall* DAT_00512a34)(int);  // 0x512a34 .bss
int (__stdcall* DAT_00512a38)(int);  // 0x512a38 .bss
int (__stdcall* DAT_00512a3c)(int);  // 0x512a3c .bss
int (__stdcall* DAT_00512a40)(int);  // 0x512a40 .bss
int (__stdcall* DAT_00512a44)(int);  // 0x512a44 .bss
int (__stdcall* DAT_00512a48)(int);  // 0x512a48 .bss
int (__stdcall* DAT_00512a4c)(int);  // 0x512a4c .bss
int (__stdcall* DAT_00512a50)(int);  // 0x512a50 .bss
int (__stdcall* DAT_00512a54)(int);  // 0x512a54 .bss
int (__stdcall* DAT_00512a58)(int);  // 0x512a58 .bss
int (__stdcall* DAT_00512a5c)(int);  // 0x512a5c .bss
int (__stdcall* DAT_00512a60)(int);  // 0x512a60 .bss
int (__stdcall* DAT_00512a64)(int);  // 0x512a64 .bss
int (__stdcall* DAT_00512a68)(int);  // 0x512a68 .bss
int (__stdcall* DAT_00512a6c)(int);  // 0x512a6c .bss
int (__stdcall* DAT_00512a70)(int);  // 0x512a70 .bss
int (__stdcall* DAT_00512a74)(int);  // 0x512a74 .bss
int (__stdcall* DAT_00512a78)(int);  // 0x512a78 .bss
int (__stdcall* DAT_00512a7c)(int);  // 0x512a7c .bss
int (__stdcall* DAT_00512a80)(int);  // 0x512a80 .bss
int (__stdcall* DAT_00512a84)(int);  // 0x512a84 .bss
int (__stdcall* DAT_00512a88)(int);  // 0x512a88 .bss
int (__stdcall* DAT_00512a8c)(int);  // 0x512a8c .bss
int (__stdcall* DAT_00512a90)(int);  // 0x512a90 .bss
int (__stdcall* DAT_00512a94)(int);  // 0x512a94 .bss
int (__stdcall* DAT_00512a98)(int);  // 0x512a98 .bss
int (__stdcall* DAT_00512a9c)(int);  // 0x512a9c .bss
int (__stdcall* DAT_00512aa0)(int);  // 0x512aa0 .bss
int (__stdcall* DAT_00512aa4)(int);  // 0x512aa4 .bss
int (__stdcall* DAT_00512aa8)(int);  // 0x512aa8 .bss
int (__stdcall* DAT_00512aac)(int);  // 0x512aac .bss
int (__stdcall* DAT_00512ab0)(int);  // 0x512ab0 .bss
int (__stdcall* DAT_00512ab4)(int);  // 0x512ab4 .bss
int (__stdcall* DAT_00512ab8)(int);  // 0x512ab8 .bss
int (__stdcall* DAT_00512abc)(int);  // 0x512abc .bss
int (__stdcall* DAT_00512ac0)(int);  // 0x512ac0 .bss
int (__stdcall* DAT_00512ac4)(int);  // 0x512ac4 .bss
int (__stdcall* DAT_00512ac8)(int);  // 0x512ac8 .bss
unsigned char DAT_00512acc[4];  // 0x512acc .bss
int (__stdcall* DAT_00512ad0)(int);  // 0x512ad0 .bss
unsigned char DAT_00512ad4[4];  // 0x512ad4 .bss
unsigned short DAT_00512ad8[2][2];  // 0x512ad8 .bss
int DAT_00512adc;  // 0x512adc .bss
int DAT_00512ae0;  // 0x512ae0 .bss
int DAT_00512ae4;  // 0x512ae4 .bss
unsigned char DAT_00512ae8[4];  // 0x512ae8 .bss
int DAT_00512aec;  // 0x512aec .bss
int DAT_00512af0;  // 0x512af0 .bss
int DAT_00512af4;  // 0x512af4 .bss
int DAT_00512af8;  // 0x512af8 .bss
int DAT_00512afc;  // 0x512afc .bss
int DAT_00512b00;  // 0x512b00 .bss
int DAT_00512b04;  // 0x512b04 .bss
int DAT_00512b08;  // 0x512b08 .bss
int DAT_00512b0c;  // 0x512b0c .bss
int DAT_00512b10;  // 0x512b10 .bss
int DAT_00512b14;  // 0x512b14 .bss
int DAT_00512b18;  // 0x512b18 .bss
int DAT_00512b1c;  // 0x512b1c .bss
int DAT_00512b20;  // 0x512b20 .bss
int DAT_00512b24;  // 0x512b24 .bss
int DAT_00512b28;  // 0x512b28 .bss
int DAT_00512b2c;  // 0x512b2c .bss
int DAT_00512b30;  // 0x512b30 .bss
int DAT_00512b34;  // 0x512b34 .bss
int DAT_00512b38;  // 0x512b38 .bss
int DAT_00512b3c;  // 0x512b3c .bss
int DAT_00512b40;  // 0x512b40 .bss
int DAT_00512b44;  // 0x512b44 .bss
int DAT_00512b48;  // 0x512b48 .bss
int DAT_00512b4c;  // 0x512b4c .bss
int DAT_00512b50;  // 0x512b50 .bss
int DAT_00512b54;  // 0x512b54 .bss
int DAT_00512b58;  // 0x512b58 .bss
int DAT_00512b5c;  // 0x512b5c .bss
int DAT_00512b60;  // 0x512b60 .bss
int DAT_00512b64;  // 0x512b64 .bss
int DAT_00512b68;  // 0x512b68 .bss
int DAT_00512b6c;  // 0x512b6c .bss
int DAT_00512b70;  // 0x512b70 .bss
int DAT_00512b74;  // 0x512b74 .bss
int DAT_00512b78;  // 0x512b78 .bss
int DAT_00512b7c;  // 0x512b7c .bss
int DAT_00512b80;  // 0x512b80 .bss
unsigned char DAT_00512b84[4];  // 0x512b84 .bss
int DAT_00512b88;  // 0x512b88 .bss
unsigned char DAT_00512b8c[4];  // 0x512b8c .bss
int DAT_00512b90[12];  // 0x512b90 .bss
int g_packetModes[2];  // 0x512bc0 .bss
int DAT_00512bc8;  // 0x512bc8 .bss
int DAT_00512bcc;  // 0x512bcc .bss
unsigned char DAT_00512bd0[4];  // 0x512bd0 .bss
int DAT_00512bd4;  // 0x512bd4 .bss
int DAT_00512bd8;  // 0x512bd8 .bss
int DAT_00512bdc;  // 0x512bdc .bss
int DAT_00512be0;  // 0x512be0 .bss
int DAT_00512be4;  // 0x512be4 .bss
int DAT_00512be8;  // 0x512be8 .bss
int DAT_00512bec;  // 0x512bec .bss
int DAT_00512bf0;  // 0x512bf0 .bss
int DAT_00512bf4;  // 0x512bf4 .bss
int DAT_00512bf8;  // 0x512bf8 .bss
int DAT_00512bfc;  // 0x512bfc .bss
int DAT_00512c00;  // 0x512c00 .bss
int DAT_00512c04;  // 0x512c04 .bss
int DAT_00512c08;  // 0x512c08 .bss
int DAT_00512c0c;  // 0x512c0c .bss
int DAT_00512c10;  // 0x512c10 .bss
int DAT_00512c14;  // 0x512c14 .bss
int DAT_00512c18;  // 0x512c18 .bss
int DAT_00512c1c;  // 0x512c1c .bss
int DAT_00512c20;  // 0x512c20 .bss
int DAT_00512c24;  // 0x512c24 .bss
int DAT_00512c28;  // 0x512c28 .bss
int DAT_00512c2c;  // 0x512c2c .bss
int DAT_00512c30;  // 0x512c30 .bss
unsigned char DAT_00512c34[4];  // 0x512c34 .bss
int DAT_00512c38;  // 0x512c38 .bss
int DAT_00512c3c;  // 0x512c3c .bss
int DAT_00512c40;  // 0x512c40 .bss
int DAT_00512c44;  // 0x512c44 .bss
int DAT_00512c48;  // 0x512c48 .bss
int DAT_00512c4c;  // 0x512c4c .bss
int DAT_00512c50;  // 0x512c50 .bss
int DAT_00512c54;  // 0x512c54 .bss
int DAT_00512c58;  // 0x512c58 .bss
int DAT_00512c5c;  // 0x512c5c .bss
int DAT_00512c60;  // 0x512c60 .bss
int DAT_00512c64;  // 0x512c64 .bss
int DAT_00512c68;  // 0x512c68 .bss
unsigned char DAT_00512c6c[4];  // 0x512c6c .bss
int DAT_00512c70;  // 0x512c70 .bss
int g_loungeRefreshTime;  // 0x512c78 .bss
unsigned int g_timeoutTimerStart;  // 0x512c7c .bss
unsigned char DAT_00512c80[336];  // 0x512c80 .bss (the type runs past the next known address, 0x512c80+0x4)
char DAT_00512dd0[260];  // 0x512dd0 .bss
unsigned char DAT_00512ed4[20];  // 0x512ed4 .bss
int g_onlineConfigLoaded;  // 0x512ee8 .bss
void* g_onlineDll;  // 0x512eec .bss
int DAT_00512ef0;  // 0x512ef0 .bss
unsigned char DAT_00512ef4[4];  // 0x512ef4 .bss
unsigned char DAT_00512ef8[24];  // 0x512ef8 .bss
int DAT_00512f10;  // 0x512f10 .bss
int DAT_00512f14;  // 0x512f14 .bss
unsigned char DAT_00512f18[85];  // 0x512f18 .bss
int DAT_00512f6d;  // 0x512f6d .bss
int DAT_00512fd9;  // 0x512fd9 .bss
int DAT_00512fe0;  // 0x512fe0 .bss
int DAT_00512fe4;  // 0x512fe4 .bss
int DAT_00512fec;  // 0x512fec .bss
int DAT_00512ff0;  // 0x512ff0 .bss
int DAT_00512ff8;  // 0x512ff8 .bss
unsigned char DAT_00512ffc[4];  // 0x512ffc .bss
int DAT_0051e53c;  // 0x51e53c .bss
int DAT_0051e540;  // 0x51e540 .bss
int DAT_0051e544;  // 0x51e544 .bss
int (__stdcall* DAT_0051e54c)(int*, int);  // 0x51e54c .bss
int (__stdcall* DAT_0051e554)(char*);  // 0x51e554 .bss
void (__cdecl* DAT_0051e558)(void);  // 0x51e558 .bss
unsigned char DAT_0051e55c[4];  // 0x51e55c .bss
unsigned char g_reportPlayerName[20];  // 0x51e560 .bss
void (__stdcall* DAT_0051e578)(void (__stdcall*)(int), int (__stdcall*)(char*, int));  // 0x51e578 .bss
int (__stdcall* DAT_0051e588)(int);  // 0x51e588 .bss
int DAT_0051e58c;  // 0x51e58c .bss
int DAT_0051e590;  // 0x51e590 .bss
int g_reportFlags;  // 0x51e594 .bss
char g_unitSyncStatusText[104];  // 0x51e5a0 .bss
char DAT_0051e608;  // 0x51e608 .bss
unsigned char DAT_0051e609[7];  // 0x51e609 .bss
unsigned char DAT_0051e610[36];  // 0x51e610 .bss
unsigned char DAT_0051e634;  // 0x51e634 .bss
unsigned char DAT_0051e635[7];  // 0x51e635 .bss
char* DAT_0051e63c;  // 0x51e63c .bss
unsigned char DAT_0051e644[8];  // 0x51e644 .bss
int DAT_0051e64c;  // 0x51e64c .bss
int DAT_0051e650;  // 0x51e650 .bss
int DAT_0051e654;  // 0x51e654 .bss
unsigned char DAT_0051e658[4];  // 0x51e658 .bss
int* DAT_0051e65c;  // 0x51e65c .bss
unsigned char DAT_0051e664[4];  // 0x51e664 .bss
int DAT_0051e668;  // 0x51e668 .bss
int DAT_0051e66c;  // 0x51e66c .bss
int DAT_0051e670;  // 0x51e670 .bss
short DAT_0051e674;  // 0x51e674 .bss
int DAT_0051e678;  // 0x51e678 .bss
unsigned int DAT_0051e67c;  // 0x51e67c .bss
unsigned int DAT_0051e680;  // 0x51e680 .bss
int DAT_0051e684;  // 0x51e684 .bss
int DAT_0051e688;  // 0x51e688 .bss
SpeechQueue* DAT_0051e68c;  // 0x51e68c .bss
int g_noDirectSound;  // 0x51e690 .bss
int g_useWindowsSound;  // 0x51e694 .bss
int DAT_0051e698;  // 0x51e698 .bss
int g_playLooping;  // 0x51e69c .bss
unsigned char DAT_0051e6b0[12];  // 0x51e6b0 .bss
unsigned char DAT_0051e6bc[4];  // 0x51e6bc .bss
int DAT_0051e6c0;  // 0x51e6c0 .bss
unsigned int DAT_0051e6c4;  // 0x51e6c4 .bss
unsigned char DAT_0051e6c8[8];  // 0x51e6c8 .bss
int DAT_0051e6d0[10];  // 0x51e6d0 .bss
char DAT_0051e6f8[24];  // 0x51e6f8 .bss
int DAT_0051e710[30];  // 0x51e710 .bss
char DAT_0051e788[136];  // 0x51e788 .bss
unsigned char DAT_0051e810[10];  // 0x51e810 .bss (the type runs past the next known address, 0x51e810+0x8)
unsigned char DAT_0051e81a[6];  // 0x51e81a .bss
unsigned char DAT_0051e820[5];  // 0x51e820 .bss
unsigned char DAT_0051e825[3];  // 0x51e825 .bss
unsigned char DAT_0051f2c8[10];  // 0x51f2c8 .bss (the type runs past the next known address, 0x51f2c8+0x8)
unsigned char DAT_0051f2d2[6];  // 0x51f2d2 .bss
unsigned int DAT_0051f2d8;  // 0x51f2d8 .bss
int DAT_0051f2dc;  // 0x51f2dc .bss
int DAT_0051f2f0;  // 0x51f2f0 .bss
int DAT_0051f2f4;  // 0x51f2f4 .bss
unsigned int DAT_0051f2f8;  // 0x51f2f8 .bss
int DAT_0051f2fc;  // 0x51f2fc .bss
int DAT_0051f300;  // 0x51f300 .bss
int DAT_0051f304;  // 0x51f304 .bss
unsigned char DAT_0051f308[8];  // 0x51f308 .bss
unsigned char DAT_0051f31c;  // 0x51f31c .bss
unsigned char DAT_0051f320[2088];  // 0x51f320 .bss
int DAT_0051fb48;  // 0x51fb48 .bss
unsigned char DAT_0051fb4c[4];  // 0x51fb4c .bss
char DAT_0051fb50[64];  // 0x51fb50 .bss
int DAT_0051fb90;  // 0x51fb90 .bss
unsigned long DAT_0051fb94;  // 0x51fb94 .bss
unsigned char DAT_0051fb98[4];  // 0x51fb98 .bss
char* g_loopingWav;  // 0x51fb9c .bss
int* g_diskWav;  // 0x51fba0 .bss
Dialog* g_guiContext;  // 0x51fba4 .bss
int DAT_0051fba8;  // 0x51fba8 .bss
int DAT_0051fbac;  // 0x51fbac .bss
int DAT_0051fbb0;  // 0x51fbb0 .bss
int DAT_0051fbb4;  // 0x51fbb4 .bss
int DAT_0051fbb8;  // 0x51fbb8 .bss
unsigned char DAT_0051fbd4[4];  // 0x51fbd4 .bss
unsigned char DAT_0051fbd8[172];  // 0x51fbd8 .bss
unsigned int DAT_0051fc84;  // 0x51fc84 .bss
unsigned int g_randomSeed;  // 0x51fc88 .bss
unsigned char DAT_0051fc8c[4];  // 0x51fc8c .bss
int g_defaultCommandHandler;  // 0x51fc90 .bss
int g_defaultCommandMask;  // 0x51fc94 .bss
unsigned char DAT_0051fcb0[256];  // 0x51fcb0 .bss
int DAT_0051fdb0;  // 0x51fdb0 .bss
unsigned char DAT_0051fdb4[4];  // 0x51fdb4 .bss
TranslationTable* g_translations;  // 0x51fdb8 .bss
unsigned char DAT_0051fdbc[4];  // 0x51fdbc .bss
char g_language[304];  // 0x51fdc0 .bss
int DAT_0051fef0;  // 0x51fef0 .bss
int DAT_0051fef4;  // 0x51fef4 .bss
Chunk* DAT_0051fef8;  // 0x51fef8 .bss
int DAT_0051fefc;  // 0x51fefc .bss
int DAT_0051ff00;  // 0x51ff00 .bss
int DAT_0051ff04;  // 0x51ff04 .bss
int DAT_0051ff08;  // 0x51ff08 .bss
int g_enumSessionsResult;  // 0x51ff0c .bss
int g_cdFadeVolume;  // 0x51ff10 .bss
void* g_cdPlayerWindow;  // 0x51ff18 .bss
unsigned char DAT_0051ff1c[4];  // 0x51ff1c .bss
int DAT_0051ff20[10];  // 0x51ff20 .bss
int g_playBufferLooping;  // 0x51ff48 .bss
unsigned char DAT_0051ff4c[12];  // 0x51ff4c .bss
int DAT_0051ff58;  // 0x51ff58 .bss
unsigned char DAT_0051ff5c[4];  // 0x51ff5c .bss
char DAT_0051ff60[112];  // 0x51ff60 .bss
char g_lzssPresetWindow[176];  // 0x51ffd0 .bss
unsigned char DAT_00520080[3944];  // 0x520080 .bss
char g_lzssPresetTree[24584];  // 0x520fe8 .bss
Struct_00526ff0* DAT_00526ff0;  // 0x526ff0 .bss
int g_lzssPresetReady;  // 0x526ff8 .bss
int g_lzssUsePreset;  // 0x526ffc .bss (the type runs past the next known address, 0x526ffc+0x3)
char DAT_005289b4;  // 0x5289b4 .bss
char DAT_005289b8;  // 0x5289b8 .bss
void (__stdcall* DAT_005289bc)(void);  // 0x5289bc .bss
int DAT_005289c0;  // 0x5289c0 .bss
int DAT_005289c4;  // 0x5289c4 .bss
unsigned char DAT_005289c8;  // 0x5289c8 .bss
unsigned char DAT_005289cc;  // 0x5289cc .bss
unsigned int DAT_005289d0;  // 0x5289d0 .bss
unsigned int DAT_005289d4;  // 0x5289d4 .bss
unsigned int DAT_005289d8;  // 0x5289d8 .bss
unsigned int DAT_005289dc;  // 0x5289dc .bss
void* DAT_005289e0;  // 0x5289e0 .bss
unsigned char DAT_005289e4[8];  // 0x5289e4 .bss
unsigned int DAT_005289f0;  // 0x5289f0 .bss
unsigned char DAT_005289f4[4];  // 0x5289f4 .bss
unsigned int DAT_005289f8;  // 0x5289f8 .bss
unsigned int DAT_005289fc;  // 0x5289fc .bss
unsigned int DAT_00528a00;  // 0x528a00 .bss
unsigned int DAT_00528a04;  // 0x528a04 .bss
unsigned int DAT_00528a08;  // 0x528a08 .bss
unsigned char DAT_00528a0c[4];  // 0x528a0c .bss
unsigned char DAT_00528a14[8];  // 0x528a14 .bss
unsigned int DAT_00528a1c;  // 0x528a1c .bss
unsigned char DAT_00528a20[8];  // 0x528a20 .bss
FreeBlockMap* DAT_00528a40;  // 0x528a40 .bss
void* DAT_00528a44;  // 0x528a44 .bss
unsigned char DAT_00528a48[4];  // 0x528a48 .bss
int DAT_00528a4c;  // 0x528a4c .bss
Node_004dde70* DAT_00528a50;  // 0x528a50 .bss
unsigned char DAT_00528a5c[4];  // 0x528a5c .bss
unsigned char DAT_00528a78[44];  // 0x528a78 .bss
void* DAT_00528aa4;  // 0x528aa4 .bss
char DAT_00528aa8;  // 0x528aa8 .bss
char DAT_00528aac;  // 0x528aac .bss
void* DAT_00528ab0;  // 0x528ab0 .bss
char DAT_00528ad8;  // 0x528ad8 .bss
char DAT_00528adc;  // 0x528adc .bss
void* DAT_00528ae0;  // 0x528ae0 .bss
char DAT_00528ae4;  // 0x528ae4 .bss
char DAT_00528ae8[1000];  // 0x528ae8 .bss
char DAT_00528ed0[1000];  // 0x528ed0 .bss
unsigned char DAT_005292b8[4];  // 0x5292b8 .bss
unsigned char DAT_005292c8[8];  // 0x5292c8 .bss
unsigned char DAT_00529504[4];  // 0x529504 .bss
int DAT_00529508;  // 0x529508 .bss
unsigned char DAT_0052950c[4];  // 0x52950c .bss
int DAT_00529528;  // 0x529528 .bss
unsigned char DAT_0052952c[4];  // 0x52952c .bss
void* DAT_00529530;  // 0x529530 .bss
unsigned char DAT_00529534[4];  // 0x529534 .bss
int DAT_005295b8;  // 0x5295b8 .bss
void* DAT_005295bc;  // 0x5295bc .bss
int DAT_005295c0;  // 0x5295c0 .bss
unsigned char DAT_005295c4[4];  // 0x5295c4 .bss
int DAT_005295c8;  // 0x5295c8 .bss
char DAT_005295cc;  // 0x5295cc .bss
int DAT_005295d0;  // 0x5295d0 .bss
int DAT_005295d4;  // 0x5295d4 .bss
char DAT_005295d8[2000];  // 0x5295d8 .bss
unsigned char DAT_00529dc8;  // 0x529dc8 .bss
int DAT_00529dcc;  // 0x529dcc .bss
int DAT_00529dd0;  // 0x529dd0 .bss
unsigned char DAT_00529dd4;  // 0x529dd4 .bss
unsigned char DAT_00529dd8;  // 0x529dd8 .bss
unsigned char DAT_00529ddc;  // 0x529ddc .bss
unsigned char DAT_00529dfc[4];  // 0x529dfc .bss
char DAT_00529e20[56];  // 0x529e20 .bss
void* DAT_00529e58;  // 0x529e58 .bss
unsigned char DAT_00529e5c[8];  // 0x529e5c .bss
unsigned char DAT_00529e64;  // 0x529e64 .bss
unsigned char DAT_00529e6c;  // 0x529e6c .bss
unsigned char DAT_00529e70;  // 0x529e70 .bss
char DAT_00529e74;  // 0x529e74 .bss
char DAT_00529e78;  // 0x529e78 .bss
NameTable* DAT_00529e7c;  // 0x529e7c .bss
char* DAT_00529e80;  // 0x529e80 .bss
unsigned char DAT_00529e84[4];  // 0x529e84 .bss
char DAT_00529e88[13];  // 0x529e88 .bss
void* DAT_00529e98;  // 0x529e98 .bss
int DAT_00529ea0;  // 0x529ea0 .bss
unsigned char DAT_00529ea4[4];  // 0x529ea4 .bss
char DAT_0052a4e4;  // 0x52a4e4 .bss
long DAT_0052a4e8;  // 0x52a4e8 .bss
long DAT_0052a4ec;  // 0x52a4ec .bss
void* DAT_0052a4f0;  // 0x52a4f0 .bss
int DAT_0052a4f4;  // 0x52a4f4 .bss
void* DAT_0052a4f8;  // 0x52a4f8 .bss
long DAT_0052a4fc;  // 0x52a4fc .bss
