"""Link every object compiled from src/ into one executable.

    uv run tools/link.py                 # build build/link/TotalA.exe
    uv run tools/link.py --strict        # no /FORCE: report every error and stop
    uv run tools/link.py --verbose       # also list the symbols left unresolved

The tree is one function per file, so every caller declares its callees and the
game's globals with its own struct names and parameter types, and no file under
src/ defines the game's data at all. Linking therefore fails on spelling, not on
missing code. link.py bridges the spellings without changing any function:

  * every src/**/*.cpp is compiled through tools/progress.py's cache (the same
    objects check.py and linkcheck.py use);
  * link/data.cpp, generated by tools/globals.py, supplies the globals whose
    type is settled; every other global tools/globals.py left out is emitted as
    a byte array, so all 788 addresses the source refers to are defined;
  * a generated COFF object of weak externals, the mechanism OLDNAMES.LIB uses
    for its C runtime aliases, maps each caller's spelling of a function or
    global to the one name defined at that address, and each C++-mangled use of
    a C runtime function (tolower, sprintf, ...) to the library's symbol.

What is still unresolved after that is exactly what has no source yet or lives
outside the tree: the 29 gap regions, the game entry point, and the DLLs with
no import library in the toolchain (smackw32, DPLAYX). The default run passes
/FORCE:UNRESOLVED /FORCE:MULTIPLE so an image is still produced and reports
them; --strict does not, and fails the way a release build would.

This needs a LINK.EXE that can start; see tools/setup_toolchain.sh.
"""

import argparse
import csv
import hashlib
import re
import struct
import subprocess
import sys
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from check import DEFAULT_FLAGS, ROOT, winpath
from linkcheck import (CRT_LIBS, IMPORT_LIBS, address_of, base_name, include_hash, library_symbols,
                       load_known, read_object)

SRC = ROOT / "src"
BUILD = ROOT / "build/link"
GLOBALS = ROOT / "data/globals.csv"
DATA_CPP = ROOT / "link/data.cpp"

# (address, size, section, init-hex) for every global the source refers to.
GLOBAL_LO, GLOBAL_HI = 0x4FC000, 0x52D000

IMAGE_SYM_CLASS_EXTERNAL = 2
IMAGE_SYM_CLASS_WEAK_EXTERNAL = 105
IMAGE_WEAK_EXTERN_SEARCH_ALIAS = 3

LIBS = ("LIBCMT.LIB", "LIBCPMT.LIB", "OLDNAMES.LIB", "KERNEL32.LIB", "USER32.LIB", "GDI32.LIB",
        "ADVAPI32.LIB", "DDRAW.LIB", "DSOUND.LIB", "DPLAY.LIB", "SHELL32.LIB", "WINMM.LIB")


# --- compiling -----------------------------------------------------------------

def compile_all(jobs: int) -> tuple[list[Path], list[tuple[Path, str]]]:
    """Every source file's object, through tools/progress.py's cache."""
    from progress import compile_cached

    sources = sorted(SRC.rglob("*.cpp"))
    ihash = include_hash()

    def cached(src: Path) -> bool:
        key = hashlib.sha256(src.read_bytes() + ihash.encode() + DEFAULT_FLAGS.encode()).hexdigest()[:16]
        stamp = ROOT / "build/progress" / src.relative_to(SRC).with_suffix(".key")
        return stamp.exists() and stamp.read_text() == key and stamp.with_suffix(".obj").exists()

    stale = [s for s in sources if not cached(s)]
    if stale:
        print(f"compiling {len(stale)} file(s) not in build/progress ...", file=sys.stderr)
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        results = dict(zip(sources, pool.map(lambda s: compile_cached(s, ihash), sources)))
    objects, failed = [], []
    for src in sources:
        obj, log = results[src]
        if obj is None:
            failed.append((src, log))
        else:
            objects.append(obj)
    return objects, failed


# --- the generated global data --------------------------------------------------

def global_rows() -> dict[int, tuple[str, int, str, str]]:
    """address -> (name, size, section, init-hex) for every globals.csv row."""
    out = {}
    if not GLOBALS.exists():
        return out
    with GLOBALS.open() as fh:
        for r in csv.DictReader(fh):
            out[int(r["address"], 16)] = (f"DAT_{int(r['address'], 16):08x}", int(r["size"]),
                                          r["section"], r["init"])
    return out


def build_data(symbols: dict[str, int]) -> tuple[list[Path], dict[int, str]]:
    """Compile link/data.cpp, emit the globals it omits, and return the two
    objects with address -> the symbol each defines."""
    BUILD.mkdir(parents=True, exist_ok=True)
    compile_data = ROOT / "tools/wcl"
    objects = []
    by_addr: dict[int, str] = {}

    def compile_one(src: Path, out: Path) -> bool:
        cmd = [str(compile_data), "/c", *DEFAULT_FLAGS.split(), f"/I{winpath(ROOT / 'include')}",
               f"/Fo{winpath(out)}", winpath(src)]
        proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
        if proc.returncode != 0 or not out.exists():
            print((proc.stdout + proc.stderr).replace("\r", ""), file=sys.stderr)
            return False
        objects.append(out)
        return True

    if DATA_CPP.exists():
        out = BUILD / "data.obj"
        if not compile_one(DATA_CPP, out):
            raise SystemExit("link/data.cpp did not compile")
    else:
        out = None

    # Extra globals: those globals.csv lists but data.cpp leaves out.
    rows = global_rows()
    rows = {a: r for a, r in rows.items() if GLOBAL_LO <= a < GLOBAL_HI}
    have = defined_addresses(out, symbols) if out else set()
    extra = {a: r for a, r in rows.items() if a not in have}
    if extra:
        lines = ['extern "C" {']
        for addr in sorted(extra):
            _, size, section, init = extra[addr]
            name = f"DAT_{addr:08x}"
            bytes_ = bytes.fromhex(init) if init else b""
            if section == ".bss" or not bytes_:
                lines.append(f"unsigned char {name}[{max(size, 1)}];")
            else:
                body = ", ".join(f"0x{b:02x}" for b in bytes_)
                lines.append(f"unsigned char {name}[{max(size, 1)}] = {{ {body}{', 0' if size > len(bytes_) else ''} }};")
        lines.append("}")
        cpp = BUILD / "extra_data.cpp"
        cpp.write_text("\n".join(lines) + "\n")
        out = BUILD / "extra_data.obj"
        if not compile_one(cpp, out):
            raise SystemExit("the generated global data did not compile")

    for out in objects:
        for addr, sym in defined_addresses(out, symbols).items():
            by_addr[addr] = sym
    return objects, by_addr


def defined_addresses(obj: Path, symbols: dict[str, int]) -> dict[int, str]:
    """address -> the data symbol an object defines there (its exact COFF name)."""
    info = read_object(str(obj), obj.read_bytes())
    out: dict[int, str] = {}
    for name, d in info.defs.items():
        if d.code:
            continue
        addr = address_of(name, symbols)
        if addr is not None and GLOBAL_LO <= addr < GLOBAL_HI:
            out[addr] = name
    return out


# --- the weak-external aliases --------------------------------------------------

def build_aliases(objects: list[Path], symbols: dict[str, int],
                  data_addr: dict[int, str], libs: dict[str, str], out: Path) -> int:
    """Write the COFF object that maps caller spellings to definitions."""
    infos = [read_object(str(o), o.read_bytes()) for o in objects]
    defined = {n for info in infos for n in info.defs}
    funcs_at: dict[int, list[str]] = defaultdict(list)
    for info in infos:
        for name, d in info.defs.items():
            if d.code:
                a = address_of(name, symbols)
                if a is not None:
                    funcs_at[a].append(name)

    # A C name in a library for a caller that spelled it as C++ (tolower -> _tolower).
    lib_by_base: dict[str, str] = {}
    for n in libs:
        if not n.startswith("?"):
            lib_by_base.setdefault(base_name(n), n)

    aliases: dict[str, str] = {}
    for info in infos:
        for name, is_func in info.refs.items():
            if name in defined or name in aliases:
                continue
            addr = address_of(name, symbols)
            if is_func:
                targets = funcs_at.get(addr) if addr is not None else None
                if targets:
                    aliases[name] = prefer(targets)
                elif base_name(name) in lib_by_base and lib_by_base[base_name(name)] != name:
                    # A caller that spelled a C runtime function as C++ (?tolower@@ -> _tolower).
                    aliases[name] = lib_by_base[base_name(name)]
            elif addr is not None and addr in data_addr and data_addr[addr] != name:
                aliases[name] = data_addr[addr]
    write_object(aliases, out)
    return len(aliases)


def prefer(names: list[str]) -> str:
    """A real symbols.csv name over a FUN_/DAT_ placeholder."""
    real = [n for n in names if not re.match(r"^(FUN|DAT|PTR|LAB)_[0-9a-f]{8}$", base_name(n))]
    return sorted(real or names)[0]


def write_object(aliases: dict[str, str], out: Path) -> None:
    strings = bytearray()
    str_index: dict[str, int] = {}

    def name_field(name: str) -> bytes:
        raw = name.encode("latin-1")
        if len(raw) <= 8:
            return raw + b"\0" * (8 - len(raw))
        if name not in str_index:
            str_index[name] = 4 + len(strings)
            strings.extend(raw + b"\0")
        return b"\0\0\0\0" + struct.pack("<I", str_index[name])

    syms = bytearray()
    index = 0
    for alias, target in aliases.items():
        syms += name_field(target) + struct.pack("<IhHBB", 0, 0, 0x20, IMAGE_SYM_CLASS_EXTERNAL, 0)
        index += 1
        syms += name_field(alias) + struct.pack("<IhHBB", 0, 0, 0x20, IMAGE_SYM_CLASS_WEAK_EXTERNAL, 1)
        index += 1
        syms += struct.pack("<II", index - 2, IMAGE_WEAK_EXTERN_SEARCH_ALIAS) + b"\0" * 10
        index += 1

    strtab = struct.pack("<I", 4 + len(strings)) + bytes(strings)
    nsects, symptr, nsyms = 1, 20 + 40, index
    header = struct.pack("<HHIIIHH", 0x14C, nsects, 0, symptr, nsyms, 0, 0)
    section = b"aliases\0" + struct.pack("<IIIIIIHHI", 0, 0, 0, 0, 0, 0, 0, 0, 0x40000040)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(header + section + bytes(syms) + strtab)


# --- linking --------------------------------------------------------------------

def link(objects: list[Path], strict: bool, output: Path, verbose: bool) -> int:
    BUILD.mkdir(parents=True, exist_ok=True)
    rsp = BUILD / "objects.rsp"
    rsp.write_text("\n".join(winpath(o) for o in objects) + "\n")
    cmd = [str(ROOT / "tools/wlink"), "/nologo", "/OPT:NOREF", "/INCREMENTAL:NO",
           "/SUBSYSTEM:WINDOWS", f"/OUT:{winpath(output)}", f"@{winpath(rsp)}", *LIBS]
    if not strict:
        cmd[2:2] = ["/FORCE:UNRESOLVED", "/FORCE:MULTIPLE"]
    print(f"linking {len(objects):,} objects -> {output.relative_to(ROOT)}", file=sys.stderr)
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    log = (proc.stdout + proc.stderr).replace("\r", "")
    BUILD.mkdir(parents=True, exist_ok=True)
    (BUILD / "link.log").write_text(log)
    report(log, verbose)
    return proc.returncode


def report(log: str, verbose: bool) -> None:
    errors = re.findall(r"error (LNK\d+): (.*)", log)
    counts = Counter(code for code, _ in errors)
    duplicates = [line for line in log.splitlines() if "warning LNK4006" in line]
    unresolved = [msg for code, msg in errors if code == "LNK2001"]
    print(f"LINK: {len(errors):,} errors, {len(duplicates):,} duplicate warnings "
          f"({', '.join(f'{c} {n:,}' for c, n in counts.most_common()) or 'none'})")
    if unresolved:
        print(f"  {len(set(unresolved)):,} distinct unresolved symbols, e.g.:")
        for msg in sorted(set(unresolved))[:10 if not verbose else len(set(unresolved))]:
            print("   ", msg)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--strict", action="store_true", help="no /FORCE: do not emit an image with errors")
    ap.add_argument("--output", type=Path, default=BUILD / "TotalA.exe")
    ap.add_argument("--jobs", type=int, default=None, help="parallel compiles (default: all cores)")
    ap.add_argument("--verbose", "-v", action="store_true")
    args = ap.parse_args()

    objects, failed = compile_all(args.jobs)
    if failed:
        for src, log in failed:
            print(f"{src}: {log}", file=sys.stderr)
        raise SystemExit(f"{len(failed)} file(s) did not compile")
    symbols, _, _ = load_known()
    data_objs, data_addr = build_data(symbols)
    libs = library_symbols(set(CRT_LIBS) | set(IMPORT_LIBS))
    aliases = BUILD / "aliases.obj"
    n = build_aliases(objects, symbols, data_addr, libs, aliases)
    print(f"{len(objects):,} objects, {n:,} aliases, {len(data_addr):,} globals at known addresses")
    rc = link(objects + data_objs + [aliases], args.strict, args.output, args.verbose)
    if rc == 0 and args.output.exists():
        print(f"{args.output.relative_to(ROOT)}: {args.output.stat().st_size:,} bytes")
    raise SystemExit(rc)


if __name__ == "__main__":
    main()
