"""Link every object compiled from src/ into one executable.

    uv run tools/link.py                 # build build/link/TotalA.exe
    uv run tools/link.py --strict        # no /FORCE:UNRESOLVED; generate stubs so it succeeds
    uv run tools/link.py --stub          # the same, naming the generated stubs explicitly
    uv run tools/link.py --carve         # link the gap regions and the original's data carved
                                         # out of the exe (tools/carve.py): an image that runs
    uv run tools/link.py --verbose       # also list the symbols left unresolved

The tree is one function per file, so every caller declares its callees and the
game's globals with its own struct names and parameter types, and no file under
src/ defines the game's data at all. Linking therefore fails on spelling, not on
missing code. link.py bridges the spellings without changing any function:

  * every src/**/*.cpp is compiled through tools/progress.py's cache (the same
    objects check.py and linkcheck.py use);
  * link/data.cpp, generated by tools/globals.py, supplies the globals whose
    type is settled; every other global tools/globals.py left out is emitted as
    a byte array, so all 788 addresses the source refers to are defined;
  * a generated COFF object of weak externals, the mechanism OLDNAMES.LIB uses
    for its C runtime aliases, maps each caller's spelling of a function or
    global to the one name defined at that address, and each C++-mangled use of
    a C runtime function (tolower, sprintf, ...) to the library's symbol.

What is still unresolved after that is exactly what has no source yet or lives
outside the tree: the gap regions with no matching source in src/gap/ (those
with it are linked from their objects, tools/gapcheck.py), the game entry
point, and the DLLs with no import library in the toolchain (smackw32,
DPLAYX). The default run passes
/FORCE:UNRESOLVED /FORCE:MULTIPLE so an image is still produced and reports
them.

--stub (and --strict, which implies it for the current tree) is the deliberate
mode that turns those into a strictly linked image, with every generated file
under build/link/:

  * build/link/{SMACKW32,DPLAYX}.LIB, generated from the original's import
    table with LIB.EXE, resolve the DLLs the toolchain has no import library
    for;
  * the game's entry point: the original's WinMainCRTStartup calls the game's
    WinMain at 0x49eda0, a gap region; the matched function it tail-calls,
    FUN_0049e830, has WinMain's exact signature, so _WinMain@16 is aliased to
    it;
  * build/link/stubs.obj defines every remaining unresolved name: a ret stub
    (stack-cleaning for __stdcall/__thiscall where the argument bytes are
    known) for a function, a zero array for data. Stubbed output is labelled
    "stub" everywhere it appears.
  * /FORCE:MULTIPLE stays: 95 duplicate definitions are known copies kept in
    callers' files so they inline (docs/consolidation.md), not missing code.

This needs a LINK.EXE and LIB.EXE that can start; see tools/setup_toolchain.sh.
"""

import argparse
import csv
import hashlib
import re
import struct
import subprocess
import sys
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from check import DEFAULT_FLAGS, GAP_DIR, ROOT, winpath
from linkcheck import (CRT_LIBS, IMPORT_LIBS, Demangle, MEMBER_STATIC, address_of,
                       archive_symbols, base_name, data_symbol, include_hash, library_symbols,
                       load_known, read_object, type_size)

SRC = ROOT / "src"
BUILD = ROOT / "build/link"
GLOBALS = ROOT / "data/globals.csv"
DATA_CPP = ROOT / "link/data.cpp"

# (address, size, section, init-hex) for every global the source refers to.
GLOBAL_LO, GLOBAL_HI = 0x4FC000, 0x52D000

IMAGE_SYM_CLASS_EXTERNAL = 2
IMAGE_SYM_CLASS_WEAK_EXTERNAL = 105
IMAGE_WEAK_EXTERN_SEARCH_ALIAS = 3

LIBS = ("LIBCMT.LIB", "LIBCPMT.LIB", "OLDNAMES.LIB", "KERNEL32.LIB", "USER32.LIB", "GDI32.LIB",
        "ADVAPI32.LIB", "DDRAW.LIB", "DSOUND.LIB", "DPLAY.LIB", "SHELL32.LIB", "WINMM.LIB")

# The exports the game uses from the two DLLs the toolchain has no import
# library for. Each is (C name, argument bytes, ordinal); the ordinals are the
# original import table's, and the names come from the matched callers that
# use them. smackw32 is imported by ordinal only.
SMACKW32_EXPORTS = [
    ("SmackNextFrame", 4, 21), ("SmackDoFrame", 4, 19), ("SmackToBuffer", 28, 23),
    ("SmackSummary", 8, 20), ("SmackGoto", 8, 27), ("SmackToBufferRect", 8, 28),
    ("SmackClose", 4, 18), ("SmackSoundEnable", 4, 15), ("SmackSoundUseDirectSound", 4, 38),
    ("SmackOpen", 12, 14), ("SmackSoundOnOff", 8, 17), ("DAT_004fc40c", 4, 32),
    ("DAT_004fc410", 24, 2), ("DAT_004fc414", 12, 5), ("DAT_004fc418", 16, 25),
]
DPLAYX_EXPORTS = [("DirectPlayEnumerateA", 8, 2), ("DirectPlayLobbyCreateA", 20, 4)]

# The original's WinMainCRTStartup (0x4e6fa0) calls the game's WinMain at
# 0x49eda0, a 1942-byte gap region that immediately forwards its four
# arguments to FUN_0049e830 and returns. FUN_0049e830 is a matched function
# with WinMain's signature, so the bridge goes there.
WINMAIN_ADDR = 0x49E830


# --- compiling -----------------------------------------------------------------

def compile_all(jobs: int) -> tuple[list[Path], list[tuple[Path, str]]]:
    """Every source file's object, through tools/progress.py's cache. The gap
    regions' sources (src/gap/) are left out: tools/gapcheck.py's gap_objects
    gives the builds those whose source matches."""
    from progress import compile_cached

    sources = sorted(s for s in SRC.rglob("*.cpp") if not s.is_relative_to(GAP_DIR))
    ihash = include_hash()

    def cached(src: Path) -> bool:
        key = hashlib.sha256(src.read_bytes() + ihash.encode() + DEFAULT_FLAGS.encode()).hexdigest()[:16]
        stamp = ROOT / "build/progress" / src.relative_to(SRC).with_suffix(".key")
        return stamp.exists() and stamp.read_text() == key and stamp.with_suffix(".obj").exists()

    stale = [s for s in sources if not cached(s)]
    if stale:
        print(f"compiling {len(stale)} file(s) not in build/progress ...", file=sys.stderr)
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        results = dict(zip(sources, pool.map(lambda s: compile_cached(s, ihash), sources)))
    objects, failed = [], []
    for src in sources:
        obj, log = results[src]
        if obj is None:
            failed.append((src, log))
        else:
            objects.append(obj)
    return objects, failed


# --- the generated global data --------------------------------------------------

def global_rows() -> dict[int, tuple[str, int, str, str]]:
    """address -> (name, size, section, init-hex) for every globals.csv row."""
    out = {}
    if not GLOBALS.exists():
        return out
    with GLOBALS.open() as fh:
        for r in csv.DictReader(fh):
            out[int(r["address"], 16)] = (f"DAT_{int(r['address'], 16):08x}", int(r["size"]),
                                          r["section"], r["init"])
    return out


def build_data(symbols: dict[str, int]) -> tuple[list[Path], dict[int, str]]:
    """Compile link/data.cpp, emit the globals it omits, and return the two
    objects with address -> the symbol each defines."""
    BUILD.mkdir(parents=True, exist_ok=True)
    compile_data = ROOT / "tools/wcl"
    objects = []
    by_addr: dict[int, str] = {}

    def compile_one(src: Path, out: Path) -> bool:
        cmd = [str(compile_data), "/c", *DEFAULT_FLAGS.split(), f"/I{winpath(ROOT / 'include')}",
               f"/Fo{winpath(out)}", winpath(src)]
        proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
        if proc.returncode != 0 or not out.exists():
            print((proc.stdout + proc.stderr).replace("\r", ""), file=sys.stderr)
            return False
        objects.append(out)
        return True

    if DATA_CPP.exists():
        out = BUILD / "data.obj"
        if not compile_one(DATA_CPP, out):
            raise SystemExit("link/data.cpp did not compile")
    else:
        out = None

    # Extra globals: those globals.csv lists but data.cpp leaves out.
    rows = global_rows()
    rows = {a: r for a, r in rows.items() if GLOBAL_LO <= a < GLOBAL_HI}
    have = defined_addresses(out, symbols) if out else set()
    extra = {a: r for a, r in rows.items() if a not in have}
    if extra:
        lines = ['extern "C" {']
        for addr in sorted(extra):
            _, size, section, init = extra[addr]
            name = f"DAT_{addr:08x}"
            bytes_ = bytes.fromhex(init) if init else b""
            if section == ".bss" or not bytes_:
                lines.append(f"unsigned char {name}[{max(size, 1)}];")
            else:
                body = ", ".join(f"0x{b:02x}" for b in bytes_)
                lines.append(f"unsigned char {name}[{max(size, 1)}] = {{ {body}{', 0' if size > len(bytes_) else ''} }};")
        lines.append("}")
        cpp = BUILD / "extra_data.cpp"
        cpp.write_text("\n".join(lines) + "\n")
        out = BUILD / "extra_data.obj"
        if not compile_one(cpp, out):
            raise SystemExit("the generated global data did not compile")

    for out in objects:
        for addr, sym in defined_addresses(out, symbols).items():
            by_addr[addr] = sym
    return objects, by_addr


def defined_addresses(obj: Path, symbols: dict[str, int]) -> dict[int, str]:
    """address -> the data symbol an object defines there (its exact COFF name)."""
    info = read_object(str(obj), obj.read_bytes())
    out: dict[int, str] = {}
    for name, d in info.defs.items():
        if d.code:
            continue
        addr = address_of(name, symbols)
        if addr is not None and GLOBAL_LO <= addr < GLOBAL_HI:
            out[addr] = name
    return out


# --- the weak-external aliases --------------------------------------------------

def leaf_address(name: str, symbols: dict[str, int]) -> int | None:
    """The address of a namespaced global whose leaf name is in symbols.csv:
    `?g_game@Build@@3PAUGame@1@A` -> symbols['g_game']. The type differs, so
    the mangled spelling is not in symbols.csv, but the address is the same
    global and the weak external only cares about the name."""
    if not name.startswith("?"):
        return None
    return symbols.get(name[1:].split("@", 1)[0])


def build_aliases(objects: list[Path], symbols: dict[str, int], data_addr: dict[int, str],
                  libs: dict[str, str], out: Path, extra: dict[str, str] | None = None,
                  winmain_addr: int | None = None, data_fallback: bool = False) -> dict[str, str]:
    """Write the COFF object that maps caller spellings to definitions."""
    infos = [read_object(str(o), o.read_bytes()) for o in objects]
    defined = {n for info in infos for n in info.defs}
    funcs_at: dict[int, list[str]] = defaultdict(list)
    for info in infos:
        for name, d in info.defs.items():
            if d.code:
                a = address_of(name, symbols)
                if a is not None:
                    funcs_at[a].append(name)

    # A C name in a library for a caller that spelled it as C++ (tolower -> _tolower).
    lib_by_base: dict[str, str] = {}
    for n in libs:
        if not n.startswith("?"):
            lib_by_base.setdefault(base_name(n), n)

    aliases: dict[str, str] = dict(extra or {})
    if winmain_addr is not None and funcs_at.get(winmain_addr) and "_WinMain@16" not in defined:
        aliases.setdefault("_WinMain@16", prefer(funcs_at[winmain_addr]))
    for info in infos:
        for name, is_func in info.refs.items():
            if name in defined or name in aliases or name in libs:
                continue
            addr = address_of(name, symbols)
            if is_func:
                targets = funcs_at.get(addr) if addr is not None else None
                if targets:
                    aliases[name] = prefer(targets)
                elif base_name(name) in lib_by_base and lib_by_base[base_name(name)] != name:
                    # A caller that spelled a C runtime function as C++ (?tolower@@ -> _tolower).
                    aliases[name] = lib_by_base[base_name(name)]
            else:
                if addr is None and data_fallback:
                    addr = leaf_address(name, symbols)
                if addr is not None and addr in data_addr and data_addr[addr] != name:
                    aliases[name] = data_addr[addr]
    write_object(aliases, out)
    return aliases


def prefer(names: list[str]) -> str:
    """A real symbols.csv name over a FUN_/DAT_ placeholder."""
    real = [n for n in names if not re.match(r"^(FUN|DAT|PTR|LAB)_[0-9a-f]{8}$", base_name(n))]
    return sorted(real or names)[0]


def write_object(aliases: dict[str, str], out: Path) -> None:
    strings = bytearray()
    str_index: dict[str, int] = {}

    def name_field(name: str) -> bytes:
        raw = name.encode("latin-1")
        if len(raw) <= 8:
            return raw + b"\0" * (8 - len(raw))
        if name not in str_index:
            str_index[name] = 4 + len(strings)
            strings.extend(raw + b"\0")
        return b"\0\0\0\0" + struct.pack("<I", str_index[name])

    syms = bytearray()
    index = 0
    for alias, target in aliases.items():
        syms += name_field(target) + struct.pack("<IhHBB", 0, 0, 0x20, IMAGE_SYM_CLASS_EXTERNAL, 0)
        index += 1
        syms += name_field(alias) + struct.pack("<IhHBB", 0, 0, 0x20, IMAGE_SYM_CLASS_WEAK_EXTERNAL, 1)
        index += 1
        syms += struct.pack("<II", index - 2, IMAGE_WEAK_EXTERN_SEARCH_ALIAS) + b"\0" * 10
        index += 1

    strtab = struct.pack("<I", 4 + len(strings)) + bytes(strings)
    nsects, symptr, nsyms = 1, 20 + 40, index
    header = struct.pack("<HHIIIHH", 0x14C, nsects, 0, symptr, nsyms, 0, 0)
    section = b"aliases\0" + struct.pack("<IIIIIIHHI", 0, 0, 0, 0, 0, 0, 0, 0, 0x40000040)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(header + section + bytes(syms) + strtab)


# --- the missing import libraries -----------------------------------------------

def build_import_libs() -> list[Path]:
    """Build SMACKW32.LIB and DPLAYX.LIB from .def files with LIB.EXE."""
    out = []
    for name, exports in (("SMACKW32", SMACKW32_EXPORTS), ("DPLAYX", DPLAYX_EXPORTS)):
        def_ = BUILD / f"{name}.def"
        lib = BUILD / f"{name}.LIB"
        lines = [f"LIBRARY {name}", "EXPORTS"]
        for cname, argbytes, ordinal in exports:
            lines.append(f"    {cname}@{argbytes} @{ordinal}")
        def_.write_text("\n".join(lines) + "\n")
        proc = subprocess.run([str(ROOT / "tools/wlib"), f"/def:{winpath(def_)}", f"/out:{winpath(lib)}"],
                              capture_output=True, text=True, cwd=ROOT)
        if proc.returncode != 0 or not lib.exists():
            raise SystemExit(f"could not build {lib.name}:\n{proc.stdout}{proc.stderr}")
        out.append(lib)
    return out


STUB_ARG_SIZES = sorted({ab for _, ab, _ in SMACKW32_EXPORTS + DPLAYX_EXPORTS})


def build_stub_dll(directory: Path) -> Path:
    """Build a no-op SMACKW32.dll next to the exe. The real Smacker decoder
    ships with the game; without it the loader stops before any game code
    runs, so the stub lets the image reach an honest failure instead."""
    c = BUILD / "smackw32_stub.c"
    lines = ["// Generated by tools/link.py --stub. A no-op stand-in for the",
             "// Smacker decoder the game ships; it exists so the linked image loads.",
             ""]
    for ab in STUB_ARG_SIZES:
        params = ", ".join(f"int a{i}" for i in range(ab // 4)) or "void"
        lines.append(f"void __stdcall stub{ab}({params}) {{}}")
    c.write_text("\n".join(lines) + "\n")

    obj = BUILD / "smackw32_stub.obj"
    proc = subprocess.run([str(ROOT / "tools/wcl"), "/c", "/O2", "/MT",
                           f"/Fo{winpath(obj)}", winpath(c)],
                          capture_output=True, text=True, cwd=ROOT)
    if proc.returncode != 0 or not obj.exists():
        raise SystemExit(f"the smackw32 stub did not compile:\n{proc.stdout}{proc.stderr}")

    def_ = BUILD / "smackw32_stub.def"
    lines = ["LIBRARY SMACKW32", "EXPORTS"]
    for cname, argbytes, ordinal in SMACKW32_EXPORTS:
        lines.append(f"    {cname}@{argbytes}=_stub{argbytes}@{argbytes} @{ordinal}")
    def_.write_text("\n".join(lines) + "\n")

    dll = directory / "SMACKW32.DLL"
    proc = subprocess.run([str(ROOT / "tools/wlink"), "/DLL", "/nologo", f"/OUT:{winpath(dll)}",
                           winpath(obj), f"/def:{winpath(def_)}"],
                          capture_output=True, text=True, cwd=ROOT)
    if proc.returncode != 0 or not dll.exists():
        raise SystemExit(f"the smackw32 stub did not link:\n{proc.stdout}{proc.stderr}")
    return dll


# --- the C++ static initialisers ---------------------------------------------------

IMAGE_SCN_LNK_REMOVE = 0x800
EXE = ROOT / "orig/TotalA.exe"
PROGRESS = ROOT / "data/progress.csv"
FUNCTIONS = ROOT / "data/functions.csv"


def original_initialisers() -> list[int]:
    """The functions the original's C runtime calls before WinMain to construct
    its global objects: the entries of its __xc_a..__xc_z table, which the
    runtime's _cinit passes to _initterm (the second pair of pushes)."""
    import pefile
    pe = pefile.PE(str(EXE))
    base = pe.OPTIONAL_HEADER.ImageBase
    with FUNCTIONS.open() as fh:
        cinit = next(int(r["address"], 16) for r in csv.DictReader(fh) if r["name"] == "__cinit")
    code = pe.get_data(cinit - base, 64)
    pushes = [struct.unpack_from("<I", code, i + 1)[0] for i in range(len(code) - 5) if code[i] == 0x68]
    xc_a, xc_z = pushes[3], pushes[2]
    out = []
    for at in range(xc_a, xc_z, 4):
        (fn,) = struct.unpack("<I", pe.get_data(at - base, 4))
        if fn:
            out.append(fn)
    return out


def fix_initialisers(objects: list[Path]) -> list[Path]:
    """Make the image construct exactly the global objects the original does.

    A file that defines a global object only so that a function matches (the
    global's constructor is called from a static initialiser the compiler
    emits, `_$E<n>`) adds that initialiser to every link, although the
    original never calls it: its constructor may be another function, or
    take arguments the placeholder declaration leaves out (0x462cc0.cpp's
    `_$E4` calls Class_00462d30's constructor with none, and the one at its
    address pops one). So every object's .CRT$XCU sections are dropped except
    the initialisers the original's table holds, and the original's
    initialisers that the tree spells as ordinary functions (FUN_004205f0) get
    a table entry of their own, in the original's order."""
    with PROGRESS.open() as fh:
        rows = {int(r["address"], 16): (r["file"], r["symbol"]) for r in csv.DictReader(fh)}
    wanted: dict[str, list[str]] = defaultdict(list)     # source file -> initialiser symbols
    for fn in original_initialisers():
        if fn in rows:
            wanted[rows[fn][0]].append(rows[fn][1])
    out_dir = BUILD / "objs"
    out_dir.mkdir(parents=True, exist_ok=True)
    result: list[Path] = []
    kept = removed = added = 0
    for obj in objects:
        src = str(Path("src") / obj.relative_to(ROOT / "build/progress").with_suffix(".cpp"))
        data = bytearray(obj.read_bytes())
        _, nsects, _, symptr, nsyms, opthdr, _ = struct.unpack_from("<HHIIIHH", data, 0)
        strtab = bytes(data[symptr + nsyms * 18:])
        names = {}
        i = 0
        while i < nsyms:
            raw = data[symptr + i * 18: symptr + i * 18 + 18]
            if raw[:4] == b"\0\0\0\0":
                off = struct.unpack_from("<I", raw, 4)[0]
                names[i] = strtab[off:strtab.index(b"\0", off)].decode("latin-1")
            else:
                names[i] = bytes(raw[:8]).split(b"\0", 1)[0].decode("latin-1")
            i += 1 + raw[17]
        changed = False
        for sidx in range(nsects):
            hdr = 20 + opthdr + sidx * 40
            if bytes(data[hdr:hdr + 8]).rstrip(b"\0") != b".CRT$XCU":
                continue
            relptr, nrel = struct.unpack_from("<I", data, hdr + 24)[0], struct.unpack_from("<H", data, hdr + 32)[0]
            targets = [names.get(struct.unpack_from("<I", data, relptr + r * 10 + 4)[0]) for r in range(nrel)]
            if any(t in wanted.get(src, ()) for t in targets):
                kept += 1
                continue
            chars = struct.unpack_from("<I", data, hdr + 36)[0]
            struct.pack_into("<I", data, hdr + 36, chars | IMAGE_SCN_LNK_REMOVE)
            removed += 1
            changed = True
        if changed:
            patched = out_dir / obj.name
            patched.write_bytes(bytes(data))
            result.append(patched)
        else:
            result.append(obj)
        # The original's initialisers the tree spells as ordinary functions.
        for sym in wanted.get(src, ()):
            if not sym.startswith("_$E"):
                entry = out_dir / f"{obj.stem}_init.obj"
                write_init_object(sym, entry)
                result.append(entry)
                added += 1
    print(f"static initialisers: {kept + added} as in the original ({kept} from the objects, {added} added), "
          f"{removed} dropped", file=sys.stderr)
    return result


def write_init_object(symbol: str, out: Path) -> None:
    """A COFF object whose .CRT$XCU section holds one pointer to symbol."""
    strings = bytearray()

    def name_field(name: str) -> bytes:
        raw = name.encode("latin-1")
        if len(raw) <= 8:
            return raw + b"\0" * (8 - len(raw))
        off = 4 + len(strings)
        strings.extend(raw + b"\0")
        return b"\0\0\0\0" + struct.pack("<I", off)

    raw_off = 20 + 40
    reloc_off = raw_off + 4
    sym_off = reloc_off + 10
    header = struct.pack("<HHIIIHH", 0x14C, 1, 0, sym_off, 2, 0, 0)
    section = b".CRT$XCU" + struct.pack("<IIIIIIHHI", 0, 0, 4, raw_off, reloc_off, 0, 1, 0, 0xC0300040)
    reloc = struct.pack("<IIH", 0, 1, 0x06)       # DIR32 against symbol 1
    syms = name_field(".CRT$XCU") + struct.pack("<IhHBB", 0, 1, 0, 3, 0)
    syms += name_field(symbol) + struct.pack("<IhHBB", 0, 0, 0x20, IMAGE_SYM_CLASS_EXTERNAL, 0)
    strtab = struct.pack("<I", 4 + len(strings)) + bytes(strings)
    out.write_bytes(header + section + b"\0\0\0\0" + reloc + syms + strtab)


# --- the stubs ------------------------------------------------------------------

def stub_cleanup_bytes(name: str) -> int | None:
    """The bytes a __stdcall/__thiscall stub must pop, 0 for __cdecl and
    __fastcall, or None when the argument size cannot be read from the name."""
    m = re.search(r"@(\d+)$", name)
    if m:
        return int(m.group(1))
    if not name.startswith("?"):
        return 0
    try:
        d = Demangle(name[1:])
        if d.s.startswith("?"):
            d.i = 1
            code = d.take()
            if code == "_":
                code += d.take()
            if code == "$":
                return None
            if d.s[d.i] != "@":
                d.qualified()
            if d.s[d.i] == "@":
                d.i += 1
        else:
            d.qualified()
        access = d.take()
        if access in "YZ":
            kind = "global"
        elif access in MEMBER_STATIC:
            kind = "static"
        else:
            kind = "member"
            d.take()  # the this-pointer's cv
        cc = d.take()
        if d.s[d.i] == "@":
            d.i += 1
        else:
            if d.s.startswith("?A", d.i):
                d.i += 2
            d.type()
        args = []
        while d.i < len(d.s) and d.s[d.i] not in "@Z":
            if d.s[d.i] == "X" and not args:
                d.i += 1
                break
            args.append(d.arg())
        sizes = [type_size(a) for a in args]
        if any(s is None for s in sizes):
            return None
        # Every stack argument occupies at least a dword on x86.
        total = sum((s + 3) & ~3 for s in sizes)
        if kind == "member" and cc == "G":
            # A __stdcall member takes `this` on the stack; __thiscall passes it
            # in ecx, so a stub that popped it too would unbalance the caller.
            total += 4
        if cc in ("G", "E"):
            return total
        return 0
    except (ValueError, IndexError, KeyError):
        return None


def stub_bytes(name: str) -> bytes:
    """`xor eax, eax` then a return, cleaning the stack for callee-cleans."""
    cleanup = stub_cleanup_bytes(name)
    if cleanup:
        return b"\x31\xc0\xc2" + struct.pack("<H", cleanup)
    return b"\x31\xc0\xc3"


def stub_data_size(name: str) -> int:
    _, t = data_symbol(name)
    size = type_size(t)
    return size if size and size > 0 else 4


def write_stub_object(funcs: list[str], data: list[str], out: Path) -> None:
    """A COFF object defining each name: a ret stub in .text, a zero array in
    .data. Written by hand so any mangled spelling can be defined."""
    strings = bytearray()
    str_index: dict[str, int] = {}

    def name_field(name: str) -> bytes:
        raw = name.encode("latin-1")
        if len(raw) <= 8:
            return raw + b"\0" * (8 - len(raw))
        if name not in str_index:
            str_index[name] = 4 + len(strings)
            strings.extend(raw + b"\0")
        return b"\0\0\0\0" + struct.pack("<I", str_index[name])

    text = bytearray()
    text_defs: list[tuple[str, int]] = []
    for name in sorted(funcs):
        text_defs.append((name, len(text)))
        text.extend(stub_bytes(name))
    dat = bytearray()
    data_defs: list[tuple[str, int]] = []
    for name in sorted(data):
        data_defs.append((name, len(dat)))
        dat.extend(b"\0" * stub_data_size(name))

    sections = []
    if text_defs:
        sections.append((b".text\0\0\0", bytes(text), 0x60500020, text_defs, 0x20))
    if data_defs:
        sections.append((b".data\0\0\0", bytes(dat), 0xC0000040, data_defs, 0x00))

    hdr_size = 20 + 40 * len(sections)
    raw_off = hdr_size
    section_headers = bytearray()
    raws = bytearray()
    for sname, raw, chars, _, _ in sections:
        section_headers += sname + struct.pack("<IIIIIIHHI", 0, 0, len(raw), raw_off, 0, 0, 0, 0, chars)
        raws += raw
        raw_off += len(raw)
    nsyms = sum(len(defs) for *_, defs, _ in sections)
    symptr = raw_off

    symtab = bytearray()
    for sec_index, (_, _, _, defs, symtype) in enumerate(sections, start=1):
        for name, value in defs:
            symtab += name_field(name) + struct.pack("<IhHBB", value, sec_index, symtype,
                                                     IMAGE_SYM_CLASS_EXTERNAL, 0)
    strtab = struct.pack("<I", 4 + len(strings)) + bytes(strings)
    header = struct.pack("<HHIIIHH", 0x14C, len(sections), 0, symptr, nsyms, 0, 0)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(header + bytes(section_headers) + bytes(raws) + bytes(symtab) + strtab)


def unresolved_names(objects: list[Path], alias_keys: set[str], libs: dict[str, str]) -> dict[str, bool]:
    """The names LINK would still report LNK2001 for: referenced by some
    object, defined by none, not aliased and not in a library."""
    defined: set[str] = set()
    refs: dict[str, bool] = {}
    for obj in objects:
        info = read_object(str(obj), obj.read_bytes())
        defined |= set(info.defs)
        for name, is_func in info.refs.items():
            refs[name] = refs.get(name, False) or is_func
    return {n: f for n, f in refs.items()
            if n not in defined and n not in alias_keys and n not in libs}


# --- linking --------------------------------------------------------------------

def link(objects: list[Path], output: Path, verbose: bool, force_unresolved: bool,
         map_path: Path | None = None) -> int:
    BUILD.mkdir(parents=True, exist_ok=True)
    rsp = BUILD / "objects.rsp"
    rsp.write_text("\n".join(winpath(o) for o in objects) + "\n")
    cmd = [str(ROOT / "tools/wlink"), "/nologo", "/OPT:NOREF", "/INCREMENTAL:NO",
           "/SUBSYSTEM:WINDOWS", f"/OUT:{winpath(output)}", f"@{winpath(rsp)}", *LIBS]
    if map_path is not None:
        cmd.insert(2, f"/MAP:{winpath(map_path)}")
    if force_unresolved:
        cmd[2:2] = ["/FORCE:UNRESOLVED", "/FORCE:MULTIPLE"]
    else:
        # The tree has 95 known duplicate copies kept in callers' files so they
        # inline (docs/consolidation.md); they are not missing code, so they are
        # folded. Every external must resolve, which is what this mode checks.
        cmd[2:2] = ["/FORCE:MULTIPLE"]
    print(f"linking {len(objects):,} objects -> {output.relative_to(ROOT)}", file=sys.stderr)
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    log = (proc.stdout + proc.stderr).replace("\r", "")
    BUILD.mkdir(parents=True, exist_ok=True)
    (BUILD / "link.log").write_text(log)
    report(log, verbose)
    return proc.returncode


def report(log: str, verbose: bool) -> None:
    errors = re.findall(r"error (LNK\d+): (.*)", log)
    counts = Counter(code for code, _ in errors)
    duplicates = [line for line in log.splitlines() if "warning LNK4006" in line]
    unresolved = [msg for code, msg in errors if code == "LNK2001"]
    print(f"LINK: {len(errors):,} errors, {len(duplicates):,} duplicate warnings "
          f"({', '.join(f'{c} {n:,}' for c, n in counts.most_common()) or 'none'})")
    if unresolved:
        print(f"  {len(set(unresolved)):,} distinct unresolved symbols, e.g.:")
        for msg in sorted(set(unresolved))[:10 if not verbose else len(set(unresolved))]:
            print("   ", msg)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--strict", action="store_true",
                    help="no /FORCE:UNRESOLVED; generate the missing stubs and import libraries")
    ap.add_argument("--stub", action="store_true",
                    help="the same as --strict, naming the generated stubs explicitly")
    ap.add_argument("--carve", action="store_true",
                    help="link the gap regions and the original's data carved from the exe "
                         "(tools/carve.py) instead of stubs and link/data.cpp; implies --stub")
    ap.add_argument("--output", type=Path, default=BUILD / "TotalA.exe")
    ap.add_argument("--map", action="store_true", help="also write build/link/TotalA.map")
    ap.add_argument("--jobs", type=int, default=None, help="parallel compiles (default: all cores)")
    ap.add_argument("--verbose", "-v", action="store_true")
    args = ap.parse_args()

    output = args.output if args.output.is_absolute() else ROOT / args.output
    stub_mode = args.strict or args.stub or args.carve

    objects, failed = compile_all(args.jobs)
    if failed:
        for src, log in failed:
            print(f"{src}: {log}", file=sys.stderr)
        raise SystemExit(f"{len(failed)} file(s) did not compile")
    symbols, _, _ = load_known()
    carved: list[Path] = []
    extra: dict[str, str] = {}
    if args.carve:
        from carve import THIRD_PARTY_OBJS, carve, library_aliases
        result = carve(objects)
        carved, data_addr = result.objects, result.data_names
        gaps = result.gap_sources
        data_objs = list(THIRD_PARTY_OBJS)       # zlib, which the original links too
        extra = library_aliases(objects + gaps, symbols, result)
    else:
        from gapcheck import gap_objects
        gaps = [g.path for _, g in sorted(gap_objects().items())]
        data_objs, data_addr = build_data(symbols)
    if gaps:
        print(f"{len(gaps)} gap region(s) built from source (src/gap/)")

    libs = library_symbols(set(CRT_LIBS) | set(IMPORT_LIBS))
    import_libs: list[Path] = []
    if stub_mode:
        import_libs = build_import_libs()
        for lib in import_libs:
            for name in archive_symbols(lib):
                libs.setdefault(name, lib.name)

    aliases_path = BUILD / "aliases.obj"
    aliases = build_aliases(objects + gaps + carved + data_objs, symbols, data_addr, libs, aliases_path,
                            extra=extra,
                            winmain_addr=WINMAIN_ADDR if stub_mode and not args.carve else None,
                            data_fallback=stub_mode)
    print(f"{len(objects):,} objects, {len(aliases):,} aliases, {len(data_addr):,} globals at known addresses")

    # The carved data goes first: where a compiled object defines a global too,
    # LINK keeps the first definition, the original's, at its full size.
    game = (fix_initialisers(objects) if stub_mode else list(objects)) + gaps
    if args.carve:
        from carve import patch_objects
        game = patch_objects(game, result)
    link_objects = carved[:1] + game + carved[1:] + list(data_objs)
    if stub_mode:
        missing = unresolved_names(link_objects, set(aliases), libs)
        funcs = [n for n, is_func in missing.items() if is_func]
        data = [n for n, is_func in missing.items() if not is_func]
        stubs = BUILD / "stubs.obj"
        write_stub_object(funcs, data, stubs)
        print(f"stub mode: {len(funcs):,} function stubs and {len(data):,} data stubs "
              f"in {stubs.relative_to(ROOT)}")
        link_objects += [stubs, aliases_path]
        link_objects += import_libs
    else:
        link_objects += [aliases_path]

    rc = link(link_objects, output, args.verbose, force_unresolved=not stub_mode,
              map_path=(BUILD / "TotalA.map") if args.map else None)
    if rc == 0 and output.exists():
        print(f"{output.relative_to(ROOT)}: {output.stat().st_size:,} bytes")
        if stub_mode:
            dll = build_stub_dll(output.parent)
            print(f"stub mode: {dll.relative_to(ROOT)} (no-op Smacker decoder) beside the exe")
    raise SystemExit(rc)


if __name__ == "__main__":
    main()
