"""Link the source tree at the original exe's addresses (a placement link).

    uv run tools/place.py                # build build/place/TotalA.exe and compare it
    uv run tools/place.py --verbose      # also list every difference in full
    uv run tools/place.py --strict       # exit non-zero if any built byte differs

tools/link.py links the tree the ordinary way, so every function lands
wherever LINK puts it. That image cannot run as the game yet: the 29 gap
regions (code with no source) and much of the data hold absolute addresses, the original exe has no relocation table to move
them with, and callers that spell a callee differently need alias bridges.
place.py instead lays every piece out exactly where the original has it, the
layout LEGO Island's decomp checks its rebuilt binaries against (reccmp,
ReproBit), so code and data that are not rebuilt still find everything where
they expect it, and every call reaches the one function at its address:

  * every game function (data/progress.csv) is placed at its address from its
    object in build/progress, the objects tools/check.py compares, and the
    functions of every gap region whose source matches (tools/gapcheck.py);
  * every relocation in a placed piece is resolved by name: a placed function
    or global, a placeholder name (FUN_/DAT_<address>), a data/symbols.csv
    name (or one of its data/aliases.csv copies), an import (its slot in the
    original's import address table, or the linker's `jmp [slot]` stub), or a
    runtime library function data/functions.csv names;
  * the import tables and the linker's `jmp [slot]` stubs are the import
    libraries' members (the toolchain's, and LIB.EXE's from link/*.def), each
    where the original has its part;
  * .tls is the runtime's tlssup.obj and the game's thread-local variables,
    and the TLS directory is tlssup.obj's __tls_used;
  * data the compiler emits with the code (string literals, floating-point
    constants, jump tables, exception tables, vtables, file and function
    statics) is placed one symbol at a time where the original's code refers
    to it, the way a map file would say; its contents come from the object
    and are compared with the original's;
  * link/data.cpp and the globals tools/globals.py leaves out are placed at
    their addresses, one global at a time;
  * the runtime library comes from the members of LIBCMT.LIB, LIBCPMT.LIB and
    zlib that the original links, each where the original holds its bytes and
    refers to the same functions, imports and data contents, and from
    src/lib/ (the basic_string members compiled with the game's options);
  * the resources are compiled from src/res/TotalA.rc and the game's icon
    and cursor with RC.EXE and CVTRES.EXE (tools/resources.py) and placed at
    the start of .rsrc;
  * the PE headers and the debug data after the sections are generated by
    tools/pe.py from the placed sections and link/link.toml;
  * what has no source yet would be copied from the original and counted as
    copied: gap regions without matching source and data no object defines.
    Nothing is.

Every relocation is checked against the address the original uses at that
spot, and the image is compared with the original byte for byte (the
placement and data compare of #4869). The report counts where each byte came
from, so it says how much of the image is built from source and how much is
still copied. build/place/TotalA.map lists every placed piece.
"""

import argparse
import bisect
from array import array
import csv
import re
import struct
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

import pefile

from check import LIB_DIR, ROOT, base_name, load_symbols
from crtmatch import MIN_SIZE
from gapcheck import gap_objects
from link import build_data, compile_all
from linkcheck import address_of

OUT_DIR = ROOT / "build/place"
PROGRESS = ROOT / "data/progress.csv"
FUNCTIONS = ROOT / "data/functions.csv"
GLOBALS = ROOT / "data/globals.csv"
ALIASES = ROOT / "data/aliases.csv"
PATCHES = ROOT / "data/exe_patches.csv"
DEF_FILES = sorted((ROOT / "link").glob("*.def"))

REL_DIR32, REL_DIR32NB, REL_SECREL, REL_REL32 = 0x06, 0x07, 0x0B, 0x14
SCN_CODE, SCN_UNINIT = 0x20, 0x80
SYM_CLASS_SECTION = 104
SKIP_SECTIONS = (".drectve", ".debug")

# Where each byte of the image came from.
SOURCES = ["unset", "game code", "game data", "global data", "library (copied)", "gap (copied)",
           "data (copied)", "padding", "headers, imports, resources (copied)", "library code",
           "library data", "gap code", "data source", "resources", "import tables", "thread-local data",
           "uninitialised", "debug directory"]
(UNSET, CODE, OBJDATA, GLOBALDATA, LIBRARY, GAP, COPIED, PADDING, FIXED, LIBCODE,
 LIBDATA, GAPCODE, DATASRC, RESOURCES, IMPORTS, TLSDATA, UNINIT, DEBUGDIR) = range(len(SOURCES))

# The output section LINK puts each input section in, by the name before the
# `$`: the import data and the exception tables go into .rdata, the
# uninitialised data and the C runtime's initialiser tables into .data.
OUTPUT_SECTIONS = {".text": ".text", ".rdata": ".rdata", ".idata": ".rdata", ".xdata": ".rdata",
                   ".data": ".data", ".bss": ".data", ".CRT": ".data", ".tls": ".tls", ".rsrc": ".rsrc"}

# The libraries the original links statically: the VC5 SP3 C and C++ runtimes,
# and zlib 1.0.4 as tools/setup_toolchain.sh builds it with Cavedog's options.
LIBRARIES = [ROOT / "toolchain/msvc5-sp3/LIB/LIBCMT.LIB", ROOT / "toolchain/msvc5-sp3/LIB/LIBCPMT.LIB"]
THIRD_PARTY = ROOT / "toolchain/thirdparty/zlib-1.0.4"


# --- COFF objects -------------------------------------------------------------------

@dataclass
class Sym:
    index: int
    name: str
    value: int
    section: int      # 1-based; 0 undefined or common, negative absolute/debug
    sclass: int       # 2 external, 3 static
    is_func: bool


@dataclass
class Sec:
    index: int
    name: str
    chars: int
    data: bytes
    relocs: list[tuple[int, int, int]]   # (offset, symbol index, type)
    starts: list[int] = field(default_factory=list)   # offsets where a named symbol begins

    @property
    def is_code(self) -> bool:
        return bool(self.chars & SCN_CODE)

    def slice_at(self, offset: int) -> tuple[int, int]:
        """The symbol-to-symbol slice holding offset."""
        i = bisect.bisect_right(self.starts, offset) - 1
        lo = self.starts[i] if i >= 0 else 0
        hi = self.starts[i + 1] if i + 1 < len(self.starts) else len(self.data)
        return lo, hi


@dataclass
class Obj:
    path: Path
    secs: list[Sec]
    syms: dict[int, Sym]
    raw: bytes
    library: bool = False      # a member of a runtime or third-party library
    gap: bool = False          # a gap region's source (tools/gapcheck.py)
    data: bool = False         # the data as source (src/data)
    externals: dict[str, Sym] = field(default_factory=dict)
    absolutes: dict[str, int] = field(default_factory=dict)    # IMAGE_SYM_ABSOLUTE externals
    commons: dict[str, int] = field(default_factory=dict)      # communal (.bss) externals -> size
    # An import descriptor's section symbols (.idata$4, .idata$5, of storage
    # class SECTION): where LINK put the first of its DLL's contributions.
    section_starts: dict[str, int] = field(default_factory=dict)


def parse(path: Path, data: bytes | None = None, library: bool = False) -> Obj:
    data = path.read_bytes() if data is None else data
    _, nsects, _, symptr, nsyms, opthdr, _ = struct.unpack_from("<HHIIIHH", data, 0)
    strtab = data[symptr + nsyms * 18:]

    def name_of(raw: bytes) -> str:
        if raw[:4] == b"\0\0\0\0":
            (off,) = struct.unpack_from("<I", raw, 4)
            return strtab[off:strtab.index(b"\0", off)].decode("latin-1")
        return raw[:8].split(b"\0", 1)[0].decode("latin-1")

    secs = []
    for s in range(nsects):
        hdr = data[20 + opthdr + s * 40: 20 + opthdr + s * 40 + 40]
        sname = hdr[:8].split(b"\0", 1)[0].decode("latin-1")
        if sname.startswith("/"):
            sname = strtab[int(sname[1:]):].split(b"\0", 1)[0].decode("latin-1")
        size, rawptr, relptr, _, nrel, _, chars = struct.unpack_from("<IIIIHHI", hdr, 16)
        body = data[rawptr:rawptr + size] if rawptr else bytes(size)
        relocs = [struct.unpack_from("<IIH", data, relptr + r * 10) for r in range(nrel)]
        secs.append(Sec(s + 1, sname, chars, body, relocs))
    syms: dict[int, Sym] = {}
    i = 0
    while i < nsyms:
        raw = data[symptr + i * 18: symptr + i * 18 + 18]
        value, secnum, typ, sclass, naux = struct.unpack_from("<IhHBB", raw, 8)
        syms[i] = Sym(i, name_of(raw), value, secnum, sclass, (typ & 0x30) == 0x20)
        i += 1 + naux
    obj = Obj(path, secs, syms, data, library)
    for s in syms.values():
        if s.section > 0 and s.sclass in (2, 3) and not s.name.startswith("."):
            obj.secs[s.section - 1].starts.append(s.value)
            if s.sclass == 2:
                obj.externals[s.name] = s
        elif s.sclass == 2 and s.section == -1:
            obj.absolutes[s.name] = s.value
        elif s.sclass == 2 and s.section == 0 and s.value:
            obj.commons[s.name] = s.value
    for sec in secs:
        sec.starts = sorted(set(sec.starts))
    return obj


def read_library(path: Path) -> list[Obj]:
    """The object members of a COFF archive (.lib)."""
    data = path.read_bytes()
    longnames, members, pos = b"", [], 8
    while pos + 60 <= len(data):
        name = data[pos:pos + 16].decode("latin-1").rstrip()
        size = int(data[pos + 48:pos + 58])
        body = data[pos + 60:pos + 60 + size]
        pos += 60 + size + (size & 1)
        if name == "//":
            longnames = body
        elif name != "/" and body[:2] == b"\x4c\x01":
            if name.startswith("/"):
                name = longnames[int(name[1:]):].split(b"\0", 1)[0].decode("latin-1")
            members.append(parse(Path(f"{path.name}({name.rstrip('/')})"), body, library=True))
    return members


# --- the original -------------------------------------------------------------------

class Image:
    """The original exe mapped at its addresses, the image being built over the
    same layout, and where each byte of it came from."""

    def __init__(self, path: Path):
        self.pe = pefile.PE(str(path))
        self.base = self.pe.OPTIONAL_HEADER.ImageBase
        self.size = self.pe.OPTIONAL_HEADER.SizeOfImage
        self.orig = bytearray(self.pe.get_memory_mapped_image()[:self.size])
        self.orig += bytes(self.size - len(self.orig))
        # The compiler's bytes under later hand patches (data/exe_patches.csv).
        self.pristine = bytearray(self.orig)
        self.patches = []
        if PATCHES.exists():
            for row in csv.DictReader(PATCHES.open()):
                at, original = int(row["address"], 16), bytes.fromhex(row["original"])
                self.pristine[at - self.base: at - self.base + len(original)] = original
                self.patches.append((at, len(original), row["note"]))
        self.copied_library: list[tuple[int, str]] = []   # library functions no member was placed for
        self.out = bytearray(self.size)
        self.src = bytearray(self.size)            # SOURCES index per byte
        self.owner = array("i", bytes(4 * self.size))   # 1 + the index of the piece that wrote it
        self.sections = [(s.Name.rstrip(b"\0").decode(), self.base + s.VirtualAddress,
                          s.Misc_VirtualSize, s.SizeOfRawData, s) for s in self.pe.sections]

    def inside(self, va: int) -> bool:
        return self.base + 0x1000 <= va < self.base + self.size

    def u32(self, va: int) -> int:
        return struct.unpack_from("<I", self.pristine, va - self.base)[0]

    def free(self, va: int) -> bool:
        return self.inside(va) and self.src[va - self.base] == UNSET

    def write(self, va: int, data: bytes, source: int, owner: int = 0) -> int:
        """Write where nothing is written yet; return how many bytes differed
        from what another piece had already written."""
        off = va - self.base
        clash = 0
        for i, b in enumerate(data):
            if not 0 <= off + i < self.size:
                break
            if self.src[off + i] == UNSET:
                self.out[off + i] = b
                self.src[off + i] = source
                self.owner[off + i] = owner
            elif self.out[off + i] != b:
                clash += 1
        return clash

    def copy(self, va: int, size: int, source: int) -> None:
        off = va - self.base
        for i in range(max(off, 0), min(off + size, self.size)):
            if self.src[i] == UNSET:
                self.out[i] = self.pristine[i]
                self.src[i] = source

    def imports(self) -> dict[tuple[str, str], int]:
        """(dll, name) -> the address of its slot in the import address table.
        Ordinal imports are named through link/*.def."""
        names: dict[tuple[str, int], str] = {}
        for path in DEF_FILES:
            dll = ""
            for line in path.read_text().splitlines():
                line = line.split(";", 1)[0].strip()
                m = re.match(r"LIBRARY\s+(\S+)", line, re.I)
                if m:
                    dll = m.group(1).lower().removesuffix(".dll")
                m = re.match(r"(\S+)\s+@(\d+)", line)
                if m and dll:
                    names[(dll, int(m.group(2)))] = m.group(1)
        out = {}
        for entry in self.pe.DIRECTORY_ENTRY_IMPORT:
            dll = entry.dll.decode().lower().removesuffix(".dll")
            for imp in entry.imports:
                name = imp.name.decode() if imp.name else names.get((dll, imp.ordinal), f"#{imp.ordinal}")
                out[(dll, undecorate(name))] = imp.address
        return out

    def fixed_ranges(self) -> list[tuple[int, int]]:
        """Tables the linker builds inside the sections: the import directory,
        its lookup and name tables, the import address table, and the debug and
        TLS directories."""
        out = []
        opt = self.pe.OPTIONAL_HEADER
        for idx in (1, 6, 9, 12):   # import, debug, TLS, IAT
            d = opt.DATA_DIRECTORY[idx]
            if d.VirtualAddress:
                out.append((self.base + d.VirtualAddress, d.Size))
        for entry in self.pe.DIRECTORY_ENTRY_IMPORT:
            for t in (entry.struct.OriginalFirstThunk, entry.struct.FirstThunk):
                out.append((self.base + t, 4 * (len(entry.imports) + 1)))
            # The DLL's name and its NUL, padded to an even length too.
            out.append((self.base + entry.struct.Name, (len(entry.dll) + 2) & ~1))
            for imp in entry.imports:
                if imp.name:
                    # A hint, the name and its NUL, padded to an even length.
                    out.append((self.base + imp.hint_name_table_rva, (len(imp.name) + 4) & ~1))
        return out


def undecorate(name: str) -> str:
    """_CreateFileA@28 -> CreateFileA, so import names compare across spellings."""
    return re.sub(r"@\d+$", "", name.lstrip("_"))


# --- placing ------------------------------------------------------------------------

@dataclass
class Piece:
    obj: Obj
    sec: Sec
    lo: int           # the part of the section placed
    hi: int
    va: int
    source: int
    label: str
    id: int
    why: str = ""     # for a piece placed where the original refers to it: the referring site


class Placer:
    def __init__(self, img: Image, objects: list[Obj], symbols: dict[str, int]):
        self.img = img
        self.objects = objects
        self.symbols = symbols
        self.pieces: list[Piece] = []
        self.placed: dict[tuple[int, int], list[Piece]] = defaultdict(list)   # (id(obj), sec) -> pieces
        self.globals: dict[str, int] = {}          # external code name -> address
        self.definers: dict[str, list[tuple[Obj, Sym]]] = defaultdict(list)
        self.absolutes: dict[str, int] = {}
        self.commons: dict[str, int] = {}
        self.common_at: dict[str, int] = {}        # communal symbol -> where the original has it
        self.learned: dict[str, int] = {}          # name no object defines -> where the original points
        self.gap_regions: dict[int, object] = {}   # gap region built from source -> its gapcheck.GapObject
        self.built_regions: set[int] = set()       # gap regions with nothing left to copy
        # Every external name the placed game code refers to -> the addresses the
        # original's code holds there: what each spelling really means.
        self.ref_targets: dict[str, Counter] = defaultdict(Counter)
        for obj in objects:
            self.add_definer(obj)
        self.aliases: dict[str, set[int]] = defaultdict(set)
        if ALIASES.exists():
            for row in csv.DictReader(ALIASES.open()):
                self.aliases[row["name"]].add(int(row["address"], 16))
        self.import_slots = img.imports()
        self.import_members: dict[int, Obj] = {}   # import address table slot -> the member placed there
        self.tls_start: int | None = None          # where .tls begins (place_tls)
        self.tls_directory: int | None = None      # where __tls_used is (place_tls)
        self.resources: Obj | None = None          # CVTRES's object (place_resources)
        self.debug_directory: int | None = None    # where LINK's debug directory goes
        # The linker's `jmp [slot]` stubs, for callers that call an import directly.
        # A stub in one of the runs of them (place_import_thunks) comes first:
        # ___threadid is `jmp [GetCurrentThreadId]` too, and the same bytes
        # turn up inside other instructions.
        slot_name = {a: n for (_, n), a in self.import_slots.items()}
        self.thunks: dict[str, int] = {}
        in_runs: dict[str, int] = {}
        runs = thunk_runs()
        text = next(s for s in img.sections if s[0] == ".text")
        lo = text[1] - img.base
        for m in re.finditer(rb"\xff\x25(....)", bytes(img.pristine[lo:lo + text[2]])):
            (slot,) = struct.unpack("<I", m.group(1))
            if slot in slot_name and m.start() % 2 == 0:
                va = img.base + lo + m.start()
                self.thunks.setdefault(slot_name[slot], va)
                if any(a <= va < a + n for a, n in runs):
                    in_runs.setdefault(slot_name[slot], va)
        self.thunks.update(in_runs)
        self.library: dict[str, list[int]] = defaultdict(list)   # runtime library symbol -> addresses
        self.stats = Counter()
        self.mismatches: list[str] = []
        self.unresolved: Counter = Counter()
        self.clashes: list[str] = []
        self.renamed: list[str] = []
        self.todo: list[Piece] = []
        # Library function names by address, for refs_agree: data/functions.csv's,
        # corrected as members are placed.
        self.named_at: dict[int, str] = {}
        for row in load_rows(FUNCTIONS):
            if row["kind"] == "library" and row["name"]:
                self.named_at[int(row["address"], 16)] = row["name"].split(": ", 1)[-1]
        # Library code sections by their size without padding (place_library).
        self.by_size: dict[int, list[tuple[Obj, Sym]]] = defaultdict(list)

    def add_definer(self, obj: Obj) -> None:
        for name, sym in obj.externals.items():
            self.definers[name].append((obj, sym))
        self.absolutes.update(obj.absolutes)
        self.commons.update(obj.commons)

    # -- pieces --

    def place(self, obj: Obj, sec: Sec, lo: int, hi: int, va: int, source: int, label: str) -> Piece:
        piece = Piece(obj, sec, lo, hi, va, source, label, len(self.pieces) + 1)
        clash = self.img.write(va, sec.data[lo:hi], source, piece.id)
        if clash:
            self.clashes.append(f"{va:#x} {label}: {clash} byte(s) differ from a piece already placed there")
        self.pieces.append(piece)
        self.placed[(id(obj), sec.index)].append(piece)
        if sec.is_code:
            for sym in obj.syms.values():
                if sym.section == sec.index and sym.sclass == 2 and lo <= sym.value < hi:
                    self.globals.setdefault(sym.name, va + sym.value - lo)
        self.todo.append(piece)
        return piece

    def address_in(self, obj: Obj, section: int, offset: int) -> int | None:
        for p in self.placed.get((id(obj), section), ()):
            if p.lo <= offset < p.hi:
                return p.va + offset - p.lo
        return None

    def place_at(self, obj: Obj, sym: Sym, offset: int, va: int, why: str = "") -> bool:
        """Place the part of sym's section that holds `offset` so that offset
        lands at va: a whole section for code, one symbol's slice for data.
        Nothing is placed over another piece; returns whether it was placed."""
        sec = obj.secs[sym.section - 1]
        if sec.name.startswith(SKIP_SECTIONS):
            return False
        lo, hi = (0, len(sec.data)) if sec.is_code else sec.slice_at(offset)
        start = va - (offset - lo)
        if self.address_in(obj, sec.index, offset) is not None or not self.img.free(start):
            return False
        if sec.is_code:
            # Code goes only where the original holds the same code: a library
            # member's neighbours can differ from the original's.
            hi = body_size(sec)
            if not masked_match(self.img, sec, start, hi):
                return False
            if obj.library and not self.refs_agree(obj, sec, start):
                return False
        if obj.library:
            source = LIBCODE if sec.is_code else LIBDATA
        else:
            source = (GAPCODE if obj.gap else CODE) if sec.is_code else (DATASRC if obj.data else OBJDATA)
        piece = self.place(obj, sec, lo, hi, start, source, f"{sec.name} of {obj.path.stem} ({sym.name})")
        piece.why = why
        self.stats["code pieces placed where the original refers to them" if sec.is_code
                   else "data pieces placed where the original refers to them"] += 1
        if (not sec.is_code and lo and lo == sec.starts[0] and self.img.free(start - lo)
                and any(off < lo for off, _, _ in sec.relocs)):
            # A pointer before a section's first symbol goes with it: the
            # runtime library's vtables (compiled with RTTI) are each preceded
            # by a pointer to their class's complete object locator.
            lead = self.place(obj, sec, 0, lo, start - lo, source, f"{sec.name} of {obj.path.stem} (before {sym.name})")
            lead.why = why
            self.stats["data placed with the symbol after it"] += 1
        return True

    def refs_agree(self, obj: Obj, sec: Sec, start: int) -> bool:
        """Whether a library member's code placed at start refers to what the
        original's code there refers to: its calls reach functions of the same
        names, its imports the same slots, and its own data (literals, tables,
        initial values) the same contents. Many runtime functions differ only
        there: _read, _write and _lseek's locking wrappers, _Xlen and _Xran,
        zlib's get_crc_table and zlibVersion."""
        img = self.img
        for off, symidx, rtype in sec.relocs:
            if off + 4 > len(sec.data):
                continue
            site, sym = start + off, obj.syms[symidx]
            ours = struct.unpack_from("<I", sec.data, off)[0]
            if rtype == REL_REL32:
                target = (site + 4 + img.u32(site) - ours) & 0xFFFFFFFF
                if self.globals.get(sym.name) == target:
                    # A function of that name is placed there, a game function
                    # too: Cavedog's operator new, which the exception
                    # constructors call.
                    continue
                if target in self.named_at:
                    if self.named_at[target] != sym.name:
                        return False
                    continue
                # An unnamed callee: some library member defining the name
                # must hold the code there (_lockexit calls _lock, _unlockexit
                # _unlock, and the two are otherwise identical).
                callees = [(o, t) for o, t in self.definers.get(sym.name, ())
                           if o.library and t.section > 0 and o.secs[t.section - 1].is_code]
                if callees and not any(masked_match(img, o.secs[t.section - 1], target - t.value,
                                                    body_size(o.secs[t.section - 1]))
                                       for o, t in callees):
                    return False
            elif rtype == REL_DIR32 and sym.name.startswith("__imp_"):
                slots = [a for (_, n), a in self.import_slots.items()
                         if n == undecorate(sym.name[len("__imp_"):])]
                # An import the original does not have cannot be what it calls.
                if len(slots) != 1 or (img.u32(site) - ours) & 0xFFFFFFFF != slots[0]:
                    return False
            elif rtype == REL_DIR32:
                item = (img.u32(site) - ours) & 0xFFFFFFFF
                offset = sym.value + (ours if sym.name.startswith(".") else 0)
                if sym.section > 0 and not obj.secs[sym.section - 1].is_code:
                    if not self.content_matches(obj, sym, offset, item + (offset - sym.value)):
                        return False
                elif sym.section == 0 and not sym.name.startswith("__imp_"):
                    # Data another member defines: one of its definers must hold
                    # the original's contents there.
                    held = [(o, t) for o, t in self.definers.get(sym.name, ())
                            if o.library and t.section > 0 and not o.secs[t.section - 1].is_code]
                    if held and not any(self.content_matches(o, t, t.value, item) for o, t in held):
                        return False
        return True

    def content_matches(self, obj: Obj, sym: Sym, offset: int, va: int, depth: int = 3) -> bool:
        """Whether the original holds, at va, the bytes of sym's section from
        offset to the end of its slice (at most 32 bytes): zeros for
        uninitialised data, a string up to its terminator, and for the fields
        the linker fills in, the same contents again where they point at data
        of the same object (an exception's throw info, down to the type name)."""
        sec = obj.secs[sym.section - 1]
        if not self.img.inside(va):
            return True
        lo, hi = sec.slice_at(offset)
        hi = min(hi, offset + 32)
        o = va - self.img.base
        if sec.chars & SCN_UNINIT:
            return not any(self.img.pristine[o:o + hi - offset])
        text = sec.data[offset:hi]
        if sym.name.startswith(("??_C@_0", "$SG")) and b"\0" in text:
            hi = offset + text.index(b"\0") + 1      # a string: up to its terminator
        fixed = bytearray(b"\1" * (hi - offset))
        for roff, symidx, rtype in sec.relocs:
            if not offset <= roff < hi:
                continue
            for i in range(roff, min(roff + 4, hi)):
                fixed[i - offset] = 0
            target = obj.syms[symidx]
            if (depth and rtype == REL_DIR32 and roff + 4 <= hi and target.section > 0
                    and not obj.secs[target.section - 1].is_code):
                (ours,) = struct.unpack_from("<I", sec.data, roff)
                at = target.value + ours          # the field holds the target's address plus ours
                theirs = struct.unpack_from("<I", self.img.pristine, o + roff - offset)[0]
                if not self.content_matches(obj, target, at, theirs, depth - 1):
                    return False
        theirs = self.img.pristine[o:o + hi - offset]
        return all(not f or a == b for a, b, f in zip(sec.data[offset:hi], theirs, fixed))

    # -- symbols --

    def resolve(self, obj: Obj, sym: Sym, offset: int) -> int | None:
        """The address a relocation against sym (at offset `offset` from its
        section's start, for section symbols) should hold, or None when only
        the original can say."""
        if sym.section > 0:
            sec = obj.secs[sym.section - 1]
            local = self.address_in(obj, sym.section, offset)
            if local is not None:
                return local - (offset - sym.value)
            if sec.is_code and sym.sclass == 2:
                # A copy of a function defined elsewhere (kept so it inlines):
                # the call goes to the one at its address.
                if sym.name in self.globals:
                    return self.globals[sym.name]
                addr = self.named_address(sym.name)
                if addr is not None:
                    return addr
            if not sec.is_code and sym.sclass == 2:
                addr = address_of(sym.name, self.symbols)
                if addr is not None:
                    self.place_at(obj, sym, sym.value, addr)
                    return addr
            return None
        name = sym.name
        if sym.sclass == SYM_CLASS_SECTION and name in obj.section_starts:
            return obj.section_starts[name]
        if name in self.globals:
            return self.globals[name]
        if name in self.absolutes:
            return self.absolutes[name]
        if name.startswith("__imp_"):
            imp = undecorate(name[len("__imp_"):])
            hits = [a for (dll, n), a in self.import_slots.items() if n == imp]
            if not hits and re.fullmatch(r"DAT_[0-9a-f]{8}", imp):
                # An import the source has no name for yet, named by its slot.
                hits = [a for a in self.import_slots.values() if a == int(imp[4:], 16)]
            return hits[0] if len(hits) == 1 else None
        if undecorate(name) in self.thunks and name not in self.definers:
            return self.thunks[undecorate(name)]
        return self.named_address(name)

    def place_copy(self, name: str, va: int) -> bool:
        """Place a second copy of a library function at va when the original
        holds one there (LIBCMT's lseek is linked twice)."""
        for obj, sym in self.definers.get(name, ()):
            sec = obj.secs[sym.section - 1]
            if not obj.library or not sec.is_code:
                continue
            start = va - sym.value
            body = body_size(sec)
            if not self.img.free(start) or not masked_match(self.img, sec, start, body):
                continue
            copy = parse(obj.path, obj.raw, library=True)
            self.objects.append(copy)
            self.place(copy, copy.secs[sec.index - 1], 0, body, start, LIBCODE, f"{name} (second copy)")
            self.stats["library sections placed as a second copy"] += 1
            return True
        return False

    def copies(self, name: str) -> set[int]:
        """Every address one name may stand for: the copies data/aliases.csv
        lists and the runtime library code linked twice (std::_Lockit)."""
        base = base_name(name)
        out = set(self.aliases.get(base, ())) | set(self.library.get(name, ()))
        if base in self.symbols and self.aliases.get(base):
            out.add(self.symbols[base])
        return out

    def named_address(self, name: str) -> int | None:
        if name in self.library:
            return self.library[name][0]
        addr = address_of(name, self.symbols)
        if addr is not None:
            return addr
        base = base_name(name)
        for cand in (base, base[1:]):
            if len(self.aliases.get(cand, ())) == 1:
                # A name only data/aliases.csv knows (__chkstk is _chkstk).
                return next(iter(self.aliases[cand]))
        if name.startswith("?") and "@@Y" in name:
            # A C runtime function declared without extern "C" (?tolower@@YAHH@Z).
            base = base_name(name)
            if "::" not in base and "_" + base in self.library:
                return self.library["_" + base][0]
        return None

    # -- relocations --

    def relocate(self) -> None:
        while self.todo:
            piece = self.todo.pop()
            obj, sec = piece.obj, piece.sec
            for off, symidx, rtype in sec.relocs:
                if not piece.lo <= off <= piece.hi - 4:
                    continue
                site = piece.va + off - piece.lo
                sym = obj.syms[symidx]
                (ours,) = struct.unpack_from("<I", sec.data, off)
                theirs = self.img.u32(site)
                if rtype == REL_DIR32:
                    orig_target = (theirs - ours) & 0xFFFFFFFF
                elif rtype == REL_REL32:
                    orig_target = (site + 4 + theirs - ours) & 0xFFFFFFFF
                elif rtype == REL_DIR32NB:
                    orig_target = (theirs - ours + self.img.base) & 0xFFFFFFFF
                elif rtype == REL_SECREL:
                    # A thread-local variable's offset in .tls (place_tls).
                    orig_target = (self.tls_start + theirs - ours) & 0xFFFFFFFF
                    target = self.resolve(obj, sym, sym.value)
                    if target is None:
                        target = self.placed_definition(sym.name)
                    how = "thread-local offsets resolved by name"
                    if target is None:
                        target, how = orig_target, "thread-local offsets from the original's bytes"
                        self.unresolved[sym.name] += 1
                    self.stats[how] += 1
                    if target != orig_target:
                        self.mismatches.append(f"{site:#x} in {piece.label}: {sym.name} is at {target:#x} in .tls, "
                                               f"the original uses {orig_target:#x}")
                    if self.pieces_own(piece, site):
                        o = site - self.img.base
                        self.img.out[o:o + 4] = struct.pack("<I", (target + ours - self.tls_start) & 0xFFFFFFFF)
                    continue
                else:
                    self.stats[f"relocation type {rtype:#x} skipped"] += 1
                    continue
                # A section symbol plus an offset names whatever lies there.
                offset = sym.value + (ours if rtype == REL_DIR32 and sym.name.startswith(".") else 0)
                if piece.source in (CODE, GAPCODE) and (sym.sclass == 2 or sym.section == 0):
                    self.ref_targets[sym.name][orig_target] += 1
                target = self.resolve(obj, sym, offset)
                how = "by name"
                if target is None:
                    # Nothing names the target: it is where the original's code
                    # points, and the piece that defines it goes there.
                    target = orig_target
                    definer = None
                    if sym.section > 0:
                        definer = (obj, sym)
                    elif sym.name in self.definers:
                        # Several members can define one name (crt0 and wincrt0
                        # both define __app_type): take the one whose contents
                        # the original holds.
                        found = [(o, s) for o, s in self.definers[sym.name] if s.section > 0]
                        definer = next(((o, s) for o, s in found
                                        if self.content_matches(o, s, s.value, orig_target)), None)
                        definer = definer or (found[0] if found else None)
                    if definer and self.img.inside(orig_target):
                        d_obj, d_sym = definer
                        at = offset if d_obj is obj else d_sym.value
                        self.place_at(d_obj, d_sym, at, orig_target + (at - d_sym.value),
                                      f"{site:#x} in {piece.label}")
                        how = "where the original refers to it"
                    elif sym.name in self.commons:
                        # Communal data the linker allocates in .bss.
                        how = "to common data where the original has it"
                        self.common_at.setdefault(sym.name, orig_target)
                    else:
                        how = "from the original's bytes"
                        self.unresolved[sym.name] += 1
                        self.learned.setdefault(sym.name, orig_target)
                elif target != orig_target and (orig_target in self.copies(sym.name)
                                                or self.place_copy(sym.name, orig_target)):
                    target = orig_target       # another copy of the same function
                    how = "by name, to another copy"
                self.stats[f"relocations resolved {how}"] += 1
                if target != orig_target:
                    note = (f"{site:#x} in {piece.label}: {sym.name} resolves to {target:#x}, "
                            f"the original uses {orig_target:#x}")
                    if piece.label.startswith("??_7") or "(??_7" in piece.label:
                        # A vtable slot naming the base class's method where the
                        # original has an override: tools/vtablecheck.py says
                        # which name the slot's own file defines.
                        note += " (a vtable slot: see tools/vtablecheck.py)"
                    self.mismatches.append(note)
                if rtype == REL_DIR32:
                    value = (target + ours) & 0xFFFFFFFF
                elif rtype == REL_DIR32NB:
                    value = (target + ours - self.img.base) & 0xFFFFFFFF
                else:
                    value = (target + ours - (site + 4)) & 0xFFFFFFFF
                o = site - self.img.base
                if self.pieces_own(piece, site):
                    self.img.out[o:o + 4] = struct.pack("<I", value)

    def placed_definition(self, name: str) -> int | None:
        """Where a placed piece defines the external name, if one does (a
        thread-local variable another object defines)."""
        for obj, sym in self.definers.get(name, ()):
            if sym.section > 0:
                at = self.address_in(obj, sym.section, sym.value)
                if at is not None:
                    return at
        return None

    def pieces_own(self, piece: Piece, site: int) -> bool:
        """Whether this piece wrote the field at site (a piece placed partly
        over another must not patch the other's bytes)."""
        o = site - self.img.base
        return all(self.img.owner[o + i] == piece.id for i in range(4))


# --- the build ----------------------------------------------------------------------

def load_rows(path: Path) -> list[dict]:
    with path.open() as fh:
        return list(csv.DictReader(fh))


def place_functions(placer: Placer, objects_by_src: dict[str, Obj]) -> None:
    sizes = {int(r["address"], 16): int(r["size"]) for r in load_rows(FUNCTIONS)}
    for row in load_rows(PROGRESS):
        addr, symbol = int(row["address"], 16), row["symbol"]
        obj = objects_by_src.get(row["file"])
        if obj is None or not symbol:
            placer.stats["game functions with no object"] += 1
            continue
        found = next((s for s in obj.syms.values() if s.name == symbol and s.section > 0
                      and obj.secs[s.section - 1].is_code), None)
        if found is None:
            placer.mismatches.append(f"{addr:#x}: {symbol} is not defined in {row['file']}")
            continue
        sec = obj.secs[found.section - 1]
        size = sizes.get(addr, len(sec.data) - found.value)
        placer.place(obj, sec, found.value, found.value + size, addr, CODE, symbol)
        placer.stats["game functions placed"] += 1
    # The alignment padding the compiler leaves after each function (every
    # function is its own COMDAT section, padded to 16 bytes with nops).
    for p in list(placer.pieces):
        if p.source == CODE and p.hi < len(p.sec.data):
            off = p.va + p.hi - p.lo - placer.img.base
            for i, b in enumerate(p.sec.data[p.hi:]):
                if placer.img.src[off + i] == UNSET:
                    placer.img.out[off + i], placer.img.src[off + i] = b, PADDING


def place_gaps(placer: Placer, gaps: dict) -> None:
    """The gap regions whose source matches (tools/gapcheck.py): each function
    at its address, and the alignment padding between them."""
    img = placer.img
    for region, gap in sorted(gaps.items()):
        obj = parse(gap.path)
        obj.gap = True
        placer.objects.append(obj)
        placer.add_definer(obj)
        for addr, symbol, size in gap.functions:
            sym = obj.externals.get(symbol) or next(
                (s for s in obj.syms.values() if s.name == symbol and s.section > 0), None)
            if sym is None:
                raise SystemExit(f"gap {region:#x}: {symbol} is not defined in {gap.path.name}")
            sec = obj.secs[sym.section - 1]
            placer.place(obj, sec, sym.value, sym.value + size, addr, GAPCODE, symbol)
            placer.stats["gap functions placed from source"] += 1
        # What is left of the region is the padding between its functions
        # (tools/gapcheck.py checks that nothing else is). It is the original's:
        # the compiler pads its sections with nops, but where the original's
        # code came from an assembler, the linker padded it with int3s.
        end = (region + gap.size + 15) & ~15
        for o in range(region - img.base, end - img.base):
            if img.src[o] == UNSET and img.pristine[o] in (0x90, 0xCC):
                img.out[o], img.src[o] = img.pristine[o], PADDING
        placer.gap_regions[region] = gap
        placer.built_regions.add(region)
        placer.stats["gap regions built from source"] += 1


def place_tls(placer: Placer) -> None:
    """The thread-local data. LINK builds .tls from the linked objects' .tls
    sections in the order of their names, each at its alignment: the
    runtime's __tls_start (tlssup.obj's .tls), the game's thread-local
    variables (.tls$: only src/gap/0x4d8d70.cpp's, Cavedog's one object with
    any, which the tree's other users declare), and __tls_end (tlssup.obj's
    .tls$ZZZ). tlssup.obj's .rdata, __tls_used, is the TLS directory, which
    goes where the original's data directory says; the callback table it
    points at (.CRT$XLA, empty up to .CRT$XLZ) goes with the other
    initialiser tables (place_crt_tables)."""
    img = placer.img
    tlssup = next((o for o in placer.objects if o.library and "__tls_used" in o.externals), None)
    if tlssup is None:
        placer.mismatches.append("no runtime library member defines __tls_used")
        return
    placed = {id(p.obj) for p in placer.pieces if p.sec.is_code}
    parts = sorted(((s.name, i, o, s) for i, o in enumerate(placer.objects)
                    if o is tlssup or (not o.library and id(o) in placed)
                    for s in o.secs if s.name == ".tls" or s.name.startswith(".tls$")),
                   key=lambda t: (t[0], t[1]))
    start = next(va for name, va, *_ in img.sections if name == ".tls")
    placer.tls_start = va = start
    for _, _, obj, sec in parts:
        n = (sec.chars >> 20) & 0xF
        align = 1 << (n - 1) if n else 16
        at = (va + align - 1) & ~(align - 1)
        img.write(va, bytes(at - va), PADDING)
        placer.place(obj, sec, 0, len(sec.data), at, LIBDATA if obj.library else TLSDATA,
                     f"{sec.name} of {obj.path.name}")
        placer.stats["thread-local sections placed"] += 1
        va = at + len(sec.data)
    rdata = next(s for s in tlssup.secs if s.name == ".rdata")
    directory = img.pe.OPTIONAL_HEADER.DATA_DIRECTORY[9].VirtualAddress
    placer.place(tlssup, rdata, 0, len(rdata.data), img.base + directory, LIBDATA, "__tls_used (the TLS directory)")
    placer.tls_directory = img.base + directory


def place_tree_globals(placer: Placer, objects_by_src: dict[str, Obj]) -> None:
    """The globals the tree's own files define (class objects with static
    initialisers, template statics), each from its largest definition: two
    files can hold different views of one class (0x460e20's Class_00460f60
    is 0xb53c bytes, 0x460f60's 0xb528)."""
    for row in load_rows(GLOBALS):
        if row.get("size_from") != "definition":
            continue
        addr = int(row["address"], 16)
        best = None
        for src, obj in objects_by_src.items():
            if not src.startswith("src/unsorted/"):
                continue
            for name, sym in obj.externals.items():
                sec = obj.secs[sym.section - 1]
                if sec.is_code or address_of(name, placer.symbols) != addr:
                    continue
                lo, hi = sec.slice_at(sym.value)
                if best is None or hi - lo > best[3] - best[2]:
                    best = (obj, sec, lo, hi, name)
        if best is not None and placer.img.free(addr):
            obj, sec, lo, hi, name = best
            placer.place(obj, sec, lo, hi, addr, OBJDATA, name)
            placer.stats["globals placed from the tree's own definitions"] += 1


def place_data_sources(placer: Placer, objects_by_src: dict[str, Obj]) -> None:
    """src/data, the game's data as source: every global at the address its
    `// GLOBAL:` annotation (or its DAT_<address> name) gives, from its
    symbol to the next one. String literals and other data its initial
    values point at follow where the original's pointers point."""
    for src, obj in sorted(objects_by_src.items()):
        if not src.startswith("src/data/"):
            continue
        obj.data = True
        for name, sym in sorted(obj.externals.items(), key=lambda kv: (kv[1].section, kv[1].value)):
            sec = obj.secs[sym.section - 1]
            if sec.is_code or sec.name.startswith(SKIP_SECTIONS) or name.startswith(("??_C@", "__real@")):
                continue          # literals and constants go where the original's pointers point
            addr = address_of(name, placer.symbols)
            if addr is None:
                placer.mismatches.append(f"{src}: {name} has no address (annotate it // GLOBAL: 0x...)")
                continue
            lo, hi = sec.slice_at(sym.value)
            placer.place(obj, sec, lo, hi, addr, DATASRC, name)
            placer.stats["globals placed from src/data"] += 1


def place_globals(placer: Placer, data_objs: list[Path], data_addr: dict[int, str]) -> None:
    """link/data.cpp and the generated extra globals, one global at a time."""
    sizes = {int(r["address"], 16): int(r["size"]) for r in load_rows(GLOBALS)}
    for path in data_objs:
        obj = parse(path)
        placer.objects.append(obj)
        placer.add_definer(obj)
        for sec in obj.secs:
            if sec.is_code or sec.name.startswith(SKIP_SECTIONS):
                continue
            for name, sym in obj.externals.items():
                if sym.section != sec.index:
                    continue
                addr = address_of(name, placer.symbols)
                if addr is None or data_addr.get(addr) != name:
                    continue
                lo, hi = sec.slice_at(sym.value)
                hi = min(hi, sym.value + sizes.get(addr, hi - sym.value))
                placer.place(obj, sec, sym.value, hi, addr, GLOBALDATA, name)
                placer.stats["globals placed from link/"] += 1


def masked_match(img: Image, sec: Sec, start: int, size: int) -> bool:
    """Whether the original holds sec's first `size` bytes at start, ignoring
    the fields the linker fills in."""
    fixed = bytearray(b"\1" * size)
    for off, _, rtype in sec.relocs:
        for i in range(off, min(off + 4, size)):
            fixed[i] = 0
    o = start - img.base
    if not img.inside(start) or o + size > img.size:
        return False
    return all(not f or a == b for a, b, f in zip(sec.data[:size], img.pristine[o:o + size], fixed))


def body_size(sec: Sec) -> int:
    """A code section without its trailing alignment padding."""
    return len(sec.data.rstrip(b"\x90\xcc")) or len(sec.data)


def place_library(placer: Placer, sources: list[Path] = ()) -> None:
    """The runtime library and zlib code, from the members of the libraries
    the original links, at the addresses data/functions.csv gives, and the
    library code built from src/lib/ (`sources`, which go first).

    A member goes where the original holds its bytes (ignoring the fields the
    linker fills in) and its calls reach functions of the right names: the
    locking wrappers _read, _write and _lseek are byte-identical apart from
    the function they call, so the bytes alone cannot tell them apart. A
    static function (string.obj's initialiser _$E50) is taken from a member
    already placed, the one placed nearest. Code shorter than MIN_SIZE that
    data/functions.csv has no name for is left to placer.relocate(), which
    puts what the placed code calls where the original's code points
    (__matherr, ___init_collate and setlocale's __init_dummy are the same three
    bytes), and to place_unreferenced_library for anything nothing calls."""
    members = [parse(p, library=True) for p in sources]
    members += [m for lib in LIBRARIES if lib.exists() for m in read_library(lib)]
    members += [parse(p, library=True) for p in sorted(THIRD_PARTY.glob("*.obj"))]
    by_name: dict[str, list[tuple[Obj, Sym]]] = defaultdict(list)
    by_size: dict[int, list[tuple[Obj, Sym]]] = defaultdict(list)
    statics: dict[str, list[tuple[Obj, Sym]]] = defaultdict(list)
    for m in members:
        placer.objects.append(m)
        placer.add_definer(m)
        for name, sym in m.externals.items():
            sec = m.secs[sym.section - 1]
            if sec.is_code:
                by_name[name].append((m, sym))
                if sym.value == 0:
                    by_size[body_size(sec)].append((m, sym))
        for sym in m.syms.values():
            if sym.sclass == 3 and sym.section > 0 and sym.value == 0 and m.secs[sym.section - 1].is_code:
                statics[sym.name].append((m, sym))
    placer.by_size = by_size
    img = placer.img
    rows = [r for r in load_rows(FUNCTIONS) if r["kind"] == "library"]
    named_at = placer.named_at

    def placed_statics(name: str, addr: int) -> list[tuple[Obj, Sym]]:
        """Static functions of that name in members already placed, nearest first."""
        near = []
        for obj, sym in statics.get(name, ()):
            vas = [p.va for sec in obj.secs for p in placer.placed.get((id(obj), sec.index), ())]
            if vas:
                near.append((min(abs(va - addr) for va in vas), obj, sym))
        return [(obj, sym) for _, obj, sym in sorted(near, key=lambda t: t[0])]

    pending = rows
    while pending:
        left = []
        for row in pending:
            addr, size = int(row["address"], 16), int(row["size"])
            if not img.free(addr):
                continue          # placed with an earlier function of the same section
            name = row["name"].split(": ", 1)[-1]
            sized = by_size.get(size, []) if name or size >= MIN_SIZE else []
            for obj, sym in by_name.get(name, []) + placed_statics(name, addr) + sized:
                sec = obj.secs[sym.section - 1]
                start, body = addr - sym.value, body_size(sec)
                if not masked_match(img, sec, start, max(body, sym.value + size)):
                    continue
                if not placer.refs_agree(obj, sec, start):
                    continue
                if (id(obj), sec.index) in placer.placed:
                    # Linked twice (std::_Lockit): a second copy of the member.
                    obj = parse(obj.path, obj.raw, library=True)
                    placer.objects.append(obj)
                    sec = obj.secs[sym.section - 1]
                placer.place(obj, sec, 0, body, start, LIBCODE, sym.name)
                placer.stats["library sections placed"] += 1
                if name and sym.name != name:
                    placer.renamed.append(f"{addr:#x}: data/functions.csv says {name}, the member placed "
                                          f"there defines {sym.name} ({obj.path.name})")
                # What is placed now names its address for the calls_agree of the rest.
                for other in obj.externals.values():
                    if other.section == sec.index:
                        named_at[start + other.value] = other.name
                break
            else:
                left.append(row)
        if len(left) == len(pending):
            break
        pending = left
    placer.stats["library functions with no matching member by name"] += len(pending)

    # Functions with no FPO record of their own hide inside other functions'
    # rows (__allshr and __allshl follow __ftol, _acos follows _strcspn): try
    # every member at each free 16-byte boundary of the library rows, by its
    # first fixed bytes (6 to 8, up to its first relocation). A member whose
    # first public symbol is not at its start goes too (87tran.obj's .text
    # opens with a private routine).
    by_prefix: dict[bytes, list[tuple[Obj, Sec, str]]] = defaultdict(list)
    for m in members:
        for sec in m.secs:
            if not sec.is_code or body_size(sec) < 8:
                continue
            fixed = min([off for off, _, _ in sec.relocs] + [8])
            names = sorted((s.value, s.name) for s in m.externals.values() if s.section == sec.index)
            if fixed >= 6 and names:
                by_prefix[sec.data[:fixed]].append((m, sec, names[0][1]))
    for row in rows:
        addr, size = int(row["address"], 16), int(row["size"])
        for at in range((addr + 15) & ~15, addr + size, 16):
            if not img.free(at):
                continue
            o = at - img.base
            found = [c for k in (8, 7, 6) for c in by_prefix.get(bytes(img.pristine[o:o + k]), ())]
            for obj, sec, label in found:
                if (id(obj), sec.index) in placer.placed:
                    continue
                if masked_match(img, sec, at, body_size(sec)) and placer.refs_agree(obj, sec, at):
                    placer.place(obj, sec, 0, body_size(sec), at, LIBCODE, label)
                    placer.stats["library sections placed inside other rows"] += 1
                    break


def place_unreferenced_library(placer: Placer) -> None:
    """The short library rows data/functions.csv has no name for that nothing
    placed refers to (place_library leaves them to placer.relocate): by size
    and bytes, the first member that matches."""
    img = placer.img
    for row in load_rows(FUNCTIONS):
        addr, size = int(row["address"], 16), int(row["size"])
        if row["kind"] != "library" or row["name"] or size >= MIN_SIZE or not img.free(addr):
            continue
        for obj, sym in placer.by_size.get(size, []):
            sec = obj.secs[sym.section - 1]
            body = body_size(sec)
            if not masked_match(img, sec, addr, body) or not placer.refs_agree(obj, sec, addr):
                continue
            if (id(obj), sec.index) in placer.placed:
                obj = parse(obj.path, obj.raw, library=True)
                placer.objects.append(obj)
                sec = obj.secs[sym.section - 1]
            placer.place(obj, sec, 0, body, addr, LIBCODE, sym.name)
            placer.stats["library sections placed by size, with nothing referring to them"] += 1
            break


def place_section_rest(placer: Placer) -> None:
    """The slices nothing refers to of a data section placed in one piece
    or several at one base: each where its offset puts it, when the original
    holds its bytes there (zlib's copyright strings, the runtime library's
    constants). LINK keeps a section whole, whatever its symbols."""
    img = placer.img
    for (_, index), pieces in list(placer.placed.items()):
        p0 = pieces[0]
        sec, obj = p0.sec, p0.obj
        if sec.is_code or sec.name.startswith(SKIP_SECTIONS) or obj.data:
            continue
        base = p0.va - p0.lo
        if any(p.va - p.lo != base for p in pieces):
            continue
        bounds = sorted(set(sec.starts) | {0, len(sec.data)})
        for lo, hi in zip(bounds, bounds[1:]):
            if lo >= hi or placer.address_in(obj, index, lo) is not None:
                continue
            va = base + lo
            if not all(img.free(v) for v in range(va, va + hi - lo)):
                continue
            if sec.chars & SCN_UNINIT:
                o = va - img.base
                if any(img.pristine[o:o + hi - lo]):
                    continue
            elif not masked_match(img, Sec(index, sec.name, sec.chars, sec.data[lo:hi],
                                           [(off - lo, s, r) for off, s, r in sec.relocs if lo <= off < hi]),
                                  va, hi - lo):
                continue
            placer.place(obj, sec, lo, hi, va, p0.source, f"{sec.name} of {obj.path.stem} (+{lo:#x})")
            placer.stats["data placed with the rest of its section"] += 1


def place_member_data(placer: Placer) -> None:
    """The initialised data sections nothing refers to of the library members
    placed (throw.obj's and frame.obj's pointers to the unhandled exception
    filter): each where the original holds its bytes among the data nothing
    defines yet, its pointers leading where the member's lead. Members that
    hold the same bytes take the places in turn. A section of only zeros
    could go anywhere, and is left; so is one whose bytes the original holds
    in more than one place, unless a pointer in it says where it belongs."""
    img = placer.img
    rdata = next(s for s in img.sections if s[0] == ".rdata")
    data = next(s for s in img.sections if s[0] == ".data")
    lo, hi = rdata[1] - img.base, data[1] + data[3] - img.base
    tables = bytearray(img.size)
    for va, n in img.fixed_ranges():
        tables[va - img.base:va - img.base + n] = b"\1" * n
    open_ = bytearray(int(img.src[o] == UNSET and not tables[o]) for o in range(img.size))
    placed_objs = {key[0] for key in placer.placed}
    for obj in placer.objects:
        if not obj.library or id(obj) not in placed_objs:
            continue
        for sec in obj.secs:
            if (sec.is_code or sec.chars & SCN_UNINIT or (id(obj), sec.index) in placer.placed
                    or sec.name.startswith(SKIP_SECTIONS + (".CRT", ".xdata", ".tls"))
                    or not sec.data or not (any(sec.data) or sec.relocs)):
                continue
            n = (sec.chars >> 20) & 0xF
            align = 1 << (n - 1) if n else 16
            size = len(sec.data)
            found = []                         # (address, pointers that agree)
            for o in range(lo + (-(img.base + lo)) % align, hi - size + 1, align):
                if 0 in open_[o:o + size]:
                    continue
                va = img.base + o
                if not masked_match(img, sec, va, size):
                    continue
                pointers = 0
                for off, symidx, rtype in sec.relocs:
                    sym = obj.syms[symidx]
                    target = placer.globals.get(sym.name) if rtype == REL_DIR32 and sym.section <= 0 else None
                    if target is None:
                        continue
                    (addend,) = struct.unpack_from("<I", sec.data, off)
                    if (target + addend) & 0xFFFFFFFF != img.u32(va + off):
                        break
                    pointers += 1
                else:
                    found.append((va, pointers))
            if len(found) == 1 or (found and found[0][1]):
                va = found[0][0]
                placer.place(obj, sec, 0, size, va, LIBDATA, f"{sec.name} of {obj.path.stem}")
                open_[va - img.base:va - img.base + size] = bytes(size)
                placer.stats["library data placed by its bytes, with nothing referring to it"] += 1


def import_libraries() -> dict[str, Path]:
    """The import libraries the original was linked with, by the name of
    their DLL (lower-cased): the toolchain's; WIN32.LIB for GOG's winmm
    (tools/link.py's copy of WINMM.LIB with the DLL renamed); and LIB.EXE's
    from link/*.def (built once into build/place/) for the DLLs the toolchain
    has no library for (smackw32, DPLAYX) or numbers the hints of differently
    (DirectX 5's DDRAW and DSOUND), which take the place of the toolchain's."""
    from link import build_win32_lib
    from linkcheck import IMPORT_LIBS, LIBDIR
    paths = [LIBDIR / f"{name}.LIB" for name in IMPORT_LIBS if (LIBDIR / f"{name}.LIB").exists()]
    paths.append(build_win32_lib())
    paths += [def_library(path) for path in DEF_FILES]
    out = {}
    for path in paths:
        for member in read_library(path):
            if any(s.name.startswith("__IMPORT_DESCRIPTOR_") and s.section > 0 for s in member.syms.values()):
                name = next(s for s in member.secs if s.name == ".idata$6").data.split(b"\0", 1)[0]
                out[name.decode().lower()] = path
                break
    return out


def def_library(path: Path) -> Path:
    """LIB.EXE's import library for a link/*.def file, built into build/place/
    (once). The file spells each export as its __stdcall symbol does
    (DirectDrawCreate@12), and LIB is given the names without the decoration
    and an object that defines the decorated symbols, the way an SDK's import
    library is made beside its DLL: the import is by the plain name (the hint
    is its place among the sorted names), and the library defines
    __imp__DirectDrawCreate@12 for the callers."""
    from check import winpath
    from link import write_stub_object
    import subprocess
    lib = OUT_DIR / f"{path.stem.upper()}.LIB"
    if lib.exists() and lib.stat().st_mtime >= path.stat().st_mtime:
        return lib
    lines, symbols = [], []
    for line in path.read_text().splitlines():
        line = line.split(";", 1)[0].strip()
        m = re.match(r"([A-Za-z_]\w*)(@\d+)?(\s+@\d+(?:\s+NONAME)?)?$", line)
        if m and line.split()[0] not in ("LIBRARY", "EXPORTS"):
            symbols.append("_" + m.group(1) + (m.group(2) or ""))
            line = m.group(1) + (m.group(3) or "")
        lines.append(line)
    lib.parent.mkdir(parents=True, exist_ok=True)
    plain, stub = lib.with_suffix(".def"), lib.with_suffix(".obj")
    plain.write_text("\n".join(lines) + "\n")
    write_stub_object(symbols, [], stub)
    lib.unlink(missing_ok=True)
    proc = subprocess.run([str(ROOT / "tools/wlib"), f"/def:{winpath(plain)}", winpath(stub), f"/out:{winpath(lib)}"],
                          capture_output=True, text=True, cwd=ROOT)
    if proc.returncode or not lib.exists():
        raise SystemExit(f"LIB could not build {lib.name} from {path.name}:\n{proc.stdout}{proc.stderr}")
    return lib


@dataclass
class ImportLibrary:
    """An import library's members (VC5's long format: each an object with
    .idata$ sections), by their part in the import tables."""
    descriptor: Obj = None          # .idata$2, the import descriptor, and .idata$6, the DLL's name
    null_descriptor: Obj = None     # .idata$3, the descriptor that ends the directory
    null_thunk: Obj = None          # .idata$4 and .idata$5, the entries that end the DLL's tables
    functions: dict = field(default_factory=dict)   # name or ordinal -> its member: .idata$4, $5, $6, the thunk

    @classmethod
    def read(cls, path: Path) -> "ImportLibrary":
        lib = cls()
        for m in read_library(path):
            defined = [s.name for s in m.syms.values() if s.section > 0 and s.sclass == 2]
            if any(n.startswith("__IMPORT_DESCRIPTOR_") for n in defined):
                lib.descriptor = m
            elif "__NULL_IMPORT_DESCRIPTOR" in defined:
                lib.null_descriptor = m
            elif any(n.endswith("_NULL_THUNK_DATA") for n in defined):
                lib.null_thunk = m
            elif any(n.startswith("__imp_") for n in defined):
                thunk = next(s for s in m.secs if s.name == ".idata$5")
                (value,) = struct.unpack_from("<I", thunk.data, 0)
                if value & 0x80000000:
                    lib.functions[value & 0xFFFF] = m
                else:
                    name = next(s for s in m.secs if s.name == ".idata$6").data[2:].split(b"\0", 1)[0]
                    lib.functions[name.decode()] = m
        return lib


def place_imports(placer: Placer) -> None:
    """The import tables, from the import libraries' members, as LINK puts
    them together: the descriptors (.idata$2) in the order LINK pulled their
    DLLs in, and the null one (.idata$3) after them; each DLL's lookup and
    address tables (.idata$4 and .idata$5), its members' entries and then its
    null thunk's, the DLLs in the order of their names; and the hints and
    names (.idata$6) and the DLLs' names in the order LINK pulled the members
    in. The address table goes at the start of .rdata, the rest at its end.
    The orders follow Cavedog's objects, which the tree does not have (and
    within a DLL's tables, LINK's own bookkeeping), so each member goes where
    the original's import directory has it, as every other piece goes where
    the original has it; the bytes and relocations are the members'. The
    descriptors' section symbols (.idata$4, .idata$5) mean where the DLL's
    tables start."""
    img = placer.img
    libs = import_libraries()
    directory = img.base + img.pe.OPTIONAL_HEADER.DATA_DIRECTORY[1].VirtualAddress
    entries = img.pe.DIRECTORY_ENTRY_IMPORT

    def put(obj: Obj, name: str, va: int, label: str) -> None:
        sec = next(s for s in obj.secs if s.name == name)
        placer.place(obj, sec, 0, len(sec.data), va, IMPORTS, f"{name} of {label}")
        placer.stats["import table pieces placed from the import libraries"] += 1

    def own(member: Obj) -> Obj:
        obj = parse(member.path, member.raw, library=True)    # each placed once
        placer.objects.append(obj)
        return obj

    null_descriptor = None
    for i, entry in enumerate(entries):
        dll = entry.dll.decode()
        if dll.lower() not in libs:
            placer.mismatches.append(f"{dll}: no import library names this DLL")
            continue
        lib = ImportLibrary.read(libs[dll.lower()])
        desc = own(lib.descriptor)
        put(desc, ".idata$2", directory + 20 * i, dll)
        put(desc, ".idata$6", img.base + entry.struct.Name, dll)
        desc.section_starts = {".idata$4": img.base + entry.struct.OriginalFirstThunk,
                               ".idata$5": img.base + entry.struct.FirstThunk}
        for k, imp in enumerate(entry.imports):
            key = imp.name.decode() if imp.name else imp.ordinal
            if key not in lib.functions:
                placer.mismatches.append(f"{dll}: {key} is not in {libs[dll.lower()].name}")
                continue
            member = own(lib.functions[key])
            label = f"{dll}!{key}"
            put(member, ".idata$5", imp.address, label)
            put(member, ".idata$4", img.base + entry.struct.OriginalFirstThunk + 4 * k, label)
            if imp.name:
                put(member, ".idata$6", img.base + imp.hint_name_table_rva, label)
            placer.import_members[imp.address] = member
        n = len(entry.imports)
        null_thunk = own(lib.null_thunk)
        put(null_thunk, ".idata$5", img.base + entry.struct.FirstThunk + 4 * n, f"{dll} (the end)")
        put(null_thunk, ".idata$4", img.base + entry.struct.OriginalFirstThunk + 4 * n, f"{dll} (the end)")
        null_descriptor = null_descriptor or lib.null_descriptor
    if null_descriptor:
        put(own(null_descriptor), ".idata$3", directory + 20 * len(entries), "the import directory (the end)")


def thunk_runs() -> list[tuple[int, int]]:
    """(address, size) of the rows that can hold the linker's import stubs:
    the gap rows, and the library rows with no name."""
    return [(int(r["address"], 16), int(r["size"])) for r in load_rows(FUNCTIONS)
            if r["kind"] == "gap" or (r["kind"] == "library" and not r["name"])]


def place_import_thunks(placer: Placer) -> None:
    """The linker's `jmp [slot]` stubs for calls to imports declared without
    __declspec(dllimport). They are the .text of the import libraries'
    members, and the original keeps two runs of them: in the gap row 0x49f710,
    and after the runtime library in the unnamed library row 0x4faff0 (the
    import libraries LINK searched last). Each member goes where the original
    has its stub. The member is the one place_imports placed the tables
    from, so the stub's slot is its own .idata$5."""
    slots = {name: a for (_, name), a in placer.import_slots.items()}
    gaps = [(int(r["address"], 16), int(r["size"])) for r in load_rows(FUNCTIONS) if r["kind"] == "gap"]
    runs = thunk_runs()
    for name, addr in sorted(placer.thunks.items(), key=lambda kv: kv[1]):
        member = placer.import_members.get(slots.get(name))
        if not any(a <= addr < a + n for a, n in runs) or not placer.img.free(addr) or member is None:
            continue
        sec = next((s for s in member.secs if s.is_code and s.data[:2] == b"\xff\x25"), None)
        if sec is None:
            continue
        placer.place(member, sec, 0, len(sec.data), addr, LIBCODE, f"{name} (import thunk)")
        placer.stats["import thunks placed from the import libraries"] += 1
    for addr, size in runs:
        if all(not placer.img.free(a) for a in range(addr, addr + size)):
            if (addr, size) in gaps:
                placer.built_regions.add(addr)
            img = placer.img
            for o in range(addr + size - img.base, ((addr + size + 15) & ~15) - img.base):
                if img.src[o] == UNSET and img.pristine[o] in (0x90, 0xCC):
                    img.out[o], img.src[o] = img.pristine[o], PADDING


def library_names(placer: Placer) -> None:
    for row in load_rows(FUNCTIONS):
        if row["kind"] == "library" and row["name"]:
            name = row["name"].split(": ", 1)[-1]
            placer.library[name].append(int(row["address"], 16))


def copy_unbuilt(img: Image, sections: list) -> None:
    """What nothing built, from the original, counted as copied (nothing, now
    that every piece has its source), and the linker's zero fill: past each
    section's contents up to its raw size, and in .data's .bss."""
    text = next(x for x in sections if x.name == ".text")
    text_start, text_size = img.base + text.rva, text.vsize
    for row in load_rows(FUNCTIONS):
        addr, size = int(row["address"], 16), int(row["size"])
        # With its alignment padding, up to the end of .text's contents (the
        # zero fill after them is the linker's, below).
        size = min((addr + size + 15) & ~15, text_start + text_size) - addr
        if row["kind"] == "gap":
            img.copy(addr, size, GAP)
        elif row["kind"] == "library":
            if img.free(addr):
                img.copied_library.append((addr, row["name"]))
            # Alignment padding: nops (the compiler's) or int3s (the linker's,
            # after assembler code) up to a 16-byte boundary, after the row's
            # functions and after the ones placed inside it.
            run = None
            for o in range(addr - img.base, addr + size - img.base + 1):
                pad = o < addr + size - img.base and img.src[o] == UNSET and img.pristine[o] in (0x90, 0xCC)
                if pad and run is None:
                    run = o
                elif not pad and run is not None:
                    if (img.base + o) % 16 == 0 or o == addr + size - img.base:
                        img.out[run:o], img.src[run:o] = img.pristine[run:o], bytes([PADDING]) * (o - run)
                    run = None
            img.copy(addr, size, LIBRARY)
    for x in sections:
        name, start, vsize, rsize = x.name, img.base + x.rva, x.vsize, x.raw
        # Past each section's virtual size: the linker's zero fill.
        for i in range(start + vsize - img.base, start + max(vsize, rsize) - img.base):
            if img.src[i] == UNSET:
                img.out[i], img.src[i] = 0, PADDING
        # Past its raw data (.data's .bss): bytes the file does not hold, which
        # the loader zeroes. Those no object defines are alignment, or
        # variables of Cavedog's objects that the tree's objects leave out
        # (0x51fc98, before 0x4b7ad0's vector).
        for i in range(start + rsize - img.base, start + vsize - img.base):
            if img.src[i] == UNSET:
                img.out[i], img.src[i] = 0, UNINIT
    # Everything still unset is data or padding no object defines yet.
    for x in sections:
        img.copy(img.base + x.rva, max(x.vsize, x.raw), COPIED)


def place_crt_tables(placer: Placer) -> None:
    """The C runtime's tables of initialisers and terminators (__xc_a to
    __xc_z and the rest at the start of .data), which LINK builds from every
    object's .CRT$X* sections: each section holds a pointer to one function,
    and goes where the original's table holds that function's address."""
    img = placer.img
    data = next(s for s in img.sections if s[0] == ".data")
    lo, hi = data[1], data[1] + 0x100
    slots: dict[int, list[int]] = defaultdict(list)
    for va in range(lo, hi, 4):
        v = img.u32(va)
        if v:
            slots[v].append(va)
    for obj in list(placer.objects):
        for sec in obj.secs:
            if not sec.name.startswith(".CRT$X") or len(sec.data) != 4 or len(sec.relocs) != 1:
                continue
            off, symidx, rtype = sec.relocs[0]
            sym = obj.syms[symidx]
            if sym.section > 0:
                target = placer.address_in(obj, sym.section, sym.value)
            else:
                target = placer.globals.get(sym.name) or placer.named_address(sym.name)
            for va in slots.get(target, ()):
                if img.free(va):
                    placer.place(obj, sec, 0, 4, va, LIBDATA if obj.library else OBJDATA,
                                 f"{sec.name} of {obj.path.stem}")
                    placer.stats["initialiser table entries placed from .CRT$X* sections"] += 1
                    break
    # The original's initialisers the tree spells as ordinary functions
    # (FUN_004205f0): tools/link.py gives each a .CRT$XCU entry of its own.
    from link import write_init_object
    names = {a: n for n, a in placer.globals.items()}
    for v, vas in sorted(slots.items()):
        va = next((a for a in vas if img.free(a)), None)
        if va is None or v not in names or not img.inside(v) or img.src[v - img.base] not in (CODE, GAPCODE):
            continue
        path = OUT_DIR / "init" / f"{v:08x}.obj"
        path.parent.mkdir(parents=True, exist_ok=True)
        write_init_object(names[v], path)
        obj = parse(path)
        placer.objects.append(obj)
        placer.place(obj, obj.secs[0], 0, 4, va, OBJDATA, f".CRT$XCU for {names[v]}")
        placer.stats["initialiser table entries placed from .CRT$X* sections"] += 1
    placer.relocate()
    # A table's end that nothing refers to (.CRT$XLZ, after the empty table of
    # TLS callbacks that __tls_used points at) goes right after the last
    # entry placed in its table: LINK puts .CRT$XLA to .CRT$XLZ together.
    placed = {(id(p.obj), p.sec.index): p for p in placer.pieces}
    for obj in list(placer.objects):
        for sec in obj.secs:
            if not (sec.name.startswith(".CRT$X") and sec.name.endswith("Z")) or (id(obj), sec.index) in placed:
                continue
            group = [p for p in placed.values() if p.sec.name.startswith(sec.name[:-1]) and p.sec.name < sec.name]
            if not group or not any(p.obj is obj for p in group):
                continue
            last = max(group, key=lambda p: p.va)
            placer.place(obj, sec, 0, len(sec.data), last.va + last.hi - last.lo,
                         LIBDATA if obj.library else OBJDATA, f"{sec.name} of {obj.path.stem}")
            placer.stats["initialiser table ends placed after their tables"] += 1


def place_commons(placer: Placer) -> None:
    """Communal variables (uninitialised data a C object defines without a
    section, such as string.obj's guards), where the original has them: LINK
    allocates each in .bss at the size its definers give it."""
    img = placer.img
    library = {name for obj in placer.objects if obj.library for name in obj.commons}
    for name, addr in sorted(placer.common_at.items(), key=lambda kv: kv[1]):
        size = placer.commons.get(name, 0)
        if not size or not img.inside(addr):
            continue
        source = LIBDATA if name in library else OBJDATA
        if img.write(addr, bytes(size), source) == 0:
            placer.stats["communal variables placed where the original has them"] += 1
        # LINK aligns each to its size, up to 32 bytes (___pioinfo's 256 bytes
        # follow __crtheap's 4 after 24 bytes of zeros).
        align = 1 << min(5, size.bit_length() - 1)
        o = addr - img.base
        run = o
        while run > o - align + 1 and img.src[run - 1] == UNSET:
            run -= 1
        if not addr % align and run < o and img.src[run - 1] != UNSET and not any(img.pristine[run:o]):
            for i in range(run, o):
                img.out[i], img.src[i] = 0, PADDING


def pad_data(placer: Placer) -> None:
    """The linker's alignment padding between pieces of data: zeros after
    one placed piece, up to the next placed piece at its section's alignment
    (a string literal of six bytes, then two zeros before the next one)."""
    img = placer.img
    for p in sorted(placer.pieces, key=lambda p: p.va):
        if p.sec.is_code:
            continue
        n = (p.sec.chars >> 20) & 0xF
        # One global of a section that holds several: a dword's alignment, or
        # a double's for an eight-byte global on an eight-byte boundary.
        align = (1 << (n - 1) if n else 16) if not p.lo else (8 if p.hi - p.lo == 8 and not p.va % 8 else 4)
        o = p.va - img.base
        if align < 2 or p.va % align:
            continue
        run = o
        while run > o - align + 1 and img.src[run - 1] == UNSET and not img.pristine[run - 1]:
            run -= 1
        if run < o and img.src[run - 1] != UNSET:
            for i in range(run, o):
                img.out[i], img.src[i] = 0, PADDING
    # Zeros before a piece of the game's data at an eight- or sixteen-byte
    # boundary, fewer than that: the original's sections there began at that
    # alignment (most of the DirectX setup code's strings start on eight-byte
    # boundaries), and the tree's objects, one function each, cannot say
    # where they began.
    for p in sorted(placer.pieces, key=lambda p: p.va):
        if p.sec.is_code or p.obj.library:
            continue
        align = min(16, p.va & -p.va)
        if align < 8:
            continue
        o = p.va - img.base
        run = o
        while run > o - align + 1 and img.src[run - 1] == UNSET and not img.pristine[run - 1]:
            run -= 1
        if run < o and img.src[run - 1] != UNSET:
            for i in range(run, o):
                img.out[i], img.src[i] = 0, PADDING
    # Zeros between two pieces of the runtime library's data, up to a 16-byte
    # boundary where the second begins: assembler members (strchr.obj,
    # memmove.obj and the like) have empty .data sections aligned to 16
    # bytes, and LINK aligned for each one it laid out there.
    for p in sorted(placer.pieces, key=lambda p: p.va):
        if p.sec.is_code or not p.obj.library or p.va % 16:
            continue
        o = p.va - img.base
        run = o
        while run > o - 15 and img.src[run - 1] == UNSET and not img.pristine[run - 1]:
            run -= 1
        prev = img.owner[run - 1]
        if run < o and prev and placer.pieces[prev - 1].obj.library:
            for i in range(run, o):
                img.out[i], img.src[i] = 0, PADDING


def place_resources(placer: Placer) -> None:
    """The resources, compiled from src/res/TotalA.rc and the game's icon and
    cursor (tools/resources.py: from --art or BT_ART_DIR, or extracted from
    orig/TotalA.exe). CVTRES's object holds the resource directory as
    .rsrc$01 and the data as .rsrc$02,
    which LINK puts at the start of .rsrc in that order, each at its
    alignment. Their relocations are the data entries' addresses."""
    from resources import build
    obj = parse(build())
    placer.objects.append(obj)
    placer.resources = obj
    va = next(start for name, start, *_ in placer.img.sections if name == ".rsrc")
    for sec in sorted((s for s in obj.secs if s.name.startswith(".rsrc$")), key=lambda s: s.name):
        n = (sec.chars >> 20) & 0xF
        align = 1 << (n - 1) if n else 16
        start = (va + align - 1) & ~(align - 1)
        placer.img.write(va, bytes(start - va), PADDING)
        placer.place(obj, sec, 0, len(sec.data), start, RESOURCES, f"{sec.name} of {obj.path.name}")
        placer.stats["resource sections placed from src/res"] += 1
        va = start + len(sec.data)


# --- what LINK adds: the headers and the debug data ------------------------------------

def place_debug_directory(placer: Placer) -> None:
    """LINK writes its debug directory into .rdata right after the import
    address table; its contents (link_image) wait for the file's layout."""
    iat = [p for p in placer.pieces if p.sec.name == ".idata$5"]
    va = max(p.va + p.hi - p.lo for p in iat)
    import pe
    size = pe.DEBUG_ENTRY * 3
    placer.img.write(va, bytes(size), DEBUGDIR)
    placer.debug_directory = va


def image_sections(placer: Placer, settings: dict) -> list:
    """The output sections, from what is placed: LINK starts each at the
    section alignment after the one before, so a section runs from such a
    boundary to its last byte before a gap that reaches the next boundary.
    It is named for its first piece's input section (the import address
    table's .idata$5 opens .rdata, the C runtime's .CRT$XIA opens .data), its
    raw data runs to its last piece of initialised data, at the file
    alignment, and its characteristics are those of its input sections of
    its own name, less their alignment and COMDAT flags. The tree's objects
    do not always put a piece in the section the original had it in (a
    string the original kept in .rdata, one of the tree's objects in .data),
    so the names of the pieces inside say less than where they are."""
    import pe
    img = placer.img
    align = settings["section_alignment"]
    src = img.src
    by_start = sorted(placer.pieces, key=lambda p: p.va)
    sections = []
    o = align
    while o < img.size:
        while o < img.size and src[o] == UNSET:
            o += 1
        if o >= img.size:
            break
        start = o
        while True:
            while o < img.size and src[o] != UNSET:
                o += 1
            # A gap: the section ends here unless something is placed before
            # the next section boundary.
            boundary = min(pe.align(o, align), img.size)
            nxt = o
            while nxt < boundary and src[nxt] == UNSET:
                nxt += 1
            if nxt >= boundary:
                break
            o = nxt
        end = o
        inside = [q for q in by_start if start <= q.va - img.base < end]
        first = OUTPUT_SECTIONS.get(inside[0].sec.name.split("$", 1)[0], inside[0].sec.name)
        initialised = [q for q in inside if not q.sec.chars & SCN_UNINIT]
        raw_end = max(q.va + q.hi - q.lo for q in initialised) - img.base if initialised else start
        own = [q for q in inside if q.sec.name.split("$", 1)[0] == first] or inside
        chars = own[0].sec.chars & 0xFE0000E0
        sections.append(pe.Section(first, start, end - start, pe.align(raw_end - start, settings["file_alignment"]),
                                   chars))
        o = pe.align(end, align)
    return sections


def fpo_records(placer: Placer) -> list[bytes]:
    """Every placed function's frame pointer omission record (FPO_DATA), from
    its object's .debug$F with the function's address in it, sorted by
    address as LINK sorts them. A record whose relocation names an undefined
    symbol (the compiler's scalar deleting destructors refer to their own
    function so) means the definition of that name in the same object."""
    records = {}
    for p in placer.pieces:
        if not p.sec.is_code:
            continue
        obj = p.obj
        for sec in obj.secs:
            if sec.name != ".debug$F":
                continue
            for off, symidx, rtype in sec.relocs:
                sym = obj.syms[symidx]
                if sym.section == 0 and sym.name in obj.externals:
                    sym = obj.externals[sym.name]
                (addend,) = struct.unpack_from("<I", sec.data, off)
                at = sym.value + addend
                if rtype != REL_DIR32NB or sym.section != p.sec.index or not p.lo <= at < p.hi:
                    continue
                rva = p.va + at - p.lo - placer.img.base
                record = bytearray(sec.data[off:off + 16])
                struct.pack_into("<I", record, 0, rva)
                records[rva] = bytes(record)
    return [records[rva] for rva in sorted(records)]


def link_image(placer: Placer, settings: dict, sections: list):
    """The image as the headers describe it, and the debug records. The
    debug directory's contents go into the image here, now that the file's
    layout says where the records are."""
    import pe
    img = placer.img
    imports = [p for p in placer.pieces if p.sec.name in (".idata$2", ".idata$3")]
    iat = [p for p in placer.pieces if p.sec.name == ".idata$5"]
    rsrc = next(x for x in sections if x.name == ".rsrc")
    entry = placer.globals.get(settings["entry"])
    if entry is None:
        raise SystemExit(f"no placed function is the entry point {settings['entry']}")
    directories = {
        pe.DIR_IMPORT: (min(p.va for p in imports) - img.base, sum(p.hi - p.lo for p in imports)),
        pe.DIR_RESOURCE: (rsrc.rva, rsrc.vsize),
        pe.DIR_DEBUG: (placer.debug_directory - img.base, 3 * pe.DEBUG_ENTRY),
        pe.DIR_TLS: (placer.tls_directory - img.base, 24),
        pe.DIR_IAT: (min(p.va for p in iat) - img.base, sum(p.hi - p.lo for p in iat)),
    }
    rich = [(0, settings["unmarked_objects"])]
    compid = placer.resources.absolutes.get("@comp.id") if placer.resources else None
    if compid is None and placer.resources:
        compid = next((s.value for s in placer.resources.syms.values() if s.name == "@comp.id"), None)
    if compid is not None:
        rich.append((compid, 1))
    image = pe.Image(sections, entry - img.base, directories, fpo_records(placer), rich)
    records = pe.debug_records(settings, image.fpo)
    pointer = pe.layout_file(settings, image)
    directory = pe.debug_directory(settings, records, pointer)
    o = placer.debug_directory - img.base
    img.out[o:o + len(directory)] = directory
    return image, records


def write_exe(placer: Placer, settings: dict, out: Path) -> bytes:
    """The exe: the generated headers, each section's raw data from the
    image, and the debug records after them (tools/pe.py)."""
    import pe
    img = placer.img
    contents = {x.name: bytes(img.out[x.rva:x.rva + x.raw]) for x in placer.exe.sections}
    return pe.write(out, settings, placer.exe, contents, placer.debug_records)


def write_map(placer: Placer, out: Path) -> None:
    rows = sorted((p.va, p.hi - p.lo, SOURCES[p.source], p.label, p.obj.path.name) for p in placer.pieces)
    with out.open("w") as fh:
        fh.write("address,size,source,symbol,object\n")
        for va, size, source, label, obj in rows:
            fh.write(f"{va:#x},{size},{source},{label},{obj}\n")


# --- the report ---------------------------------------------------------------------

def compare(img: Image, placer: Placer, verbose: bool) -> tuple[int, list[str]]:
    """Bytes of the built image that differ from the original, by source."""
    def label(va: int) -> str:
        pid = img.owner[va - img.base]
        if not pid:
            return ""
        p = placer.pieces[pid - 1]
        return f"{p.label}+{va - p.va:#x}" + (f" (placed for {p.why})" if p.why else "")

    patched = set()
    for at, size, _ in img.patches:
        patched.update(range(at - img.base, at - img.base + size))
    lines, total, by_source, run = [], 0, Counter(), None
    for name, start, vsize, rsize, _ in img.sections:
        lo, hi = start - img.base, start - img.base + max(vsize, rsize)
        for i in range(lo, hi + 1):
            differs = i < hi and img.out[i] != img.orig[i] and i not in patched
            if differs:
                total += 1
                by_source[SOURCES[img.src[i]]] += 1
                if run is None:
                    run = i
            elif run is not None:
                va = img.base + run
                lines.append(f"  {va:#x}..{img.base + i:#x} ({i - run} bytes, {SOURCES[img.src[run]]}) {label(va)}")
                run = None
    out = [f"bytes that differ from the original, outside data/exe_patches.csv: {total:,}"]
    out += [f"  {k}: {v:,}" for k, v in by_source.most_common()]
    patch_diff = sum(1 for i in patched if img.out[i] != img.orig[i])
    if img.patches:
        out.append(f"bytes under data/exe_patches.csv that differ from the original: {patch_diff:,} "
                   "(GOG's patch is applied after the link; --no-exe-patches leaves the compiler's bytes)")
    shown = lines if verbose else lines[:20] + (["  ..."] if len(lines) > 20 else [])
    return total, out + shown


def report(img: Image, placer: Placer, verbose: bool) -> int:
    print("placement:")
    for k, v in sorted(placer.stats.items()):
        print(f"  {k}: {v:,}")
    counts = Counter()
    for x in placer.exe.sections:
        for i in range(x.rva, x.rva + max(x.vsize, x.raw)):
            counts[(x.name, img.src[i])] += 1
    print("where each section's bytes come from:")
    for x in placer.exe.sections:
        parts = [f"{SOURCES[s]} {counts[(x.name, s)]:,}" for s in range(len(SOURCES)) if counts[(x.name, s)]]
        print(f"  {x.name:6} {max(x.vsize, x.raw):>9,}: " + ", ".join(parts))
    headers = placer.exe.sections[0].pointer
    debug = sum(len(data) for _, data in placer.debug_records)
    print(f"  headers {headers:,} and debug records {debug:,} (after the sections): generated (tools/pe.py)")
    limit = None if verbose else 15
    for title, items in (("relocations that disagree with the original, and missing definitions", placer.mismatches),
                         ("pieces that differ from a piece already placed there", placer.clashes),
                         ("library functions data/functions.csv names differently", placer.renamed)):
        if items:
            print(f"{title}: {len(items):,}")
            for m in items[:limit]:
                print("  " + m)
    if img.copied_library:
        print(f"library functions copied, with no member placed: {len(img.copied_library):,}")
        for addr, name in img.copied_library[:limit]:
            print(f"  {addr:#x} {name}")
    if placer.unresolved:
        print(f"names whose address only the original's bytes give: {len(placer.unresolved):,}")
        for name, n in placer.unresolved.most_common(limit):
            print(f"  {name} ({n})")
    total, lines = compare(img, placer, verbose)
    print("\n".join(lines))
    return total


def layout(jobs: int | None = None) -> tuple[Image, Placer]:
    """Lay the tree out at the original's addresses: the image and every
    placed piece. Other tools use it as a map of what each address holds."""
    paths, failed = compile_all(jobs)
    if failed:
        raise SystemExit(f"{len(failed)} file(s) did not compile; tools/link.py lists them")
    symbols = load_symbols()
    # src/lib/ is runtime library code: placed with the library members.
    lib_objs = ROOT / "build/progress" / LIB_DIR.relative_to(ROOT / "src")
    lib_paths = [p for p in paths if p.is_relative_to(lib_objs)]
    paths = [p for p in paths if not p.is_relative_to(lib_objs)]
    objects = [parse(p) for p in paths]
    by_src = {}
    for p, obj in zip(paths, objects):
        by_src[str(Path("src") / p.relative_to(ROOT / "build/progress").with_suffix(".cpp"))] = obj

    img = Image(ROOT / "orig/TotalA.exe")
    placer = Placer(img, objects, symbols)
    library_names(placer)
    place_functions(placer, by_src)
    place_gaps(placer, gap_objects())
    place_library(placer, lib_paths)
    place_imports(placer)
    place_import_thunks(placer)
    place_tls(placer)
    place_tree_globals(placer, by_src)
    place_data_sources(placer, by_src)
    data_objs, data_addr = build_data(symbols)
    place_globals(placer, data_objs, data_addr)
    placer.relocate()
    place_unreferenced_library(placer)
    placer.relocate()
    place_section_rest(placer)
    placer.relocate()
    place_member_data(placer)
    placer.relocate()
    place_crt_tables(placer)
    place_commons(placer)
    pad_data(placer)
    place_resources(placer)
    placer.relocate()
    place_debug_directory(placer)
    from pe import settings
    link = settings()
    sections = image_sections(placer, link)
    placer.exe, placer.debug_records = link_image(placer, link, sections)
    copy_unbuilt(img, sections)
    return img, placer


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--output", type=Path, default=OUT_DIR / "TotalA.exe")
    ap.add_argument("--jobs", type=int, default=None, help="parallel compiles (default: all cores)")
    ap.add_argument("--strict", action="store_true", help="exit non-zero if any built byte differs")
    ap.add_argument("--no-exe-patches", action="store_true",
                    help="leave out data/exe_patches.csv (GOG's no-CD music patch): the compiler's bytes")
    ap.add_argument("--art", type=Path,
                    help="the directory with the game's icon and cursor (TotalA.ico, TotalA.cur) for the "
                         "resources (default: BT_ART_DIR, or extracted from orig/TotalA.exe)")
    ap.add_argument("--verbose", "-v", action="store_true")
    args = ap.parse_args()
    if args.art:
        import os
        os.environ["BT_ART_DIR"] = str(args.art.resolve())
    output = args.output if args.output.is_absolute() else ROOT / args.output

    img, placer = layout(args.jobs)
    if not args.no_exe_patches:
        from exepatch import apply_placed
        apply_placed(img.out, img.base)
    from pe import settings
    data = write_exe(placer, settings(), output)
    write_map(placer, output.with_suffix(".map"))
    total = report(img, placer, args.verbose)
    original = bytes(img.pe.__data__)
    differ = sum(a != b for a, b in zip(data, original)) + abs(len(data) - len(original))
    print(f"{output.relative_to(ROOT)}: {len(data):,} bytes, {differ:,} of them differ from orig/TotalA.exe "
          f"(headers {sum(a != b for a, b in zip(data[:0x400], original[:0x400])):,})")
    total += differ
    if args.strict and total:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
